### ISSUE TITLE
Please make alpine based image

### ISSUE THREAD

**Issue by freeseacher** [docker-library/mongo#100]
Current images is soo big

**Comment by abcfy2** [comment]
+1. Most official images offered alpine based image, but why mongo not ?

**Comment by yosifkit** [comment]
There was some work in https://github.com/docker-library/mongo/pull/80, but we'd rather not push an image that upstream is unwilling to support.

**Comment by tianon** [comment]
Closing for the same reason as in https://github.com/docker-library/mongo/pull/80#issuecomment-291966876:

> I think we need to revisit this once upstream is willing to support musl (which I really hope they come around to doing :disappointed:).
