### ISSUE TITLE
MongoDB ReplSet configuration

### ISSUE THREAD

**Issue by piugoyal** [docker-library/mongo#106]
Hi,

I have run the below docker command
docker run --dns=$IP --name=mongodb --restart=always -e IS_MASTER=true  -e MONGO_MASTER_HOSTNAME=\"*****\" -e SERVICE_27017_NAME=mongodb -e MONGO_AUTH=false -v /data/refdata/:/data/refdata/ -v /data/mongodb/:/data/db/ -dt -p 27017:27017  <imagename> --net mongo-test-network mongo_custom --smallfiles --replSet "rs0"

Docker container is up and running but when i am trying to execute rs.conf() , its giving null and rs.initiate command giving error as 

> rs.initiate()
> { "ok" : 0, "errmsg" : "server is not running with --replSet" }

Mongo version: 2.6.6

Please help me on this ASAP

**Comment by yosifkit** [comment]
Without knowing how `mongo_custom` is built, my guess is that your entrypoint is not passing the arguments `"$@"` to `mongod`.  In the official image, we do it with [line 5](https://github.com/docker-library/mongo/blob/7065352d915f03584da8a57cc070e612106496ef/3.2/docker-entrypoint.sh#L5) and then ensure that `mongod` is pid 1 with [line 21](https://github.com/docker-library/mongo/blob/7065352d915f03584da8a57cc070e612106496ef/3.2/docker-entrypoint.sh#L21) via `exec`.
