### ISSUE TITLE
Docker Mongo Version Questions

### ISSUE THREAD

**Issue by dlazov** [docker-library/mongo#108]
It looks like mongo just released version 3.2.8 [https://www.mongodb.com/download-center#enterprise](url) but this link [https://hub.docker.com/_/mongo/](url) shows a version 3.3 (3.3.10). 

Is 3.2 the current stable release and is 3.3 the in development release?

**Comment by dlazov** [comment]
It looks like MongoDB just released 3.2, yet, there are MongoDB Containers tagged up to version 3.3.10 (https://hub.docker.com/_/mongo/). 

Are these versions related?

We are running mongo 3.0.6 in production, what container version best matches that?

**Comment by yosifkit** [comment]
For MongoDB, the odd point releases are the development releases (`x.1`, `x.3`, etc...), while the even numbers are the actual releases (`x.0`, `x.2`, etc).  So currently the 3.2 series the the latest stable.  If you are looking on the Docker hub [page](https://hub.docker.com/r/library/mongo/), then you can also spot the newest stable by looking for `latest` or the newest stable of the `3.x` line by looking for `3`.

If you are looking for the `3.3` series on the [MongoDB download page](https://www.mongodb.com/download-center#community), then you have to click `Development Releases` at the top right of the green bordered box.

**Comment by yosifkit** [comment]
As for the newest `3.0` then there is a `3.0` tag which currently corresponds to `3.0.12` and can be pulled with `docker pull mongo:3.0` or `docker pull mongo:3.0.12`.  There are older images available, like `mongo:3.0.6`, but they are no longer updated.

**Comment by dlazov** [comment]
yosifkit thank you.
