### ISSUE TITLE
applying production notes recommendation

### ISSUE THREAD

**Issue by hbakhtiyor** [docker-library/mongo#112]
i'm getting these warnings

> Your database has startup warnings. This is typically a bad thing. See the "startupWarnings" field in this document for more information.
> Your database host/server has a low ulimit setting configured. For more information, see the MongoDB docs. 

```
Server has startup warnings: 
2016-09-15T10:42:28.494+0000 I CONTROL  [initandlisten] 
2016-09-15T10:42:28.494+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-09-15T10:42:28.494+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-09-15T10:42:28.494+0000 I CONTROL  [initandlisten]
```

the startup warnings are because the server is not configured with mongodb production notes recommendation for [transparent_hugepage](https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/) and [ulimit](https://docs.mongodb.com/manual/reference/ulimit/). 

need to apply these recommendations to docker image itself or a server which hosted docker container?

**Comment by yosifkit** [comment]
THP is a system wide setting, so it will have to be done on the host.  Most ulimits should be settable on the [`docker run`](https://docs.docker.com/engine/reference/commandline/run/#/set-ulimits-in-container-ulimit).

**Comment by ifeltsweet** [comment]
ulimits cannot be set in a swarm environment (yet), so we'd need to set one in Dockerfile. Fortunately  all but one ulimit (max locked memory -l) are already high enough by default in a docker container.
