### ISSUE TITLE
standard_init_linux.go:175: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by gladmo** [docker-library/mongo#115]
when i run mongo
`sudo docker run --rm mongo`

tty print
standard_init_linux.go:175: exec user process caused "exec format error"

my docker version:
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:31:15 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:31:15 2016
 OS/Arch:      linux/arm

**Comment by yosifkit** [comment]
This is an amd64 image, it will not run on arm.  We have some experimental images available for other architectures, but I don't see MongoDB among them: https://github.com/docker-library/official-images/tree/c52f0d6b854321577f8dd0a0a969e700d1b1fd36#architectures-other-than-amd64.

**Comment by tianon** [comment]
Looks like upstream only supplies binaries for `amd64`, `i386`, and `ppc64el`: http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.2/main/

**Comment by gladmo** [comment]
thinks

**Comment by Bidthedog** [comment]
@yosifkit Just ran into this same error - running on Win 10 64 bit.

Version 18.03.1-ce-win64 (17438)
Channel: stable
83da144

Any options for me to be able to run MongoDB in a Linux container on Windows? Will be deploying to a Linux box, though I'm not sure of the architecture or distro yet.
