### ISSUE TITLE
Permissions issues changing ownership of /data/configdb and /data/db

### ISSUE THREAD

**Issue by lbdremy** [docker-library/mongo#118]
I'm having issues to setup the permissions of the mounted host directories, I tried a couple paths to solve the issue the last is this one using the --user flag.

Here is the situation:

1) I pull the 3.3.15 docker image.
2) I create a container with the following parameters here

```
sudo docker run --name mongodb-test -p 27017:27017 --log-driver syslog -v /etc/mongodb:/data/configdb -v /srv/mongodb:/data/db --user 0 mongo:3.3.15 mongod --conf /data/configdb/mongod.conf
```

With sudo I get the id 0

```
$ sudo id -u
0
```

Considering this it triggers this line https://github.com/docker-library/mongo/blob/master/3.3/docker-entrypoint.sh#L10 but ...

3) I'm getting permissions errors

```
Oct 18 10:39:30 vagrant docker/1b431a750edf[11002]: chown: changing ownership of '/data/configdb/mongod.conf': Operation not permitted
Oct 18 10:39:30 vagrant docker[12810]: chown: changing ownership of '/data/configdb/mongod.conf': Operation not permitted
Oct 18 10:39:30 vagrant docker[12810]: chown: changing ownership of '/data/configdb': Operation not permitted
Oct 18 10:39:30 vagrant docker[12810]: chown: changing ownership of '/data/db': Operation not permitted
Oct 18 10:39:30 vagrant docker/1b431a750edf[11002]: chown: changing ownership of '/data/configdb': Operation not permitted
Oct 18 10:39:30 vagrant docker/1b431a750edf[11002]: chown: changing ownership of '/data/db': Operation not permitted
```

How should I deal with the permissions make the whole thing working properly ? Some images seem to permit to change the uid and gid of the user running the process so everything match with the user on the host. Sorry for that, I'm a bit confused by the whole thing.

**Comment by lbdremy** [comment]
I tried to do things differently this time the host directories /srv/mongodb (permission: 0755) and /etc/mongodb (permission: 0755) are owned by the user mongodb and group mongodb with the uid 2003 and gid 2004 (so nothing to do with the user mongodb in the container)

Then I started the container with this command:

```
sudo docker run --name mongodb-test -p 27017:27017 --log-driver syslog -v /etc/mongodb:/etc/mongodb -v /srv/mongodb:/srv/mongodb --user 2003:2004 mongo:3.3.15 mongod --conf /etc/mongodb/mongod.conf
```

With this command the mongod daemon starts, it is able to read the config in /etc/mongodb/mongod.conf but stopped while initialising with this error:

```
exception in initAndListen: 10309 Unable to create/open lock file: /srv/mongodb/mongod.lock errno:13 Permission denied Is a mongod instance already running?, terminating
```

From there what I have done is to set the permissions a "bit more permissive" of the folder /srv/mongodb to 0777. With this permission the mongod daemon starts without issues and all the files are created but the user/group affected to the shared folders are really unexpected to me.
Here is the actual state:

 In the container:

```
$ sudo docker exec -i mongodb ls -la /srv/mongodb/
total 200
drwxrwxrwx 4 nobody nogroup  4096 Oct 18 14:29 .
drwxr-xr-x 3 root   root     4096 Oct 18 14:21 ..
-rw-r--r-- 1   2003    2004    46 Oct 18 14:21 WiredTiger
-rw-r--r-- 1   2003    2004    21 Oct 18 14:21 WiredTiger.lock
-rw-r--r-- 1   2003    2004   933 Oct 18 14:29 WiredTiger.turtle
-rw-r--r-- 1   2003    2004 45056 Oct 18 14:29 WiredTiger.wt
-rw-r--r-- 1   2003    2004  4096 Oct 18 14:21 WiredTigerLAS.wt
-rw-r--r-- 1   2003    2004 32768 Oct 18 14:29 _mdb_catalog.wt
-rw-r--r-- 1   2003    2004 16384 Oct 18 14:22 collection-0--6754507297440992599.wt
-rw-r--r-- 1   2003    2004 16384 Oct 18 14:29 collection-2--6754507297440992599.wt
drwxr-xr-x 2   2003    2004  4096 Oct 18 14:30 diagnostic.data
-rw-r--r-- 1   2003    2004 16384 Oct 18 14:22 index-1--6754507297440992599.wt
-rw-r--r-- 1   2003    2004 16384 Oct 18 14:29 index-3--6754507297440992599.wt
drwxr-xr-x 2   2003    2004  4096 Oct 18 14:21 journal
-rw-r--r-- 1   2003    2004     2 Oct 18 14:21 mongod.lock
-rw-r--r-- 1   2003    2004 16384 Oct 18 14:23 sizeStorer.wt
-rw-r--r-- 1   2003    2004    95 Oct 18 14:21 storage.bson
```

On the host:

```
sudo ls -la /srv/mongodb/
total 204
drwxrwxrwx 4 mongodb mongodb  4096 Oct 18 14:49 .
drwxr-xr-x 3 root    root     4096 Oct 18 14:21 ..
-rw-r--r-- 1  298611  298612 16384 Oct 18 14:22 collection-0--6754507297440992599.wt
-rw-r--r-- 1  298611  298612 16384 Oct 18 14:29 collection-2--6754507297440992599.wt
drwxr-xr-x 2  298611  298612  4096 Oct 18 14:50 diagnostic.data
-rw-r--r-- 1  298611  298612 16384 Oct 18 14:22 index-1--6754507297440992599.wt
-rw-r--r-- 1  298611  298612 16384 Oct 18 14:29 index-3--6754507297440992599.wt
drwxr-xr-x 2  298611  298612  4096 Oct 18 14:21 journal
-rw-r--r-- 1  298611  298612 32768 Oct 18 14:29 _mdb_catalog.wt
-rw-r--r-- 1  298611  298612     2 Oct 18 14:21 mongod.lock
-rw-r--r-- 1  298611  298612 32768 Oct 18 14:30 sizeStorer.wt
-rw-r--r-- 1  298611  298612    95 Oct 18 14:21 storage.bson
-rw-r--r-- 1  298611  298612    46 Oct 18 14:21 WiredTiger
-rw-r--r-- 1  298611  298612  4096 Oct 18 14:21 WiredTigerLAS.wt
-rw-r--r-- 1  298611  298612    21 Oct 18 14:21 WiredTiger.lock
-rw-r--r-- 1  298611  298612   938 Oct 18 14:49 WiredTiger.turtle
-rw-r--r-- 1  298611  298612 36864 Oct 18 14:49 WiredTiger.wt
```

So on the host:
- /srv/mongodb has the expected user/group
- /srv/mongodb/* - all files have a user/group completely unknown, why the user/group is not mongodb:mongodb 2003:2004 since the container is started with --user 2003:2004 ?

On the container:
- /srv/mongodb has the user/group nobody/nogroup why it is not 2003:2004 ?
- /srv/mongodb/* - all files have the expected user/group

**Comment by yosifkit** [comment]
It looks like you have [user namespace remapping](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-user-namespace-options) turned on.  So user ids from the container are mapped to really high ones on the host (which is also why the chown failed, since it wasn't really the host root user that was trying to chown).

**Comment by lbdremy** [comment]
Thanks @yosifkit, that was it :)

Thanks again  💯 x 👍
