### ISSUE TITLE
Retrieve of gpg key in error

### ISSUE THREAD

**Issue by jmcollin78** [docker-library/mongo#121]
Hi there,
In the Dockerfile we can see this line:
`gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4`

But this line give me this result:
```
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
gpgkeys: key B42F6819007F00F88E364FD4036A9C25BF357DD4 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

So, how is the image build ?
More generaly speaking, how to be sure that the image in Docker Hub is build with this Dockerfile?

Edit:
As a workaroung substituing h1.pool.sks...net by hkp://keyserver.ubuntu.com:80 resolve the issue

**Comment by tianon** [comment]
This is usually indicative of a firewall or network issue, especially if it works fine via port 80 (as you've noted).  Are you in a corporate environment or does your ISP do any port filtering you're aware of?

**Comment by jmcollin78** [comment]
I'm on corporate env but m'y http_proxy and https_proxy are set correctly
inside the container.

**Comment by tianon** [comment]
Right, but "gpg --recv-keys" does not use HTTP or HTTPS by default, so
those will not apply unless you explicitly choose a keyserver which uses
port 80.

**Comment by jmcollin78** [comment]
Ok. Thanks for your explaination and your time. I Guess we can close the
issue.
For my information, what protocole or port is used by pgp recv-keys ?

**Comment by tianon** [comment]
I believe it is port 11371 by default. :+1:
