### ISSUE TITLE
Only chown in docker entrypoint.sh when needed

### ISSUE THREAD

**Issue by christianhuening** [docker-library/mongo#128]
Follow up to #127 .
The docker script should only chown the /data/db folder when it really needs to.

**Comment by tianon** [comment]
How do you propose we detect that `chown` is necessary?

**Comment by christianhuening** [comment]
Hm don't really know. @yosifkit suggested something like that in #127

**Comment by yosifkit** [comment]
How about this:
```bash
# allow the container to be started with `--user`
if [ "$1" = 'mongod' -a "$(id -u)" = '0' ]; then
	# check if chown is necessary
	for dir in /data/{db,configdb}; do
		if gosu mongodb bash -c '[ ! -r '"$dir"' ] || [ ! -w '"$dir"' ] || [ ! -x '"$dir"' ]'; then
			chown -R mongodb "$dir"
		fi
	done
	exec gosu mongodb "$BASH_SOURCE" "$@"
fi
```

**Comment by tianon** [comment]
Is this still necessary/useful?  One workaround would be to simply use `--user mongodb` on the container, which should skip the `chown` line entirely.

**Comment by christianhuening** [comment]
well, tbh: no. We moved from NFS to CEPH, thus the error is gone and is was not only with MongoDB, but basically with any Database in a container. I'll close that issue for now.
