### ISSUE TITLE
Push windowsservercore tags to docker hub with new windowsservercore  base image

### ISSUE THREAD

**Issue by git-jiby-me** [docker-library/mongo#129]
The base image microsoft/windowsservercore used for the windows docker images was updated 12 days ago, is it possible that the tags can be rebuild and pushed to docker hub to use the new base image ?

**Comment by yosifkit** [comment]
Doing a build test on our server and then we'll rebuild and push all the `windowservercore` and `nanoserver` images.

Is there is a way to be notified when the Microsoft team updates either of these images?  Maybe we just do a watch on https://hub.docker.com/r/microsoft/windowsservercore/ for pushes?

**Comment by tianon** [comment]
These rebuilds should be pushed up now!

**Comment by git-jiby-me** [comment]
@yosifkit I am not, but probably docker hub should have some triggers I believe. I just noticed this when the pull for mongodb was trying to pull additional large layers.

But anyways thanks for the rebuild. 👍
