### ISSUE TITLE
Mongo 3.2 contribute in docker official debian system, available memory is enough but mongo use swap?

### ISSUE THREAD

**Issue by xkeyideal** [docker-library/mongo#130]
We contribute mongo 3.2.10 version by using the official dockerfile of debian operate system.
But the docker can't see available memory, and the free memory is less, the mongo will use swap.
How to solve it?

**Comment by xkeyideal** [comment]
![qq 20161229122425](https://cloud.githubusercontent.com/assets/6369390/21536749/c57ec0c4-cdc1-11e6-9632-85fdeac15ac2.png)
See the image

**Comment by tianon** [comment]
I'm not sure I understand fully what issue you're having, but I can't reproduce the container not seeing the same amount of free memory as the host system:
```console
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          32148       20922        1511        2238        9714        8898
Swap:          2047        2008          39

$ docker run -it --rm mongo:3.2.10 free -m
             total       used       free     shared    buffers     cached
Mem:         32148      30851       1297       2239       1407       6747
-/+ buffers/cache:      22695       9453
Swap:         2047       2008         39
```
