### ISSUE TITLE
Connect to mongo docker with authentication from other docker (node)

### ISSUE THREAD

**Issue by inlacou** [docker-library/mongo#133]
Hi,

How can I connect to a docker with authentication from another docker?

I have followed this steps:
`docker run --name some-mongo -d mongo --auth`
`docker exec -it some-mongo mongo admin`
`db.createUser({ user: 'jsmith', pwd: 'some-initial-password', roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] });`

And now the command to connect is said to be
`docker run -it --rm --link some-mongo:mongo mongo mongo -u jsmith -p some-initial-password --authenticationDatabase admin some-mongo/some-db`
but I cant success on merge this command with the one I had launching nodejs and connecting to mongo:
`docker run -it --name start -p 9000:9000 -v `pwd`:/usr/src/app --link some-mongo:mongo node:4.2.4 bash -c "cd /usr/src/app && node server/app.js"`
(it's the command I had working when mongo docker had no authentication)

**Comment by tianon** [comment]
Your Node.js application will need to also use authentication when connecting, and how to configure that is going to depend on the specifics of your Node.js application.
