### ISSUE TITLE
Add XFS support

### ISSUE THREAD

**Issue by admiralobvious** [docker-library/mongo#135]
Hello,

I would like to use this image with storage using XFS but it seems the xfsprogs package is not installed so this is currently not possible. 

Would you accept a pull request adding the xfsprogs package to the various Dockerfiles under this line `		numactl \`?

**Comment by tianon** [comment]
I don't think I understand what's breaking when this image is used on an XFS volume -- can you elaborate on what the failure mode/error is?

**Comment by admiralobvious** [comment]
My bad. I thought the issue came from the container but it's a problem on the host node on Google Container Engine.
