### ISSUE TITLE
Can't download from debian repo's

### ISSUE THREAD

**Issue by anneq** [docker-library/mongo#139]
docker build mongo/3.4, gives me this:

Err http://security.debian.org jessie/updates/main amd64 Packages
  504  Gateway Time-out [IP: 195.20.242.89 80]
Err http://deb.debian.org jessie/main amd64 Packages
  502  Bad Gateway [IP: 128.31.0.62 80]
Err http://deb.debian.org jessie-updates/main amd64 Packages
  504  Gateway Time-out [IP: 128.31.0.62 80]
W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/binary-amd64/Packages  504  Gateway Time-out [IP: 195.20.242.89 80]
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  502  Bad Gateway [IP: 128.31.0.62 80]
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  504  Gateway Time-out [IP: 128.31.0.62 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

Indeed, when I try to access those urls from my browser, the files are not there.

Why the error message is a 504 instead of a 404 I do not understand.

**Comment by tianon** [comment]
My best guess is that you've probably got a proxy in the middle that's
failing in some way.
