### ISSUE TITLE
mongorestore: error: Closed explicitly

### ISSUE THREAD

**Issue by jamesongithub** [docker-library/mongo#140]
version: 3.2.11

`mongorestore --host 127.0.0.1 --db databasename --drop --numParallelCollections 16 --port 33005 path/to/dump`

22:09:07 2017-02-21T22:09:07.189+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.191+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.198+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.202+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.204+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.207+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.211+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.213+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.234+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.238+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.249+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.252+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.266+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.269+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.272+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.274+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.277+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.280+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.284+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.288+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.288+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.291+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.295+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.308+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.312+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.316+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.319+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.322+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.325+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.328+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.331+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.334+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.337+0000	error: Closed explicitly
22:09:07 2017-02-21T22:09:07.340+0000	error: Closed explicitly

---

Seems to run fine against a local mongo instance. I'm just using the default mongo image w/ no config changes.

**Comment by yosifkit** [comment]
What is your `docker run`? And specifically, what is the value of your `-p` on the docker run that starts the mongo container?  The default mongo port is `27017`, so I am not sure where `33005` is coming from.  I assume that you are running the `mongorestore` from the host or is that through a `docker exec`?

**Comment by jamesongithub** [comment]
yeah mongostore is on the host against dockerized mongo
using docker-py to run mongo

```
        mongo_container = docker_client.containers.run(
            image='mongo:{}'.format('3.2.11'),
            detach=True,
            name=db_name,
            network_mode='bridge',
            ports={
                '{}/tcp'.format(mongo.MONGO_DEFAULT_PORT): (localhost, None)
            },
            publish_all_ports=False,
            shm_size='1G'
        )
```
this database we're restoring is ~10gb

pymongo seems to be working fine connecting as a client.

**Comment by erickmgriffin** [comment]
I am seeing this issue too!
I am using:
```
$ mongorestore --version
mongorestore version: r3.4.5
git version: 520b8f3092c48d934f0cd78ab5f40fe594f96863
Go version: go1.7
   os: linux
   arch: amd64
   compiler: gc
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```
And restoring against a 3.2.8 database running in cluster configuration using certificate based TLS encryption.  I have restored 3 separate environments and only had the issue with this particular environment and series of dumps.  The error was seen performing a full restore.  However, I was lucky to get a partial restore for what I needed after that for the colleciton in question.
What additional data do you need?

**Comment by erickmgriffin** [comment]
I will also give you the size of some of this dump
```
-rw-r--r-- 1 egriffin egriffin 1382870812 Jul 25 08:18 bssSubmitted_usage.bson
-rw-r--r-- 1 egriffin egriffin         96 Jul 25 08:15 bssSubmitted_usage.metadata.json
```

**Comment by erickmgriffin** [comment]
I was able to trace our issues back for this problem to a corrupted zip file. Unfortunately when the zip of the dumped directory we are unable to tell if it was a filesystem issue, though strongly suspect this, or the way in which the zip file was handled later.  In any case, when using **sftp** to individually transfer the files for restoration we never hit the above issue, so suspect that error indicates some kinda of bson corruption.  We consider the issue CLOSED.

**Comment by dinfer** [comment]
I got the same error. But I'm not using mongo in docker, it runs directly on host.

When I try to find something in log. I got something may help, but I don't know what does it mean.

```
2017-08-22T11:10:38.904+0800 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 604, after asserts: 896, after backgroundFlushing: 896, after connections: 1000, after dur: 1000, after extra_info: 1304, after globalLock: 1999, after locks: 1999, after network: 1999, after opLatencies: 2200, after opcounters: 2200, after opcountersRepl: 2200, after repl: 2301, after security: 2301, after storageEngine: 2402, after tcmalloc: 2704, after wiredTiger: 3699, at end: 4900 }
```

It seems using too many connection? Could somebody give more information?

**Comment by tianon** [comment]
@jamesongithub were you ever able to figure out this one?  I imagine it's probably similar to the issue you described over in #142, so I imagine my same hunch of `docker-proxy` being an issue is worth trying.

**Comment by jamesongithub** [comment]
hey @tianon i think this issue is different from #142, because the errors on the other were pretty consistent, but i suppose it's possible since the data size was similar

**Comment by tianon** [comment]
Are you still able to reproduce this one, or is it safe for us to close it?

**Comment by jamesongithub** [comment]
you can close. can always reopen if it happens again.

**Comment by tianon** [comment]
Sounds good, thanks! :heart:
