### ISSUE TITLE
mongorestore 10gb database insertion error EOF

### ISSUE THREAD

**Issue by jamesongithub** [docker-library/mongo#142]
version: 3.2.11

`mongorestore --host 127.0.0.1 --db databasename --drop --numParallelCollections 16 --port 33005 path/to/dump`

```
05:27:49 2017-02-28T05:27:49.444+0000	[#################.......]  database1.collection1  1.39GB/1.91GB  (73.0%)
05:27:49 2017-02-28T05:27:49.449+0000	[################........]  database1.collection2  1.22GB/1.82GB  (67.2%)
05:27:49 2017-02-28T05:27:49.449+0000	[#####################...]  database1.collection3  949MB/1.03GB  (90.1%)
05:27:49 2017-02-28T05:27:49.449+0000	Failed: database.collection1: error restoring from backup_2017-02-28T03:57:16/database1/collection1.bson: insertion error: EOF
05:27:49 
05:27:49 Fatal error: local() encountered an error (return code 1) while executing 'mongorestore --host 127.0.0.1 --db database --drop --numParallelCollections 16 --port 33043 backup_2017-02-28T03:57:16/database1'
05:27:49 
05:27:49 Aborting.
```

Similar setup as in https://github.com/docker-library/mongo/issues/140

```
        mongo_container = docker_client.containers.run(
            image='mongo:{}'.format('3.2.11'),
            detach=True,
            name=db_name,
            network_mode='bridge',
            ports={
                '{}/tcp'.format(mongo.MONGO_DEFAULT_PORT): (localhost, None)
            },
            publish_all_ports=False,
            shm_size='1G'
        )
```

Is it just increase shm_size? Is there anything else to tune?

**Comment by jamesongithub** [comment]
tried on aufs and still happening. any idea @tianon ? must be a limit im unware of that it's hitting. definitely related to the size of the workload

**Comment by tianon** [comment]
Hmm, is it running in a VM? (Docker for Windows, Docker for Mac, and Docker Toolbox all start a Linux VM to run your containers in)

Does it happen on other versions of MongoDB as well? (`mongo:3.4`, for example?)

**Comment by jamesongithub** [comment]
Hi @tianon. Yes there is running on EC2 Ubuntu. Does that matter?

Haven't tried 3.4. Could try it out.

**Comment by tianon** [comment]
What does the system's storage/RAM look like?  Can you reproduce with
mongodb not running in Docker?

**Comment by tianon** [comment]
When you hit "localhost" -- is that going through "docker-proxy", or are
you running this in the same container?  Can you try hitting the
container's external IP instead?

For context, when you do something like "-p 80:80", traffic to "localhost"
is routed through a "docker-proxy" process, which is doing "io.Copy" on all
the data, and could cause issues (although EOF still seems odd -- grasping
at straws here to try and help debug what's going on).

**Comment by jamesongithub** [comment]
are you saying the local ip the bridge network assigns the container? i can try that. i'll have to see if it's exposed via https://github.com/docker/docker-py currently it's using the port exposed to localhost. i was not aware of the docker-proxy process.

Btw, this only happens when we are mongorestoring a large database 10gb. less than that it seems to work fine.

**Comment by tianon** [comment]
Sorry @jamesongithub -- yes, I meant the IP that Docker assigns the container on the bridge network.

Did you ever get a chance to try that and verify whether `docker-proxy` was related to your issue?

**Comment by jamesongithub** [comment]
i think the problem was devicemapper and the 10gb base storage size. 

i recall increasing the storage size with `dm.basesize` and i think it might have solved the issue.
i wished the docker docs were more clear on this

haven't seen it since, but we also switched to overlay2 recently.

**Comment by tianon** [comment]
Ahh, that would make a ton of sense -- `devicemapper` is kind of a PITA in my experience (and difficult to configure in a performant way).

Thanks for confirming that this appears to be fixed (I'm going to close)!

Future travelers running into this issue: check your `dm.basesize` if you're using `devicemapper` :+1:
