### ISSUE TITLE
User initialisation and --auth option

### ISSUE THREAD

**Issue by deployable** [docker-library/mongo#147]
The new user initialisation via `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` adds an `--auth` option to `$@`

This causes a problem when a user supplies `--auth`. 
```
Error parsing command line:  Multiple occurrences of option "----auth"
try 'mongod --help' for more information
```

Which is non obvious until you look at the script. 

Maybe `if ! echo "$@" | grep -qw -- '--auth'; then echo "Adding --auth"` ?

**Comment by yosifkit** [comment]
Yeah the mongo error is a little non-obvious. (also, why did they add the extra dashes? `----auth`).

It seems sane to only add it when it is not already in the arguments.

**Comment by tianon** [comment]
How irritating that it can't just realize that we didn't even ask for conflicting things and accept it. :cry:

#152 should help!

**Comment by deployable** [comment]
Thanks! `for arg` is one of those things that's always been there but I've never seen/used in how ever many years scripting.
