### ISSUE TITLE
can't add user the first time run mongo with --auth

### ISSUE THREAD

**Issue by laoqiren** [docker-library/mongo#162]
I use `docker run --name db -v data:/data/db -d mongo:latest --auth` just follow the document, and the I try to add a use to admin database, it's not not authorized. 

So how to add a user?

**Comment by laoqiren** [comment]
I know how to solve it now. thanks

**Comment by yosifkit** [comment]
Did you see the new variables?

```console
docker run  --name some-mongo -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=password mongo
```

**Comment by laoqiren** [comment]
I know we should add a user not use '--auth',   I think the document is not clear enough.   run  a container for creating user then the user option will be at /home/mymongodb/db( the file in real host computer), then run the container with '--auth', I think this can be clear more. that's how I solve this problem.

**Comment by yosifkit** [comment]
It seems like this was solved; closing
