### ISSUE TITLE
Regression: Cannot set --logpath with > 3.4.1

### ISSUE THREAD

**Issue by bedonath** [docker-library/mongo#168]
The following works fine:

`docker run mongo:3.4.1 mongod --logpath /data/db/mongodb.log --logRotate rename`

Attempting to use 3.4.2 or 3.4.3 this does not work anymore:

`docker run mongo:3.4.3 mongod --logpath /data/db/mongodb.log --logRotate rename`

fails with:

> Error parsing command line:  Multiple occurrences of option "----logpath"
try 'mongod --help' for more information

**Comment by yosifkit** [comment]
We added a fix in https://github.com/docker-library/mongo/pull/167 to account for this; can you pull and see if the latest image works for you?

**Comment by bedonath** [comment]
Thank you for the quick response! This change fixed the problem for me.

**Comment by yosifkit** [comment]
Awesome!
