### ISSUE TITLE
Can not access mongo DB after run a container

### ISSUE THREAD

**Issue by xudan2189** [docker-library/mongo#177]
I run a Docker container with the cmd:
```console
$ docker run --name my_mongo -d mongo:3.5
```
It can successfully create a container.
```console
$ docker ps -a
CONTAINER ID        IMAGE           COMMAND                  CREATED               STATUS                  PORTS               NAMES
ede5e98eb958        mongo:3.5      "docker-entrypoint.sh"   14 minutes ago   Up 14 minutes      27017/tcp           my_mongo
```
When I try to connect to this DB, it goes wrong.
```console
root@ubuntu:~# mongo
MongoDB shell version: 2.4.9
connecting to: test
Wed May 10 04:02:56.530 Error: couldn't connect to server 127.0.0.1:27017 at src/mongo/shell/mongo.js:145
exception: connect failed
```

When I enter this container, use cmd "mongo" to connect the mongo DB it will stuck...
```console
root@ubuntu:~#  sudo docker exec -it my_mongo bash
root@411e98f22781:/# mongo                                                                                                                                                            
MongoDB shell version v3.5.6
connecting to: mongodb://127.0.0.1:27017
```

What's worse, this container can not been stopped or removed.

my docker version
```console
root@ubuntu:~# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

my OS:
```console
root@ubuntu:~# uname -a
Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yosifkit** [comment]
Using the `mongo` client from the host will require you to specify the IP address of the container to connect to.

```console
$ myMongo="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my_mongo)"
$ mongo "$myMongo"
```

Or you need to run the MongoDB container and expose its port as a port on your host:

```console
$ # this will allow you access via localhost on your host, but will prevent external connections
$ # but does not prevent access from other containers on your host
$ docker run --name my_mongo -d -p 127.0.0.1:27017:27017 mongo:3.5
$ mongo
> db
test

$ # this exposes it to anyone that can access port 27017 on your host from your network
$ # can be a security concern if host IP is accessible publicly
$ docker run --name my_mongo -d -p 27017:27017 mongo:3.5
```

I have never seen the MongoDB container as unstoppable or non-removable.  Maybe these commands will help out:
- stopping the container: `docker stop my_mongo`
  - sends `SIGTERM`, waits 10 seconds and then `SIGKILL` if it has not stopped
- stop the container without any delay: `docker kill -sKILL my_mongo`
  - same as a `kill -9`, process has no chance to clean up
- removing the stopped container: `docker rm my_mongo`
- removing the container (even if it is running): `docker rm -f my_mongo`
- removing the container and its volume: `docker rm -fv my_mongo`

**Comment by bakmei** [comment]
I just come up with a solution to kill the invincible:

docker kill $(docker ps -a -q); docker rmi --force <image id#1> [more image id#2]; docker image ls;

************************************************************************************************
CAUTION: **This should not be run in a Production environment.**
The above command will remove the mongo image as the command "rmi" will delete the Mongo image.
Please be noted that you should only include the mongo image.  For my case, the images are  mongo and mongo-express, use the image id accordingly.  The command "docker image ls" will list all the docker image Id. 
************************************************************************************************

You may need to run the command a few times until you don't see the images.  Then you just need to rebuild the Mongo image.

Next, you have to restart the docker process to ensure that the mongo stuff not left in the memory.
