### ISSUE TITLE
Use environment configuration

### ISSUE THREAD

**Issue by imaia** [docker-library/mongo#188]
Docker images as postgres, allow you to change some common behavior throught environment variables (POSTGRES_USER, POSTGRES_PASSWORD, etc). Why not to mimic this very convenient behavior? It would be nice to have a easy way to setup authentication for the mongo container, per example.

**Comment by tianon** [comment]
If you set `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` during the initial container startup, the entrypoint script (https://github.com/docker-library/mongo/blob/d1c2ba0001233372a1ab8515ee5e1e968e0d64f9/3.4/docker-entrypoint.sh) should configure a root user for you. :+1:

**Comment by imaia** [comment]
Thanks @tianon Then this issue should be related to having those options documented. I'll open another.
