### ISSUE TITLE
Please, document environment variables

### ISSUE THREAD

**Issue by imaia** [docker-library/mongo#189]
Please, document the variables below:

* MONGO_INITDB_DATABASE
* MONGO_INITDB_ROOT_USERNAME
* MONGO_INITDB_ROOT_PASSWORD

**Comment by aaomidi** [comment]
Why is this not documented?

As devops we keep telling others to "RTFM", at this point it's "RTFS".

**Comment by tianon** [comment]
It's not documented yet both because we haven't gotten to writing good docs
for it yet, and because it doesn't work as well as we'd like it to yet (so
we still consider it somewhat experimental).  For example, it has very
annoying edge behavior when folks attempt to use it together with a
configuration file.

**Comment by imaia** [comment]
@tianon how can we help?

**Comment by yosifkit** [comment]
@imaia thanks for any help!  Any documentation would go in the content.md file over [here](https://github.com/docker-library/docs/blob/master/mongo/content.md).

I think the best option we thought to improve the reliability of these variables was to add a small yaml parser to the image to parse the MongoDB config file and use it with our cli flag parsing to ensure we properly detect ssl usage and other conflicting config.  I don't recall what @tianon had found when searching for a small yaml parser. We just haven't been able to get back to give the MongoDB image more attention.

[Here](https://github.com/docker-library/mongo/blob/61aabfb537a1fbcae44f02ab515df54395b68400/3.4/docker-entrypoint.sh#L161-L178) is the section that we have to ensure certain config flags are set for `mongod`.  It all is a little hacky, and I'd love a better way to do it.  The biggest annoyance is `mongod` handling of config; it just fails if config options exist twice (two flags or one flag and one in the config file); it can't handle `allowSSL` if there is no ssl config, or `disabled` sslMode when there are ssl certs.

Have any ideas where you would like to help?

**Comment by geekscrapy** [comment]
Has the actual OP issue been resolved yet? Still can't find doco for setting the auth in environment variables

**Comment by tianon** [comment]
Parsing the config file was added in https://github.com/docker-library/mongo/pull/225, which was the main driver for considering this functionality to still be experimental, so we're definitely ready to document this.

It looks like there's been a stab taken at doing so in https://github.com/docker-library/docs/pull/1127, but we haven't had a chance to review it in depth yet.

**Comment by tianon** [comment]
Closing in favor of https://github.com/docker-library/docs/pull/1127 (since this is really a documentation issue, not an image issue). :+1:
