### ISSUE TITLE
docker-entrypoint.sh Permission Denied

### ISSUE THREAD

**Issue by manuelkasiske** [docker-library/mongo#193]
Docker version 17.05.0-ce, build 89658be
docker-compose version 1.14.0, build c7bdf9e

I got permission denied if i am using mongo with docker-compose.

mongo1_1           | error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied

But it is the same if i try to run the single container with that docker-entrypoint.sh script. Is there someting what i am doing wrong?

$ docker run -tiP mongo bash
root@a277ea29a1a4:/# docker-entrypoint.sh mongodb
+ '[' m = - ']'
+ originalArgOne=mongodb
+ [[ mongodb == mongo* ]]
++ id -u
+ '[' 0 = 0 ']'
+ '[' mongodb = mongod ']'
+ chown --dereference mongodb /proc/511/fd/1 /proc/511/fd/2
+ exec gosu mongodb /usr/local/bin/docker-entrypoint.sh mongodb
error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied

root@a277ea29a1a4:/# ls -ltr /usr/local/bin/docker-entrypoint.sh 
-rwxrwxrwx 1 root root 7688 Jul 28 16:01 /usr/local/bin/docker-entrypoint.sh

**Comment by manuelkasiske** [comment]
Found the error. Image has not been build correctly.

**Comment by agarwal13** [comment]
Am still seeing this issue, when using the mongo:3.6.6 image in my docker-compose file.

docker-compose file snippet:
dbservice:
    image: "mongo:3.6.6"
    ports:
      - "5009:27017"
    volumes:
      - /home/data/db:/data/db
      - /home/data/configdb:/data/configdb
    restart: on-failure

error:
error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied

mongo service is crashing continuously with the above error. Can you please help me identifying the appropriate image for the mongo version 3.6.*

**Comment by yosifkit** [comment]
@agarwal13 , did you build the `mongo:3.6.6` image yourself or did you `docker pull` it?

Could be similar to https://github.com/docker-library/percona/issues/7 or https://github.com/docker-library/postgres/issues/386?

**Comment by allistoncarlos** [comment]
Any updates? I'm having the same issue, using docker pull mongo:4.1.3 image...

**Comment by tianon** [comment]
Could be AppArmor or SELinux blocking the script.

**Comment by agarwal13** [comment]
@yosifkit Yes, am building with the mongo:3.6.6. This seems to be running fine on the linux system as it is. But, when tried running inside a lxd container, it is failing with the same error. i.e., 
error: exec: "/usr/local/bin/docker-entrypoint.sh": stat /usr/local/bin/docker-entrypoint.sh: permission denied

Any idea why is this happening? I tried security.privileged and security.nesting to true and still the issue is persistent
