### ISSUE TITLE
mongo:3.2-windowsservercore built off old base image

### ISSUE THREAD

**Issue by drnybble** [docker-library/mongo#194]
mongo:3.2-windowsservercore is built off a Microsoft base image from April.
It should be pulling the latest base image when it is built using docker pull or the --pull option to docker build.

PS C:\Users\mcdowels> docker pull mongo:3.2-windowsservercore
3.2-windowsservercore: Pulling from library/mongo
Digest: sha256:fe56a401238349a669735ae199e423a4bd8c85ee5e46c6f38eee289f8c13583d
Status: Image is up to date for mongo:3.2-windowsservercore

PS C:\Users\mcdowels> docker history mongo:3.2-windowsservercore
IMAGE               CREATED             CREATED BY                                      SIZE
a7f186224c8e        2 weeks ago         powershell -Command $ErrorActionPreference...   41kB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   41kB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   41kB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   161MB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   41kB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   41kB
<missing>           2 weeks ago         powershell -Command $ErrorActionPreference...   41kB
<missing>           3 months ago        powershell -Command $ErrorActionPreference...   41kB
<missing>           3 months ago        Install update 10.0.14393.1066                  2.47GB
<missing>           8 months ago        Apply image 10.0.14393.0                        7.68GB

**Comment by tianon** [comment]
This should be updated now. :+1:

(A few days ago, but just now getting back to the issue. :innocent:)
