### ISSUE TITLE
Failed when build

### ISSUE THREAD

**Issue by agus3winarno** [docker-library/mongo#195]
failed when build from https://github.com/docker-library/mongo/blob/master/3.4/Dockerfile on mac osx 10.12.5.

found this error : docker-entrypoint.sh: no such file or directory.

<img width="866" alt="screen shot 2017-08-11 at 12 50 10 am" src="https://user-images.githubusercontent.com/1158222/29184136-66a20344-7e2f-11e7-95c5-847b77abb3d1.png">

**Comment by yosifkit** [comment]
If you are building the image rather then just doing a `docker pull`, you need to clone the whole context to have all required files (like `docker-entrypoint.sh`) with correct permissions on the files, especially executability.
