### ISSUE TITLE
WiredTiger Storage Engine Default?

### ISSUE THREAD

**Issue by knpwrs** [docker-library/mongo#197]
[The MongoDB docs](https://docs.mongodb.com/manual/core/wiredtiger/) state that the default storage engine for 3.2 and higher is WiredTiger. The `README` for this repo makes a point of explicitly pointing out the `--storageEngine` flag to use WiredTiger. I just wanted to confirm -- is WiredTiger the default storage engine for this image (obviously, starting with version 3.2)? Would a documentation update be appropriate?

**Comment by yosifkit** [comment]
Sounds reasonable.  Those lines haven't been updated in about 2 years. Although the wiredtiger is still appropriate for 3.0, it seems sane to just switch to some other example.  The place to update would be [content.md](https://github.com/docker-library/docs/blob/master/mongo/content.md).
