### ISSUE TITLE
mongodump (3.4.7) not working anymore: permission denied

### ISSUE THREAD

**Issue by luca-moser** [docker-library/mongo#199]
Using image version 3.4.7, mongodump commands don't work anymore and error out with a `permission denied`. It did work under image version 3.3.15. Using the `--privilege` flag doesn't fix the issue.

Command: `docker run --rm --net=xxx -v /mnt/backup:/opt -w /opt mongo:3.4.7 mongodump -h storage:27017 -u xxx -p yyy --gzip --archive=dump.gz`

**Comment by tianon** [comment]
Sorry for the delay! (must have missed this one :disappointed:)

Can you provide more information about your host system?  Does your host include anything like SELinux?  Have you enabled user namespaces or something that would similarly affect the file permissions?

Without more details (ideally a very simple reproducing example which doesn't involve your private credentials or custom setup), we cannot help debug effectively. :wink:

**Comment by tianon** [comment]
Closing stale issue -- if you can provide more detail for how we can reproduce this reliably so that we can attempt to fix it, please do so and we'll be happy to reopen. :heart:

**Comment by nodejsdeveloperskh** [comment]
Hi, I got the same error with the `bitnami/mongodb:4.4-debian-10`, But when I use the `mongo:4` the problem magically disappeared and I did the `mongodump`.

**Quick Tip**: change the base image
**Long Tip**: IDK, I hope someone, later on, adds more details about this problem and tag me
