### ISSUE TITLE
SELinux is preventing chown from setattr access on the fifo_file

### ISSUE THREAD

**Issue by eburgueno** [docker-library/mongo#201]
I am having issues running the `mongo:latest` container (`9b39de1d79a53`) on CentOS 7. Here's how to reproduce

```
# cd app; cat docker-compose.yml 
version: '2'
services:
  db:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --logpath=/dev/null'
    volumes:
      - ./data/mongo:/data/db:z

# docker logs app_db_1
chown: changing ownership of '/proc/1/fd/1': Permission denied
chown: changing ownership of '/proc/1/fd/2': Permission denied

# grep denied /var/log/audit/audit.log
type=AVC msg=audit(1504567301.081:52965): avc:  denied  { setattr } for  pid=2007 comm="chown" name="" dev="pipefs" ino=923848 scontext=system_u:system_r:svirt_lxc_net_t:s0:c98,c889 tcontext=system_u:system_r:container_runtime_t:s0 tclass=fifo_file
type=AVC msg=audit(1504567301.081:52966): avc:  denied  { setattr } for  pid=2007 comm="chown" name="" dev="pipefs" ino=923849 scontext=system_u:system_r:svirt_lxc_net_t:s0:c98,c889 tcontext=system_u:system_r:container_runtime_t:s0 tclass=fifo_file
```

Other than creating and loading a custom policy (which I strongly dislike doing), is there a better way to solve this?

**Comment by yosifkit** [comment]
Those should be ignore-able since we specifically do an ["or true"](https://github.com/docker-library/mongo/blob/a625cc00167b598f6902de0824519196410074f4/3.4/docker-entrypoint.sh#L19) on those chowns (from https://github.com/docker-library/mongo/issues/149 and https://github.com/docker-library/mongo/pull/151).  It should only apply to the intdb.d setup (which it appears you are not using).

**Comment by eburgueno** [comment]
@yosifkit I'm afraid the application cannot connect to the mongo instance if I ignore it, so something might be missing.

#151 makes sense to me, so this could be something else and the SELinux denial just a coincidence. If I use `mongo:3.4.0` instead of `mongo:latest` (which should be `3.4.7`), the container works; but the `entrypoint.sh` is different in that version.

I will try and capture more verbose logs to confirm the problem and report back.

**Comment by tianon** [comment]
@eburgueno any luck capturing more verbose logs to help debug/confirm the issue?

**Comment by tianon** [comment]
Closing stale issue -- if you can provide more detail for how we can reproduce this reliably so that we can attempt to fix it, please do so and we'll be happy to reopen. :heart:
