### ISSUE TITLE
Cannot find the config file

### ISSUE THREAD

**Issue by JaxLgj** [docker-library/mongo#206]
When I run the command
`docker run --rm --name mongoc1 -v mongoconfig1:C:\data\configdb\ -d mongo -f "C:\data\configdb\mongo.cfg"`

get error "docker: Error response from daemon: container 1e9ca3e5f31970d2f0ab18cc7422831813e9ccc580d196a14e372bff3e9e30bc encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified."

![default](https://user-images.githubusercontent.com/24977009/31379514-07418e2e-ade1-11e7-95de-28fd7e8588cd.png)

**Comment by tianon** [comment]
Indeed, that's by design -- on Windows, we cannot easily support the same sort of entrypoint behavior we have in the Linux variants, so you'll have to include `mongod` in your command:
```console
C:> docker run --rm --name mongoc1 -v mongoconfig1:C:\data\configdb\ -d mongo mongod -f "C:\data\configdb\mongo.cfg"
```

**Comment by JaxLgj** [comment]
Ohhh, thanks.

**Comment by JaxLgj** [comment]
@tianon  Ohh, thank you for your help.
