### ISSUE TITLE
mongodb instance not started, when try to execute shell script through dockerfile.

### ISSUE THREAD

**Issue by sathisz** [docker-library/mongo#207]
I try to do some default operations like create a user and database before the start of the container. So I explicitly call a new script file in Dockerfile through "CMD". But while the script is executing mongod instance is not started. 

`CMD ["/run.sh"]`

Where run.sh is my script which creates user and database. But when I didn't specify any "CMD", the mongod instance started with "noauth" mode as usual.

**Comment by yosifkit** [comment]
If you are just adding a user/password, then you can use the environment variables `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` or you can drop your script in `/docker-entrypoint-initdb.d/`.  If you go the script route, you'll need to add the `--auth` flag yourself.

```console
$ docker run -d -v /path/to/script/:/docker-entrypoint-initdb.d/ mongo:3.4 --auth
$ # or
$ docker run -d -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=secret mongo:3.4
$ # though you'll probably want a "-v /path/to/db/files/:/data/db/" to keep the db peristent
```

Here is the part of the entrypoint that handles these two things:

https://github.com/docker-library/mongo/blob/7b2fe2cd853161fdb6d28d318e9e7968e51d0ee3/3.4/docker-entrypoint.sh#L207-L234
