### ISSUE TITLE
Support for arm32v7

### ISSUE THREAD

**Issue by Serkan-devel** [docker-library/mongo#209]
Is there any? I want to run a local pump.io instace on a raspberry pi.

**Comment by tianon** [comment]
See the discussion over on https://github.com/docker-library/mongo/issues/196.  I doubt upstream is going to officially support arm32 since MongoDB on 32bit platforms is limited to 4GB IIRC (and they don't actively support i386 anymore, for example).

**Comment by tianon** [comment]
Closing as a duplicate of #196 (so we can keep the "multi-architecture" discussion in one place).
