### ISSUE TITLE
3.6 Tag too Early

### ISSUE THREAD

**Issue by rawkode** [docker-library/mongo#217]
`3.6` tag shouldn't exist until out of RC. I assumed it was GA and have now upgraded a bunch of containers and realised that `db.version()` returns rc7.

:disappointed:

**Comment by yosifkit** [comment]
You are correct. :disappointed: We usually don't tag the images without `-rc` until they are a release, but it seems we messed up the mongo repo in that.  We don't have an easy way to delete tags on the Docker Hub, so for now I would like to keep updating it with new RC builds.

For next time you can check the Docker Hub description to see what tags are the same image.

> -	[`3.6.0-rc7-jessie`, `3.6.0-jessie`, `3.6-jessie`, `3.6-rc-jessie`, `rc-jessie` (*3.6-rc/Dockerfile*)](https://github.com/docker-library/mongo/blob/060a2889ba425fd498839ddeb562140e1899f216/3.6-rc/Dockerfile)

> -	`3.6.0-rc7`, `3.6.0`, `3.6`, `3.6-rc`, `rc`:
>	-	[`3.6.0-rc7-jessie` (*3.6-rc/Dockerfile*)](https://github.com/docker-library/mongo/blob/060a2889ba425fd498839ddeb562140e1899f216/3.6-rc/Dockerfile)
>	-	[`3.6.0-rc7-windowsservercore-ltsc2016` (*3.6-rc/windows/windowsservercore-ltsc2016/Dockerfile*)](https://github.com/docker-library/mongo/blob/06c92111d8f3ea13dff1401dd41077a314fcb95d/3.6-rc/windows/windowsservercore-ltsc2016/Dockerfile)
>	-	[`3.6.0-rc7-windowsservercore-1709` (*3.6-rc/windows/windowsservercore-1709/Dockerfile*)](https://github.com/docker-library/mongo/blob/06c92111d8f3ea13dff1401dd41077a314fcb95d/3.6-rc/windows/windowsservercore-1709/Dockerfile)

**Comment by rawkode** [comment]
I used the API, not Hub. Things seem stable for now, so fingers crossed :joy:

**Comment by tianon** [comment]
Pushed https://github.com/docker-library/mongo/commit/6cc8a96aaf38dec1525ecbb026488d8e817f6ef2 to fix the over-aggressive generate script for the next round of RCs so we don't create this confusion again.  I'm also going to go create the https://github.com/docker-library/official-images PR which will get the image up to 3.6.0 GA.

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/3784
