### ISSUE TITLE
rs.initiate() not preserved with data volume

### ISSUE THREAD

**Issue by pward123** [docker-library/mongo#22]
Here's how I'm running the container:
```
  /usr/bin/docker run \
    -d \
    --name=mongo \
    --volumes-from=mongo_data \
    mongo:2.6.7 \
    mongod --smallfiles --replSet "rs0" --noauth
```
Once it's up, I run "rs.initiate()" against the database.  Everything works great.  I can docker stop/start all day long and everything is good.

If I "docker rm mongo" and run the command above again, I get the following error in the docker logs for mongo:

```
[rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
[rsStart] replSet info you may need to run replSetInitiate -- rs.initiate() in the shell -- if that is not already done
[rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
[rsStart] replSet can't get local.system.replset config from self or any seed (EMPTYCONFIG)
```

I'm assuming that rs.initiate() is modifying some file on disk outside of the /data/db tree, but I haven't been able to figure out where that might be yet.

**Comment by pward123** [comment]
I forgot to mention that if I run rs.initiate() again against the new container, everything starts working again.

**Comment by tianon** [comment]
Can you run "docker diff" on the container to see if it's modified any
files in the R/W layer?

**Comment by md5** [comment]
You can check whether anything has changed before doing your `docker rm mongo` with the `docker diff mongo` command. That will show you any changed files against the base `mongo` image that happened outside of volumes.

I suspect your replicaset issue is actually related to the transient hostname being used by the container. You could try using the `-h` flag to `docker run`.

**Comment by md5** [comment]
jinx @tianon

**Comment by pward123** [comment]
Ahh, didn't know about the docker diff command. That's pretty handy.
```
A /data
A /data/db
C /root
A /root/.bash_history
A /root/.dbshell
A /root/.mongorc.js
C /tmp
A /tmp/mongodb-27017.sock
C /var
A /var/db
```

I tried -h but that doesn't seem to help either. If you like I can try to create a github repo duplicating it with vagrant

**Comment by md5** [comment]
Does your mongo_data container actually have a volume at /data/db?

**Comment by pward123** [comment]
Doh, you're right on. I must've goofed when creating the data container. I recreated it making sure I had the correct -v param. That fixed the problem.

Thanks for the assist
