### ISSUE TITLE
3.6.0 is actually showing 3.6.0-rc8

### ISSUE THREAD

**Issue by trentmswanson** [docker-library/mongo#220]
The mongo image currently tagged with `3.6.0` is actually running `RC8`

![mongo-docker-versions](https://user-images.githubusercontent.com/1594373/33664362-5822a34e-da61-11e7-9e65-4e9db1a42113.png)

There's likely another issue with the tagging and upload script that needs to be created, because the release candidates should never have been tagged with the `3.6.0` and `3.6` tags.

**Comment by robgrimball** [comment]
Confirmed after pulling down the 3.6.0 image myself.

**Comment by animedbz16** [comment]
Seeing this same issue. 

If you look at the commit hash it also confirms that the image is the rc8 version and not the publicly released 3.6 version

![image](https://user-images.githubusercontent.com/2822632/33680070-7ebd9540-da8e-11e7-84b5-0769c941613b.png)

![image](https://user-images.githubusercontent.com/2822632/33680061-7411051e-da8e-11e7-90a4-1044ec61f11e.png)

**Comment by yosifkit** [comment]
duplicate #217.
