### ISSUE TITLE
Basic configuration and persistence

### ISSUE THREAD

**Issue by KevinBurton** [docker-library/mongo#235]
I understand that on OSX and Windows I cannot use -v. I guess I am not clear how the database "persists" when each new container. Is it possible to detail the full path for where the database will be for OSX?
How do I pass configuration information if I cannot use -v? Where is the configuration information maintained/persisted for each new container. The only thing in the documentation is to check the official documentation on the configuration options. Ideas?

**Comment by yosifkit** [comment]
On OSX and Windows you can use a named volume so that docker will persist the data to the VM's hard disk: `-v my-mongo-data:/data/db/`.  You can then manage the volume life-cycle with `docker volume` subcommands.

As for config, you can just pass them in as the command to the image and they will get passed along to `mongod` (https://docs.mongodb.com/manual/reference/program/mongod/):
```console
$ docker run -d -v mongo-data:/data/db/ mongo --replSet my-replica 
```

**Comment by KevinBurton** [comment]
Is there a better way? What if there are a lot of configuration settings? A configuration file is not supported?

**Comment by KevinBurton** [comment]
I am not sure how to interpret this warning:

> WARNING (Windows & OS X): The default Docker setup on Windows and OS X uses a VirtualBox VM to host the Docker daemon. Unfortunately, the mechanism VirtualBox uses to share folders between the host system and the Docker container is not compatible with the memory mapped files used by MongoDB (see vbox bug, docs.mongodb.org and related jira.mongodb.org bug). This means that it is not possible to run a MongoDB container with the data directory mapped to the host.

https://hub.docker.com/_/mongo/

**Comment by yosifkit** [comment]
The warning is that on OSX/Windows you are not running mongod natively on the host, but in a VM and any folders shared between VM and Host do not support the filesystem access that mongod requires. In short, it will fail to run if you do something like the following:

```console
$ docker run -d -v /path/on/osx/:/data/db/ mongo
```

You can add a config file as a flag (it can be put anywhere in the container that the `mongo` user can access):
```console
$ docker run -d -v mongo-data:/data/db/ -v /path/to/config/:/etc/mongo/ mongo --config /etc/mongo/mongo.conf
```
(this one could use better docs :disappointed:)

**Comment by wglambert** [comment]
Question seems sufficiently answered and hasn't had any responses in some months so I'm going to prune.

The docs now have a subsection: ***WARNING (Windows & OS X):***
> The default Docker setup on Windows and OS X uses a VirtualBox VM to host the Docker daemon. Unfortunately, the mechanism VirtualBox uses to share folders between the host system and the Docker container is not compatible with the memory mapped files used by MongoDB . . .

https://github.com/docker-library/docs/tree/master/mongo#where-to-store-data

**Comment by wglambert** [comment]
A named volume is independent of the host filesystem
To try for a concise explanation: https://stackoverflow.com/a/34357861
For nuance on volumes vs bind mounts https://github.com/docker-library/mariadb/issues/120#issuecomment-382456566

https://docs.mongodb.com/v3.4/reference/program/mongod/#cmdoption-configsvr
`--config` is to specify the file for runtime options
