### ISSUE TITLE
Mongo 3.6.2 not build in hub.docker.com yet ?

### ISSUE THREAD

**Issue by Meabed** [docker-library/mongo#236]
Mongo 3.6.2 not build in hub.docker.com yet

**Comment by tianon** [comment]
From https://github.com/docker-library/mongo/blob/master/README.md:

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/mongo" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/mongo), especially [PRs with the "library/mongo" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fmongo). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

I'll make an update PR to official-images shortly.
