### ISSUE TITLE
failed to connect to server

### ISSUE THREAD

**Issue by SLedunois** [docker-library/mongo#238]
Hello,

I got an issue with my CI test workflow. I try to launch a mongodb docker image to run my db tests. Here is my travis ci configuration : 
```
sudo: required

language: node_js
node_js:
  - stable

services:
  - docker

before_install:
  - docker pull mongo
  - docker run --name mongo -d mongo -p 0.0.0.0:27017:27017

install:
- npm install

script:
- npm run lint
- npm test
- npm run build

notifications:
    slack: travis-projet:qqijRoPDFiJL99vloreIeAUF
```

Actually, I launch docker by running a `docker run --name mongo -d mongo -p 0.0.0.0:27017:27017`.

The problem : When I try to connect Nodejs to Mongo with `mongodb://localhost:27017`, i'm issuing this error : `MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]`.

I'm new on docker and I try to industrialize it. Can you help me? I don't find anything on this issue that corrects my bug :/

Thank you,

SLedunois

**Comment by yosifkit** [comment]
For travelers from the future, it should be this change (the `-p` argument needs to be to docker run, not to the mongo container):
```diff
-  - docker run --name mongo -d mongo -p 0.0.0.0:27017:27017
+  - docker run --name mongo -d -p 0.0.0.0:27017:27017 mongo
```
