### ISSUE TITLE
if SSL if supported why is not documented?

### ISSUE THREAD

**Issue by alfredocambera** [docker-library/mongo#244]
I've been trying to make the mongo container work with SSL. So far all I have read a log of notes on github but no clear explanation on what is supported and how to use it,

It seems like a lot of people has invested time on working on this, so I'd suggest to improve documentation.

I'd document it if anybody provides some info,

**Comment by tianon** [comment]
It should be what's described by https://docs.mongodb.com/manual/tutorial/configure-ssl/ -- you shouldn't have to do anything "container specific" besides somehow providing those certificate files to the container (as one might expect) and appropriatelly telling `mongod` how to find them (either via commandline flags or via a configuration file).

**Comment by yosifkit** [comment]
Docs on using a config file or flags added in https://github.com/docker-library/docs/pull/1127.
