### ISSUE TITLE
How to Initialize container with fixture data?

### ISSUE THREAD

**Issue by k0pernikus** [docker-library/mongo#247]
I have written a [so question](https://stackoverflow.com/questions/48864386/how-to-initialize-mongo-container-via-a-query-on-build/48868244#48868244) about this, yet I ponder it fits more here.

As a developer setting up a development stack using docker-compose, I like to have the option to setup a mongo db with fixture data, similar as to the [mariadb image works](https://hub.docker.com/_/mariadb/):

> ## Initializing a fresh instance
> When a container is started for the
> first time, a new database with the specified name will be created and
> initialized with the provided configuration variables. Furthermore, it
> will execute files with extensions `.sh`, `.sql` and `.sql.gz` that are
> found in `/docker-entrypoint-initdb.d`. Files will be executed in
> alphabetical order. You can easily populate your `mariadb` services by
> mounting a SQL dump into that directory and provide custom images with
> contributed data. SQL files will be imported by default to the
> database specified by the `MYSQL_DATABASE` variable.

It seems that currently I have to either query the database manually after it was created, meaning I have to either point out some manual steps in the `Readme.md`. (Currently, I require a developer to have a mongo-client installed, in order to fire some queries, which will be copy-pasted.)

I want to automate that process so that docker-compose or a custom dockerfile takes care about the initalization.

Is there a current best practice on how to achieve that? Otherwise, please kindly treat this as a feature request :)

**Comment by yosifkit** [comment]
The same functionality now exists in the MongoDb image for Bash and JavaScript files: 

https://github.com/docker-library/mongo/blob/5ad7b10217359104c1870d2d79bcb6498bf76b70/3.6/docker-entrypoint.sh#L306-L313

We are just working on documenting it: https://github.com/docker-library/docs/pull/1127. It was previously considered unstable, so we hadn't documented it.  Hopefully we can get some docs up soon.

Related to https://github.com/docker-library/mongo/issues/189.
