### ISSUE TITLE
how to configure TLS/SSL for mongod

### ISSUE THREAD

**Issue by zhenwan** [docker-library/mongo#250]
Is there a documentation on configuring TLS/SSL for mongod?

I found this doc
https://docs.mongodb.com/manual/tutorial/configure-ssl/

but I could not find the instruction for Mongo docker image

**Comment by yosifkit** [comment]
It will be the same as the doc from MongoDB goes through:

 - generate the cert and create the pem file
   - just follow their documentation
 - then run monogd with the cert

```console
$ # their example
$ mongod --sslMode requireSSL --sslPEMKeyFile /etc/ssl/mongodb.pem <additional options>

$ # translate that to use the the docker image:
$ # mount in the pem (or use something like docker secrets to add it to the container)
$ # add mongd flags after the image name and they will be passed along (or mount in a config file and tell mongo where it is)
$ docker run -d -v /path/to/pem/:/etc/ssl/ mongo:3.6 --sslMode requireSSL --sslPEMKeyFile /etc/ssl/mongodb.pem <additional options>
```

**Comment by zhenwan** [comment]
This works, thanks

**Comment by alecgerona** [comment]
Doesn't seem to work for 4.4. Just running run and it periodically logs `SSLHandshakeFailed` as an error and refuse the connection. I'm not even sure what's trying to connect to it.
