### ISSUE TITLE
Logo missing

### ISSUE THREAD

**Issue by spacecat** [docker-library/mongo#256]
MongoDB logo missing here: 

[https://store.docker.com/images/mongo](https://store.docker.com/images/mongo)

**Comment by tianon** [comment]
Yeah, this was unfortunately intentional, see https://github.com/docker-library/docs/commit/d592f22ae9748a2464f32fc3b0a089f9c3afcd37#diff-1ed75a5d1e2c0bb05f410077765af687 (this was at the request of upstream -- MongoDB Inc).
