### ISSUE TITLE
debian stretch+

### ISSUE THREAD

**Issue by dieeasy** [docker-library/mongo#258]
Was wondering, are there any plans on updating the ondelying Debian OS to stretch and eventually buster?

It would be quite important from a security standpoint, in my opinion.

**Comment by yosifkit** [comment]
From the conversation in https://github.com/docker-library/mongo/issues/196, it will most likely be migrating to Ubuntu based images so that we can support more architectures.  So, yes we do want to have a more up-to-date OS distribution.

**Comment by haodong** [comment]
@yosifkit Why? Why no Debian support?

**Comment by yosifkit** [comment]
@haodong
> arm64 is only supported [by MongoDB] on Ubuntu 16.04: https://docs.mongodb.com/manual/installation/#mongodb-supported-platforms
>
> \- https://github.com/docker-library/mongo/pull/293#issuecomment-415505621

Related: https://github.com/docker-library/mongo/issues/313
