### ISSUE TITLE
error exec numactl: executable file not found in $PATH

### ISSUE THREAD

**Issue by javiervivanco** [docker-library/mongo#26]
Hi, I Have this error in mongo:latest *59b3d123f9b8*

     error: exec: "numactl": executable file not found in $PATH

when run:

       docker run  mongo:latest
or

       docker run  mongo:latest mongod

or

     docker run -it --rm mongo:latest bash
     ./entrypoint.sh
or 

     docker run -it --rm mongo:latest bash
     ./entrypoint.sh mongod

* Docker version 1.4.1, build 5bc2ff8

docker info

    Containers: 43
    Images: 1125
    Storage Driver: aufs
    Root Dir: /var/lib/docker/aufs
    Dirs: 1219
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-44-generic
    Operating System: Ubuntu 14.04.1 LTS
    CPUs: 4
    Total Memory: 2.806 GiB
    Name: Latitude-E5510

**Comment by yosifkit** [comment]
I'm not getting this problem on the same image ID.  I thought [line 11-14](https://github.com/docker-library/mongo/blob/master/2.6/docker-entrypoint.sh#L11-14) was supposed to solve this and prevent `numactl` from running if it was not available.

```console
$ docker run -it --rm mongo bash
root@ace8d08d5ec1:/# which numactl
/usr/bin/numactl

$ docker run -it --rm debian
root@077255e8cec2:/# which numactl
root@077255e8cec2:/# 

$ docker images mongo
mongo               latest              59b3d123f9b8        2 weeks ago         392.4 MB
```

Have you tried removing the image (`docker rmi`) and docker pulling again?  Make sure to remove all tags that point to the same ID and any images that are FROM it so that the layers actually get deleted.

**Comment by chadmott** [comment]
I'm having the same issue, on a newly created EC2 instance Docker build 786b29d/1.7.1

```
Operating System: Amazon Linux AMI 2015.09
...
Digest: sha256:223d59692269be18696be5c4f48e3d4117c7f11e175fe760f6b575387abc1bba
Status: Downloaded newer image for mongo:latest
$ docker run --name some-mongo -v /home/somedir/mongo_data:/data/db -d mongo
f6df4673a16f478bd0e83e12845f23c5a1c3fdf1ccf1a7cee0718636fbab88d0
$ docker logs f6
error: exec: "numactl": executable file not found in $PATH
```
Any thoughts?

**Comment by tianon** [comment]
This sounds suspiciously like image layer corruption -- have you tried completely purging all the related layers (especially the one that actually includes the `numactl` binary) and re-pulling?

**Comment by chadmott** [comment]
@tianon yes I did, and it didn't work, though I suppose some sort of image caching could have been in play... Not sure. I've since upgraded host/dicker and it is fine tho
