### ISSUE TITLE
mongodb:3.6 doesn't bind to the docker network interface

### ISSUE THREAD

**Issue by andytson-inviqa** [docker-library/mongo#261]
I understand the reasoning for the software itself to default to the loopback adapter, but in docker, you're not exposing to the host's network adapters by default.

Please can the docker image be updated to bind back to 0.0.0.0?

In the very least, please mention it on in the readme/docker hub, as you say how to expose the port to the docker network yet that's not going to work without changing the mongodb configuration or CMD to fix the bind ip.

**Comment by tianon** [comment]
We already do exactly that:

https://github.com/docker-library/mongo/blob/master/3.6/docker-entrypoint.sh#L323-L333

**Comment by andytson-inviqa** [comment]
I see, our downstream image Dockerfile was created before you added the initdb work and changed the CMD, so this was not run. Thanks, I'll update our image to the newer way
