### ISSUE TITLE
not authorized on admin to execute command

### ISSUE THREAD

**Issue by ycjcl868** [docker-library/mongo#274]
## My docker-compose

```sh
 mongodb:
    image: mongo:3.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kylin
      - MONGO_INITDB_ROOT_PASSWORD=ycjcl868
      - MONGO_INITDB_DATABASE=object_detection
    volumes:
      - pro-mongo:/data/db
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
```

## my db/init.js
```
db.createUser({
  user: 'kylin',
  pwd: 'ycjcl868',
  roles: [
    {
      role: 'readWrite',
      db: 'object_detection',
    },
  ],
});

db.auth('kylin', 'ycjcl868');

db.training.insert({
  url: 'https://kylinking.oss-cn-qingdao.aliyuncs.com/objewefwefwetion/4ewefewwefwe511d05e5aa.jpg',
  concept: ['aaa', 'bbb'],
  isUsed: false,
  createTime: Date.now(),
  updateTime: Date.now(),
});

```

## Snapshot
![image](https://user-images.githubusercontent.com/13595509/40209153-4d4b0ed6-5a70-11e8-85c8-858c7b96e753.png)

**Comment by tianon** [comment]
When you use `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` to create a user, it will always use an `authenticationDatabase` of `admin` (https://github.com/docker-library/mongo/blob/f77d645e749bdda0740a35c00213baae8859edf2/3.2/docker-entrypoint.sh#L291), regardless of the value of `MONGO_INITDB_DATABASE`.

See also the new section in the docs at https://hub.docker.com/_/mongo/:

> This user is created in the `admin` authentication database and given the role of `root`.

So, if you update your code to use `--authenticationDatabase admin` instead, it should work properly.

I'm also not sure why you're doing a _second_ `db.createUser` in your `init.js` file -- that's probably not necessary?

**Comment by ycjcl868** [comment]
@tianon second `init.js` help me create collections. (yd init a existing db)

**Comment by darmawan01** [comment]
halo, i am getting the same issue. first i run docker-compose up the user create. but on second i remove container and image and try run docker compose up again. user not created
