### ISSUE TITLE
Retrieve environment vars in JavaScript initialisation script(s)

### ISSUE THREAD

**Issue by ivanmaeder** [docker-library/mongo#277]
I'd like to be able to create a DB user in an initialisation JavaScript file (copied into the `docker-entrypoint-initdb.d/` directory), **separate** to the admin user. Something like this:

```
db.createUser({
    user: process.env.DB_USER,
    pwd: process.env.DB_PASSWORD,
    roles: [{
        role: 'readWrite',
        db: process.env.DB_NAME
});
```

But `process` is not available, and I can't figure out any other way to do it.

Just to clarify:

1. Initialisation with `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` works fine, but my understanding is that this is for an admin-type user (not "user space")
2. I'd like to keep the password secret (hence trying to use env vars in the `createUser()` call)

Is this possible? If not, can this be a feature request? I'm not even sure if it's possible unless MongoDB officially make changes on their end, and so this would be a feature request for MongoDB.

For posterity, I'm achieving the same thing with this shell script, but it's not pretty:

```
mongo --eval "\
    db = connect('localhost:27017/admin'); \
    db.auth('$MONGO_INITDB_ROOT_USERNAME', '$MONGO_INITDB_ROOT_PASSWORD'); \
    db = db.getSiblingDB('$DB_NAME'); \
    db.createUser({ \
        user: '$DB_USER', \
        pwd: '$DB_PASSWORD', \
        roles: [{ \
            role: 'readWrite', \
            db: '$DB_NAME' \
        }] \
    });"
```

I'm using macOS.

**Comment by tianon** [comment]
We pass `.js` files directly to `mongo` unchanged, and I'm not aware of any way to read environment variables there, so this would definitely need to be an upstream feature request, sorry!

**Comment by ivanmaeder** [comment]
Fair enough. Thanks @wglambert

**Comment by ArtemeeSenin** [comment]
@ivanmaeder I suppose if you really need to use the variables you can use `envsubst` to replace them at runtime before executing `docker stack` or `docker-compose` on machine which has that particular variables
