### ISSUE TITLE
When will Mongo v3.7 become stable/latest?

### ISSUE THREAD

**Issue by lag-linaro** [docker-library/mongo#279]
Currently, if you wish to pull an ARM64 supported image you have to specify mongo:3.7.

**Comment by lag-linaro** [comment]
Thanks for the info.  Do you know what the timeline is for 4.0 to go GA?

**Comment by tianon** [comment]
Sorry, no, I'm not aware of anywhere that they publish timelines for
releases.

**Comment by tianon** [comment]
(but typically, they don't last very long once it hits RCs)

**Comment by wglambert** [comment]
Stable release for 4.0 was June 27
