### ISSUE TITLE
MongoDB packages do not support SSL

### ISSUE THREAD

**Issue by buth** [docker-library/mongo#28]
It looks like the only way to get SSL support in MongoDB is to build it from source. Is that a possible direction for this image?

**Comment by tianon** [comment]
So, with the new 3.0 release, they changed their APT repo and it includes SSL support, but we're currently still consuming the binary tarballs, which their website labels as "legacy" now.  I'm in favor of switching to APT, which will also happen to fix this issue.

I'm gonna start working up a PR, but what are your thoughts on this, @yosifkit?

**Comment by buth** [comment]
Would this still eave behind 2.x.x versions? It doesn't seem that they've updated their APT repo to include SSL for those versions.

**Comment by tianon** [comment]
True, it would indeed.  I'm not comfortable switching to compiling from source though, especially just for 2.x and even more especially when upstream has official binaries and recommends their use.

**Comment by buth** [comment]
That makes sense. Having SSL support in any version via this image will still be very useful. My use-case is interacting with legacy databases with the client binaries (dump, restore, etc.), and it seems like the 3.x versions may be compatible enough. Thanks for having a look.
