### ISSUE TITLE
Obsolete Debian release is being used

### ISSUE THREAD

**Issue by mlowicki** [docker-library/mongo#280]
As in https://github.com/docker-library/pypy/issues/24.

```
Debian Jessie will be in LTS phase since June 2018[6]; what it really means: the support will be provided "by a separate group of volunteers and companies interested in making it a success"
```

**Comment by tianon** [comment]
This was mostly fixed via https://github.com/docker-library/mongo/pull/275 -- older releases are the only ones still on Jessie, and of them, only 3.6 even _could_ be updated to Stretch (http://repo.mongodb.org/apt/debian/dists/stretch/mongodb-org/).

**Comment by tianon** [comment]
Unfortunately, without upstream support, this is as "fixed" as it can be.  If you're concerned about avoiding Debian Jessie, you need to upgrade to MongoDB 3.6 or above (which is a prudent plan anyhow).  Closing issue accordingly.

**Comment by tianon** [comment]
Crap, I just lied slightly -- we _do_ need to update 3.6 to Stretch: (reopening again :sweat_smile:)

```console
$ bashbrew from --uniq mongo | grep -v windows
mongo:3.2.20-jessie: debian:jessie-slim
mongo:3.4.16-jessie: debian:jessie-slim
mongo:3.6.7-jessie: debian:jessie-slim
mongo:4.0.1-xenial: ubuntu:xenial
mongo:4.1.2-xenial: ubuntu:xenial
```
