### ISSUE TITLE
docker-entrypoint-initdb.d scripts running with wrong port?

### ISSUE THREAD

**Issue by J0s3f** [docker-library/mongo#284]
For automated tests, I need to create a replica set consisting of a single node to have working transactions.
Because the Port used is exposed on the build server, I use a non standard port
I changed the commandline to: `--replSet rs0 --port 12345` and mounted a JavaScript file to init the rs.
The file contains:
`rs.initiate({ _id: "rs0", version: 1, members: [ { _id: 0, host: "127.0.0.1:12345" } ] });`

The JavaScript cannot be executed, because the server is not found at `127.0.0.1:12345`.

I assume, the first start of mongo to execute the scripts ignores the port option?

**Comment by wglambert** [comment]
You need to give the `-p 12345:12345` flag to docker.

```console
$ docker run --rm -p 12345:12345 -d --name mongo mongo --replSet rs0 --port 12345
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                 NAMES
532f7f4c8e0d        mongo               "docker-entrypoint.s…"   9 seconds ago       Up 8 seconds        0.0.0.0:12345->12345/tcp, 27017/tcp   mongo
```

**Comment by J0s3f** [comment]
No.

The startup scripts are executed inside the container anyway, so this changes nothing.

**Comment by ft0907** [comment]
I have similar needs and problems with you. I don't know how you solved them. Can you share them if they are solved?
The replica set configuration needs to be configured in the Mongo shell after Mongo is started, I execute after the mount script, but only after the dockerfile execution will execute the mongod boot command, and the Mongo shell command cannot be executed

**Comment by tianon** [comment]
Oh interesting -- we do indeed set a specific port at https://github.com/docker-library/mongo/blob/281c91f0148cf73d6ee3d64c94aa5d51c9b0b4be/4.0/docker-entrypoint.sh#L234 because we need to know where to connect in order to actually run the initdb scripts.

**Comment by J0s3f** [comment]
@ft0907 for our tests, they now run on port 27017 outside and inside the container. Currently, we can't run two integration tests needing docker on the same Jenkins node in parallel. That's unfortunate, but the way it is for now.

For deployments we create the replica set manually.

**Comment by ft0907** [comment]
@J0s3f  I have been able to automatically configure permissions + replica sets by way of dockerfile+dockercompose, but I'm testing on a single host. It can run well. Please look at the detailed code I posted. If there are any problems, we can discuss them. detailed answer code is here #211

**Comment by tianon** [comment]
So, in order for us to work around this, we'd have to not only parse provided command-line flags for `--port`, but also would need to parse any provided configuration file to do the same, so I'm inclined to say this is just outside of what we support out-of-the-box with the included behavior (unless someone's got a simpler idea for implementing something meaningful here).

**Comment by tianon** [comment]
Closing, since it looks like there aren't any better/simpler ideas for what we could change here. :disappointed:
