### ISSUE TITLE
Consider using current ubuntu LTS instead of xenial

### ISSUE THREAD

**Issue by zxaos** [docker-library/mongo#292]
#275 switched this to xenial, but the current ubuntu LTS is bionic. Switch to `ubuntu:bionic` instead?

**Comment by tianon** [comment]
See also https://github.com/docker-library/mongo/pull/297 :disappointed:

**Comment by zxaos** [comment]
I don’t suppose there’s any hope of supporting both? Or should I just go roll my own off bionic base at this point?

**Comment by tianon** [comment]
Yeah, supporting both is a bit much, but I am curious why you need the base
of this image on Bionic?  Are you building something on top of Mongo?

**Comment by zxaos** [comment]
Trying to have layer minimization between other images we’re deploying on the same machines, and the other images are all based on bionic.

**Comment by tianon** [comment]
Ah, ok, thanks for elaborating!  Yeah, you're probably right that you're
best off maintaining your own image at this point (which will probably be
better for you in the long run, since you'll be able to more directly
control the cache/layer sharing).
