### ISSUE TITLE
broken containers / registry

### ISSUE THREAD

**Issue by SavePointSam** [docker-library/mongo#295]
Just recently I tried to pull `docker:4.0` on CentOS and ran into the following issue:

```
$ docker pull mongo:4.0
4.0: Pulling from library/mongo
no matching manifest for linux/amd64 in the manifest list entries
```

This has worked for me just fine for the last couple weeks. When looking at another team member's cached container, I see the following:

```
$ docker images
REPOSITORY            TAG           IMAGE ID            CREATED             SIZE
mongo                 4.0           8bf72137439e        12 days ago         380MB
```

However, on docker hub it appears something went very wrong a couple hours ago. The containers listed are MUCH larger than they should be and were needlessly overwritten.

![image](https://user-images.githubusercontent.com/8203211/44493349-7eb6bb80-a61c-11e8-9902-8f4d37d51455.png)

**Comment by aaroncolwill** [comment]
Seeing the same issue in our k8s cluster when starting pods.
```Failed to pull image "mongo": rpc error: code = Unknown desc = no supported platform found in manifest list```

**Comment by wglambert** [comment]
This was an issue of https://github.com/docker-library/official-images/issues/3835 and is resolved now 

```console
$ docker pull mongo:4.0
4.0: Pulling from library/mongo
124c757242f8: Pull complete 
2ebc019eb4e2: Pull complete 
dac0825f7ffb: Pull complete 
82b0bb65d1bf: Pull complete 
ef3b655c7f88: Pull complete 
7390dfec61b2: Pull complete 
d0d69d17b8ae: Pull complete 
0f1361c44993: Pull complete 
4803d25be6fa: Pull complete 
d886a5975bd2: Pull complete 
bfada64c4b00: Pull complete 
40efead10b68: Pull complete 
179020b066d6: Pull complete 
d442d3a039f1: Pull complete 
Digest: sha256:80ab977292cf6e1fbc4d7a85bb6cfe85356af883647a4e2ec09c4c0edc30b28e
Status: Downloaded newer image for mongo:4.0
```
