### ISSUE TITLE
What's the difference between shared and simple tags?

### ISSUE THREAD

**Issue by x-yuri** [docker-library/mongo#316]
Mongo's [README][1] has two categories of tags? What's the difference?

[1]: https://github.com/docker-library/docs/tree/725663803aa20b1d48553446d2c6564d058bdb47/mongo

**Comment by tianon** [comment]
I've taken a first pass at explaining this difference in a generic way over in https://github.com/docker-library/faq/pull/2. :+1:

**Comment by x-yuri** [comment]
@tianon So if I run an image with a shared tag... all images from the list are downloaded and one of those is automatically chosen? I guess not.

Also, the first link from both categories points to the same [file][1]. So does the second.

[1]: https://github.com/docker-library/mongo/blob/6932ac255d29759af9a74c6931faeb02de0fe53e/3.2/Dockerfile

**UPD** I probably see. `3.2.21`, `3.2` are shared tags. Both are assigned to each of the following images:

```
3.2.21-jessie
3.2.21-windowsservercore-ltsc2016
3.2.21-windowsservercore-1709
```

Which are identified by simple tags. Simple tags are like main tags. Shared tags group images together under common name. But what's the idea? How can I use shared tags? I don't think `docker` will chose automatically which image to download if I do:

```
$ docker run mongo:3.2
```

**Comment by tianon** [comment]
The point is that you can `docker run mongo:3.2` and it will roughly Do The Right Thing on both Linux and the various supported versions of Windows.

**Comment by tianon** [comment]
See also "manifest lists" in Docker (although we also already use manifest lists for multiarchitecture support, and your Docker client is smart enough to usually pull the correct image from that list).
