### ISSUE TITLE
name of keyserver is failed

### ISSUE THREAD

**Issue by FreshardF** [docker-library/mongo#318]
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keyring `/tmp/tmp.yxEKFjtGWD/secring.gpg' created
gpg: keyring `/tmp/tmp.yxEKFjtGWD/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
?: ha.pool.sks-keyservers.net: Network is unreachable
gpgkeys: HTTP fetch error 7: couldn't connect: Network is unreachable
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found

you need change this command 
gpg --batch --keyserver ha.pool.sks-keyservers.net
to
gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749
