### ISSUE TITLE
mongo container failed if pass any mongod parameters in windows 10 docker

### ISSUE THREAD

**Issue by rockyzhao** [docker-library/mongo#322]
Offical mongo container works fine without any mongod command line parameters. but if I put any parameter, such as `--replSet “rs0"` or `--config /etc/mongo/mongod.conf` or `--dbpath d:\temp\db1` or `--logpath d:\temp\db1\mongod.log`, the container failed to run (failed at same location), for example:
```console

docker run --name mongo-node1 -d --net csc-mongo-cluster mongo --replSet “rs0"
ee683b7d20338b475b0f477f64326fa2ee9441a8b0f8326b2e0bf7b0260eefce
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container ee683b7d20338b475b0f477f64326fa2ee9441a8b0f8326b2e0bf7b0260eefce encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(174)\vmcomputeagent.exe!00007FF7AF58C00A: (caller: 00007FF7AF55ECEA) Exception(40) tid(368) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\ComputeSystemManager_ExecuteProcess\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"--replSet rs0","WorkingDirectory":"C:\\","Environment":{"MONGO_DOWNLOAD_SHA256":"e2ac83cfee3350012a641405ce5ba5c3cffe3f8d1a0cd5e0eb3e332246a9cc20","MONGO_DOWNLOAD_URL":"https://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-4.0.5-signed.msi","MONGO_VERSION":"4.0.5"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.
```

I am running Windowds 10 Pro (1803), docker version:
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:56:41 2018
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by wglambert** [comment]
The windows variants don't have an entrypoint script so you'll want to do something like `docker run --name mongo-node1 -d --net csc-mongo-cluster mongo mongod  --bind_ip_all --replSet “rs0"`

**Comment by rockyzhao** [comment]
Thank you very much! it works now
