### ISSUE TITLE
mongo:latest bound to localhost

### ISSUE THREAD

**Issue by flowl** [docker-library/mongo#325]
**Subject:**
The current latest (4.0 xenial).
`mongo:3.4.18-jessie` is not bound to localhost, but `mongo:4.0-xenial` is.

**Expected:**
A docker container is reachable from all hosts within the same docker-compose context or within the same network.

**Actual:**
The mongod by default is bound to `localhost` and does not accept connections from other hosts within the same network.

**Possible fix:**
Default (docker) configuration should not bind to localhost, or - for security's sake, there should at least be a hint and a kind of toggle / env variable to easily change this.

**Comment by wglambert** [comment]
MongoDB 3.6+ defaults to localhost-only binding
https://github.com/docker-library/mongo/blob/5ab118c15c474192dc6ab058e5cb370b73ced636/4.0/docker-entrypoint.sh#L323-L335

**Comment by flowl** [comment]
Could this be because I override the entrypoint by having `CMD mongod --smallfiles` at the end of my `Dockerfile`?

**Comment by tianon** [comment]
Yep, that's exactly it. Change that to `CMD ["mongod", "--smallfiles"]` and it should fix it.

**Comment by flowl** [comment]
@tianon @wglambert That works, thanks for your hint and apologies for the confusion.
