### ISSUE TITLE
docker-entrypoint.sh behaves incorrectly when "mongod" is provided as its argument, environment variables are set and numactl support detected on node.

### ISSUE THREAD

**Issue by Gapmeister66** [docker-library/mongo#330]
docker-entrypoint.sh works fine if "numactl" not detected because the arguments are not moved along:

```
if [[ "$1" == mongo* ]]; then
	numa='numactl --interleave=all'
	if $numa true &> /dev/null; then
		set -- $numa "$@"
	fi
fi
```

However if numactl is detected, "$1" is no longer set to "mongod" and therefore the following code fragment is never run:

```
if [ "$1" = 'mongod' ]; then
	file_env 'MONGO_INITDB_ROOT_USERNAME'
	file_env 'MONGO_INITDB_ROOT_PASSWORD'
	if [ "$MONGO_INITDB_ROOT_USERNAME" ] && [ "$MONGO_INITDB_ROOT_PASSWORD" ]; then
		set -- "$@" --auth
	fi
...
fi
```

this means that auth will never become enabled.

**Comment by yosifkit** [comment]
That looks like a fairly old image. This was fixed in https://github.com/docker-library/mongo/pull/161.

**Comment by Gapmeister66** [comment]
Thanks, I can see it now works for 3.4.19 and 4.1.7.

**Comment by was1130** [comment]
> Thanks, I can see it now works for 3.4.19 and 4.1.7.
can you share your yaml for me?thx!
