### ISSUE TITLE
Better example in Read Me for "Connect to MongoDB from another Docker container"

### ISSUE THREAD

**Issue by snoblenet** [docker-library/mongo#336]
At https://hub.docker.com/_/mongo/, under "Connect to MongoDB from another Docker container", the example given is if you want to run two MongoDB containers side-by-side, but you want to connect them so you only have to start the Mongo server in one of them. This makes for some very confusing language, with mongo-this and mongo-that spread over two lines. It's impossible to unpack host name from link name from tag name from service name across two run commands.

Would it be possible to replace this example with a more useful one please? The perfect example would be this: Mongo is running one container, your web server is running in another, and the web server needs to access Mongo.

Many thanks.

**Comment by tianon** [comment]
```console
$ docker network create some-network
$ docker run -d --name some-mongo --network some-network mongo:X.Y
$ docker run -d --name some-website --network some-network -e SOME_WEBSITE_MONGO=mongodb://some-mongo some-website-image
```

(Quite a bit more verbose and IMO not really any more clear.)

There's also a `stack.yml` example that I think is somewhat more clear: https://hub.docker.com/_/mongo#-via-docker-stack-deploy-or-docker-compose

**Comment by snoblenet** [comment]
Thanks. This worked for me:
```
$ docker network create skynet
$ docker run -d --name mongo --network skynet mongo:3.4.19
$ docker run -it --net skynet -e MONGO_HOST=mongo samsao/mongo-shell:3.4
```

**Comment by tianon** [comment]
Adjusted via https://github.com/docker-library/docs/pull/1441 :+1:
