### ISSUE TITLE
Failed to mount rexray volume - problem creating volume implicitly

### ISSUE THREAD

**Issue by rakeshyoga** [docker-library/mongo#344]
I'm using [DC/OS](https://docs.mesosphere.com/1.10/storage/external-storage/) to run mongo docker container and it is failed to deploy with the following errors.
```
I0402 18:04:56.477025 11102 exec.cpp:162] Version: 1.4.2
I0402 18:04:56.481741 11112 exec.cpp:236] Executor registered on agent 34a178b0-eafc-4899-b6f4-d420e94b1832-S18
I0402 18:04:56.482506 11124 executor.cpp:121] Registered docker executor on 10.168.246.117
I0402 18:04:56.482640 11112 executor.cpp:161] Starting task test-docker.d26f8538-5571-11e9-9c36-3285e7f2401e
W0402 18:05:01.485777 11126 executor.cpp:218] Docker inspect timed out after 5secs for container 'mesos-9a24dc48-e14b-46fb-8734-7da7cb44cf63'
W0402 18:05:06.577800 11126 executor.cpp:218] Docker inspect timed out after 5secs for container 'mesos-9a24dc48-e14b-46fb-8734-7da7cb44cf63'
docker: Error response from daemon: VolumeDriver.Mount: {"Error":"problem creating volume implicitly"}.
See 'docker run --help'.
I0402 18:05:07.562394 11111 executor.cpp:352] Received killTask for task test-docker.d26f8538-5571-11e9-9c36-3285e7f2401e
W0402 18:05:11.579516 11126 executor.cpp:218] Docker inspect timed out after 5secs for container 'mesos-9a24dc48-e14b-46fb-8734-7da7cb44cf63'
I0402 18:05:12.799762 11126 process.cpp:1068] Failed to accept socket: future discarded
```

Here is the configuration used to deploy the mongo docker container. 
```
{
  "id": "/test-docker",
  "instances": 1,
  "cpus": 2.0,
  "mem": 2048,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "mongo:4.0.5",
      "network": "HOST",
      "forcePullImage": true
    },
    "volumes": [
      {
        "containerPath": "/data/db",
        "external": {
          "name": "my-test-vol",
          "provider": "dvdi",
          "options": { "dvdi/driver": "rexray" }
        },
        "mode": "RW"
      }
    ]
  },
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  }
}
```
When I replace the mongo image with some other image name, then everything works fine. It is not working only for the **mongo** container. Is there any special configuration that I need to do to mount rexray volume?

**Comment by wglambert** [comment]
Is it related to the socket configuration/access rexray's using? https://rexray.readthedocs.io/en/stable/user-guide/schedulers/docker/

I'm not able to try and reproduce as I'm encountering quite a lot of install issues
```console
$ rexray service start
FATA[0000] failed to create known_hosts                  path=/home/rei/.rexray/known_hosts time=1554235582244

$ sudo rexray service start
error: service startup failed: libstorage: invalid format
```

I'd recommend asking a resource familiar with rexray for help troubleshooting your issue, if there is a fault with the image then we would be keen to alleviate that but without more concise detail I don't see anything we could do here.

**Comment by yosifkit** [comment]
It is most likely file system permissions and failure to chown:

https://github.com/docker-library/mongo/blob/ebba6ab73981e4d78ae03ec5a47c6e1afb1b9c47/docker-entrypoint.sh#L14

If you can tell dc/os to run the mongo image as a specific user, do that (and tell rexray to use that same user id for the storage).  Or you could try only telling rexray the user id that the mongo container usually runs as (`999:999`).

```console
$ docker run --rm mongo:4 id mongodb
uid=999(mongodb) gid=999(mongodb) groups=999(mongodb)
```

**Comment by rakeshyoga** [comment]
@yosifkit I tried running the container from dc/os using _mongodb_ user. I still see the same problem. Is there any way to customize the image, so that the mongodb user group and name could be an optional configuration?

**Comment by tianon** [comment]
Looking at https://docs.mesosphere.com/1.12/deploying-services/marathon-parameters/#container, I think you're going to have to use `parameters` under the `docker` object to add `--user` to your MongoDB image.

Another alternative could be a simple `Dockerfile` to create your own custom image:

```dockerfile
FROM mongo:4.0
USER xxx:yyy
```

Looking at your original error though, this seems more like a misconfiguration of DC/OS and/or Rexray than an issue with this image though: `docker: Error response from daemon: VolumeDriver.Mount: {"Error":"problem creating volume implicitly"}.`

I'd suggest trying a DC/OS or Rexray support forum for further help diagnosing the issues with your environment/configuration.

**Comment by rakeshyoga** [comment]
I end up creating my own mongo image using the mongo binary. Thanks, a lot for the input and suggestions.
