### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by Garito** [docker-library/mongo#35]
Hi!
Would like to consume the mongo logs but I don't wanna put them in the data folder

I check the entrypoint.sh file and I can see you change the data folder permissions so I understand that the same will be needed to the logs files

Or do you do this in another way?

Thanks!

**Comment by devinrsmith** [comment]
+1

**Comment by tianon** [comment]
By default, the logs don't go to a file, they go to stdout, so "docker logs
my-container" works, and in 1.6+ you can even redirect them with log
drivers, such as "--log-driver=syslog".

**Comment by devinrsmith** [comment]
I've got mine setup with a config:

```
$ cat /opt/testmongo/config/mongo.conf 
systemLog:
  destination: file
  path: "/logs/mongo.log"
  logAppend: true
```

I try to run `docker ... mongo -f /config/mongo.conf` and get the error: `2015-04-22T19:24:29.503+0000 SEVERE: Failed global initialization: FileNotOpen Failed to open "/logs/mongo.log"`

(But if I run `chown -R mongodb /logs` inside the container, it works as expected.)

**Comment by tianon** [comment]
Right, but how could our script know ahead of time which directories to
chown, since this is user-specified configuration?

**Comment by devinrsmith** [comment]
Agreed. 

It's just not immediately obvious why (without investigation into the inner working of the Dockerfile / entrypoint) we receive this error.

I think it should be mentioned in https://github.com/docker-library/docs/tree/master/mongo that `destionation: file` logging won't work unless the path is accessible to the mongodb user.

**Comment by tianon** [comment]
+1! :+1:

**Comment by Garito** [comment]
If I want to see a pattern with the existing entrypoint, this project must update the docker-entrypoint.sh adding:
chown -R mongodb /logs/db
In the same line a volume must to be created like:
VOLUME /logs/db

This is assuming the fact I'm caching the pattern correctly since my vote will go to do this modifications (the entrypoint and the dockerfile) but with this paths:
/data/mongodb
/logs/mongodb
since I could have more databases and all could fight for the db idea

Another change I would do will be to change the name docker-entrypoint.sh to entrypoint.sh since I don't get the need to add docker-

I don't really know how syslog works but I prefer the file option because I can consume it with logstash without touching the host filesystem

I you are agree with my bet, I could make a pull request to show you the actual changes in context and to test

What do you think?

**Comment by Garito** [comment]
hi again!
here: https://github.com/docker-library/elasticsearch/pull/18#issuecomment-94256109
make a good point: why to change the default paths for data and logs?

I would like to change my mind and respect the default configuration on the whole docker official images

**Comment by yosifkit** [comment]
Actually, we don't have any active config, so we are getting the defaults from the daemon, ie the data dir of `/data/db/` ([docs.mongodb](http://docs.mongodb.org/manual/reference/configuration-options/#storage.dbPath)). This does not conflict with [mariadb](https://github.com/docker-library/mariadb/blob/master/10.0/Dockerfile#L29), [mysql](https://github.com/docker-library/mariadb/blob/master/10.0/Dockerfile#L29), [percona](https://github.com/docker-library/percona/blob/master/5.6/Dockerfile#L21), [rabbitmq](https://github.com/docker-library/rabbitmq/blob/master/Dockerfile#L43), [postgres](https://github.com/docker-library/postgres/blob/master/9.4/Dockerfile#L43), [elasticsearch](https://github.com/docker-library/elasticsearch/blob/master/1.5/Dockerfile#L28), or [redis](https://github.com/docker-library/redis/blob/master/3.0/Dockerfile#L38).  Changing the data directory will break a non-zero number of users. The default logging, when you don't give a `systemLog.destination`, is to standard out ([docs.mongo](http://docs.mongodb.org/manual/reference/configuration-options/#systemLog.destination)).

I would be in favor of documenting how a user can handle logging in a nice way.

**Comment by Garito** [comment]
Then is good enought to me
Agree too with the log issue: seems to me that the correct way is to put them in the mongo's standard location and change the permissions ala data folder in the entrypoint

**Comment by n9code** [comment]
Referring to [this ticket](https://github.com/docker/docker/issues/20) Docker stores the logs, even to the `stdout`, so if your restart your container, they will be stored, i.e. you can view old logs using `--since` option of `logs` command.

**Comment by wattletimber** [comment]
Hi Guys. My container is increasing by a gig everyday please help.

ubuntu@ip-172-31-5-57:~$ sudo du -ch -d 1 /var/lib/docker
9.9G /var/lib/docker/containers
8.0K /var/lib/docker/tmp
2.9M /var/lib/docker/image
60K /var/lib/docker/volumes
4.0K /var/lib/docker/trust
1.4G /var/lib/docker/aufs
60K /var/lib/docker/network
12G /var/lib/docker
12G total
<img width="1085" alt="screen shot 2016-06-02 at 6 22 40 am" src="https://cloud.githubusercontent.com/assets/19662899/15812854/f66aee38-2bb9-11e6-9ed8-4f69ca43c171.png">

**Comment by yosifkit** [comment]
Closing old issue. The solution is to either provide `--logpath` and  `--logappend` via command line options or config file, or to configure [docker log drivers](https://docs.docker.com/engine/admin/logging/overview/#/json-file-options) as desired.

Related to https://github.com/docker-library/mongo/issues/103#issuecomment-233438299.
