### ISSUE TITLE
Start mongod as root

### ISSUE THREAD

**Issue by AjawadMahmoud** [docker-library/mongo#351]
I have a scenario where a shared mounted network drive is not saving the files from `/data/db` when the user is non-root. That is some other issue I'm looking into it separately. But, I'm thinking that for quick testing purpose and to confirm that the issue is this I would like to know how can I edit the entrypoint without rebuilding the whole image (Can I?) to start `mongod` as root and skip all the `chown`, `chmod` instructions.

**Comment by tianon** [comment]
I'd suggest using `--entrypoint mongod` to skip our script entirely.

**Comment by AjawadMahmoud** [comment]
@tianon, that's not an option where I need to start the image. I can only start it with the environment vars. I tried manipulating the `entrypoint` file to drop the block for `gosu` as well as changed `Dockerfile` to remove the steps to install the same. But now I'm getting:
```
standard_init_linux.go:207: exec user process caused "no such file or directory"
```
when trying to build the image on my windows machine. Is this something you can comment on?

**Comment by wglambert** [comment]
Did you remove https://github.com/docker-library/mongo/blob/09972ffcbb43fcddae202a2a4d71a195f0e05ab7/4.1/docker-entrypoint.sh#L22

**Comment by tianon** [comment]
`standard_init_linux.go:207: exec user process caused "no such file or directory"` is typically due to missing `chmod +x` on the file (or having a bad shebang line).

I'm not sure where you're trying to run this that you can't set `entrypoint:` (I knew there were a few places that didn't allow that previously, but I'd thought they'd all received an update to allow it since), but you should be able to do the same thing via a short `Dockerfile`, ala:

```dockerfile
FROM mongo:4.0
ENTRYPOINT []
CMD ["mongod"]
```

**Comment by AjawadMahmoud** [comment]
@wglambert, yes. I removed this line.

@tianon, this would end up causing me lose the ability to set superadmin credentials and the default database name. That's why I'm trying to only remove the part where it steps down from root. I already starting rebuilding the `entrypoint` from the ground for this purpose, which is definitely based on yours.

**Comment by AjawadMahmoud** [comment]
I'm closing the issue as I found a way around by reusing `entrypoint`.
