### ISSUE TITLE
New Commands fail in docker-entrypoint.sh script

### ISSUE THREAD

**Issue by tarunngidwani** [docker-library/mongo#357]
Hello,

I am trying to add some commands to the docker-entrypoint.sh and it seems to be failing. Specifically I am trying to **run envsubst**. Here is the exact command:

`envsubst < /workspace/config/mongod.conf.template > /workspace/mongod.conf`

I have added the above line right before the `exec $@` at the end of the script. I keep getting this error: 

`./start-db.sh: line 378: /workspace/mongod.conf: Permission denied`
 
Other commands such as unset, ls, pwd work fine but I am not sure why this specific **envsubst command keeps failing**? Any ideas, thoughts, help would be much appreciated.

**Note:** I have tested the above failing command stand-alone and in a different script and it runs without any issues but fails in the docker-entrypoint.sh script.

**Comment by tianon** [comment]
It's likely due to not running as root:

https://github.com/docker-library/mongo/blob/3f117ac35a947ddff307aee85ecd5abe9e3a0fe1/4.0/docker-entrypoint.sh#L22

If you pre-create `/workspace` or use `/tmp` or something writable my the `mongodb` user instead, it will probably work.

**Comment by tarunngidwani** [comment]
@tianon When I try to run my commands before the gosu I am root but my commands run twice once as root and then as mongodb user. Any ideas on why that is the case?

**Comment by tianon** [comment]
That'd be because of the same line I linked you to: https://github.com/docker-library/mongo/blob/3f117ac35a947ddff307aee85ecd5abe9e3a0fe1/4.0/docker-entrypoint.sh#L22

The `gosu` re-runs the entrypoint as `mongodb`.

**Comment by tianon** [comment]
(Closing this, since it's not an issue with the image itself perse.)
