### ISSUE TITLE
Outdated docs on dockerhub

### ISSUE THREAD

**Issue by 0mars** [docker-library/mongo#362]
https://hub.docker.com/_/mongo

option --smallfiles is used, while it is not supported by mongo v4.1.13

gives unrecognized option
What is the alternative ? and a documentation update is probably needed

Thanks

**Comment by wglambert** [comment]
That section is an example
>See below an example of setting MongoDB to use a smaller default file size

For which variant of Mongo does it not apply?

```console
$ docker run --name some-mongo -d --rm mongo --smallfiles
d8e76e840481a015ea2d7e234916dea81bf97a4a8f70866772ceb2c2307268b4

$ docker logs some-mongo | grep -i small
2019-07-26T16:11:58.070+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, storage: { mmapv1: { smallFiles: true } } }
```
