### ISSUE TITLE
Tag mongo:4.2 Image, Environment Variables, and TLS are Incompatible

### ISSUE THREAD

**Issue by LeaderXFX** [docker-library/mongo#367]
Using env `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` forces the mongo docker image mongo:4.2 to default to net.ssl, which is deprecated. Therefore, on image mongo:4.2, if you use `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD`, you are unable to use net.tls settings.

**Results in error:**
_Docker Run with TLS_
```
docker run -d --name=mongo42-example \
-e MONGO_INITDB_ROOT_PASSWORD=Example \
-e MONGO_INITDB_ROOT_USERNAME=Example \
-v /keyfile:/keyfile mongo:4.2 --tlsMode requireTLS --tlsDisabledProtocols TLS1_1 --tlsCertificateKeyFile /keyfile/keyfile.pem
```
_Error Message_
```
W  CONTROL  [main] Option: sslMode is deprecated. Please use tlsMode instead.
F  CONTROL  [main] Failed global initialization: BadValue: net.ssl.mode is not allowed when net.tls.mode is specified
```
**SSL Mode Without Error:**
_Docker Run with SSL_
```
docker run -d --name=mongo42-example \
-e MONGO_INITDB_ROOT_PASSWORD=Example \
-e MONGO_INITDB_ROOT_USERNAME=Example \
-v /keyfile:/keyfile mongo:4.2 --sslMode requireSSL --sslDisabledProtocols TLS1_1 --sslPEMKeyFile /keyfile/keyfile.pem
```

**Comment by yosifkit** [comment]
That sounds like we need to improve these lines to account for `tlsMode` too:

https://github.com/docker-library/mongo/blob/687a397947f374e3bd6dbdf00a98753584833d96/docker-entrypoint.sh#L256-L257

and maybe these ones:

https://github.com/docker-library/mongo/blob/687a397947f374e3bd6dbdf00a98753584833d96/docker-entrypoint.sh#L152-L158

**Comment by yosifkit** [comment]
While a fix is developed, you can just use the `ssl` versions of the arguments, since they work the same.

> Starting in version 4.2, MongoDB provides `net.tls` settings (and corresponding command-line options) that corresponds to the `net.ssl` settings (and their corresponding command-line options). The `net.tls` settings provide identical functionality as the `net.ssl` options since MongoDB has always supported TLS 1.0 and later.
>
> https://docs.mongodb.com/manual/tutorial/configure-ssl/#procedures-using-net-tls-settings
