### ISSUE TITLE
Latest image empty IP address

### ISSUE THREAD

**Issue by staminna** [docker-library/mongo#369]
Hi

I pulled latest mongo from docker hub, and docker inspect mongo | grep "IP" shows empty address.

           "Networks": {
                "cornerjob_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "d3a5481cecc5",
                        "mongo"
                    ],
                    "NetworkID": "2dccd35cf9479b86ce32ee600153c5f74f3eaa162532412b2c5b9e4a2b90a932",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }

How can I set a IP on docker-compose.yml file?

**Comment by wglambert** [comment]
Is your container is stopped?

```console
$ docker run -d --name mongo mongo
1e4d0a93108bcf2e8be4dd9630f14c3bd1b454b774040ed01c9aca05a9d5a22d

$ docker inspect mongo | jq '.[] | .NetworkSettings.Networks'
{
  "bridge": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": null,
    "NetworkID": "6b74b002ba9c5848757e60d8286a5d6a6d4bb4ebc9d20f65f09dea51a5422ac6",
    "EndpointID": "3bece51877f52eb121436ae9887e908e7979be6874fa8a9c670ebd4b308b55db",
    "Gateway": "172.17.0.1",
    "IPAddress": "172.17.0.4",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:ac:11:00:04",
    "DriverOpts": null
  }
}
```

```console
$ docker stop mongo
mongo

$ docker inspect mongo | jq '.[] | .NetworkSettings.Networks'
{
  "bridge": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": null,
    "NetworkID": "6b74b002ba9c5848757e60d8286a5d6a6d4bb4ebc9d20f65f09dea51a5422ac6",
    "EndpointID": "",
    "Gateway": "",
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "",
    "DriverOpts": null
  }
}
```

**Comment by staminna** [comment]
Hi

No, it wasn't. I had to link it to my Docker-container. yml file first.

Thanks
