### ISSUE TITLE
ARM64v8 latest unavailable

### ISSUE THREAD

**Issue by agowa338** [docker-library/mongo#378]
Currently there is no build for 4.2, 4.2.2 and latest for the arm64v8 platform.
Was that platform deprecated?

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/7094#issuecomment-564244244 -- it disappeared from the upstream repos, so the best bet would be to ask upstream why that happened.  Hopefully it's a simple oversight, but we don't really have any more visibility than that.
