### ISSUE TITLE
Seeding data into a database

### ISSUE THREAD

**Issue by willis7** [docker-library/mongo#38]
What is the best practice regarding seeding data? 

I have tried to run `mongo myDB myData.js` from a linked container, but get the error `bash: mongo: command not found`. I have also tried to run this same command on my extended mongo image, but get an error mongo isn't running - as expected. 

The only thing I can think of is to seed via the application, but this isn't practical. With this approach each time I deploy a new version of the application I would seed the data again - thats not an option for production.

Any help gratefully received.

**Comment by md5** [comment]
What image did you run when using the first command? Using a `mongo` client container linked to your extended `mongo` server image should work fine. Also, there shouldn't be any reason that you couldn't use your extended `mongo` image as the client by linking it to your `mongo` server.

**Comment by willis7** [comment]
Hi, thanks for the reply. 

I have uploaded my project, [invader-zim](https://github.com/willis7/invader-zim). The [README](https://github.com/willis7/invader-zim/blob/master/README.adoc#docker) includes all the steps I took for the first attempt. The Dockerfile you see in the project root is the image I tried to run `mongo` from. Its for the microservice, and the `start.sh` should seed the database then run the microservice.

**Comment by md5** [comment]
What you're doing in `start.sh` looks like it would work if you had a `mongo` command, but I don't see you installing one in the Dockerfile.

**Comment by md5** [comment]
One caveat would be that if you start the `invader-zim` and `mongo` containers using something like Docker compose or Upstart that starts them in rapid succession, then the Mongo server may not be ready to service requests from the `invader-zim` container. You may want to have a delay and retry in `start.sh`, similar to what's done in the `wordpress` container to way for MySQL to be ready: https://github.com/docker-library/wordpress/blob/d7be0b140da5e9ccddd0eab818e89e088ab1d5ef/apache/docker-entrypoint.sh#L123-L134

You'd probably want to use the `sleep` command and have a shell loop in your case as opposed to custom PHP code.

**Comment by willis7** [comment]
No, I don't have mongo installed in the `invader-zim` container. I have done that by design as I wanted it to be a single purpose container. I can install mongo, I guess, but is that the best I can do? It feels a little clunky, and adds bloat to the `invader-zim` container.

I'm actually leaning towards writing the seeding into the application and use environment variables to decide between environments.

**Comment by md5** [comment]
I only mentioned that because your `start.sh` assumes there is a `mongo` command. I agree that adding `mongo` to that image is a bit clunky.

Allowing the application to write the seems seems reasonable to me since `quotes.js` will already be packaged with the app since it's in `src/main/resources`.

**Comment by willis7** [comment]
I wasn't sure if the link also exposed the `mongo` command, but I see now that isn't the case. Also good to bounce ideas off people. Thanks for all of your assistance.

**Comment by willis7** [comment]
Sorry, the plot thickens!

After a few hours playing I realised I can create another container and connect using `mongo` as per the docs. Then all I need to do is the following:

`docker run -it --link zim-mongo:mongo --rm mongo sh -c 'exec mongo "$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/invasion" quote.js'`

This doesn't work as quote.js isn't present, so I'm thinking build another mongo image which has a `COPY quote.js /src/quote.js` then the command above should work. I shall report back either way.

**Comment by yosifkit** [comment]
Just mount in the javascript with  `-v /local/path/to/quote.js:/quote.js:ro`.  Then, no need for a new image :smile:.

**Comment by willis7** [comment]
Thanks yosifkit,  that worked perfectly!

`docker run -it  -v $PWD/db/quote.js:/src/quote.js:ro --link zim-mongo:mongo --rm mongo sh -c 'exec mongo "$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/invasion" /src/quote.js'`

Now to workout why my microservice is timing out connecting to mongo. Not a problem for this thread. Thank you both for putting up with me!!

**Comment by kidphys** [comment]
Is there anyway we can seed data into the image itself, or run the seeding script when container starts up?

**Comment by willis7** [comment]
kidphys - the method I described in my last comment will seed the running mongo container.

**Comment by kidphys** [comment]
I actually meant specifying the script in Dockerfile itself. Anyway, another problem I run into is that mongo takes sometime to startup, and the script fails if mongo is not ready. One way is to polling the logs to wait, but is there any better way?

**Comment by djeps** [comment]
I'd do this: 
`while ! nc -q 1 localhost 27017 </dev/null; do sleep 1; done`
