### ISSUE TITLE
Version 2.4 images throwing errors when pulling from Docker Hub

### ISSUE THREAD

**Issue by bilbof** [docker-library/mongo#382]
Hello,

I'm seeing the error `Error response from daemon: unexpected EOF` when pulling `mongo:2.4` images. It happens intermittently (around 80% of the time).

To reproduce the issue:

```
$ docker pull mongo:2.4.14
# Error response from daemon: unexpected EOF
```

When it does work, a warning is displayed:

> Image docker.io/library/mongo:2.4 uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/

Are there any plans to upgrade the 2.4 images to use the new schema version?

Thank you!

**Comment by tianon** [comment]
See https://github.com/docker-library/golang/issues/269#issuecomment-473094518 for some previous discussion around schema1 images.  We do not typically update or republish old images, even in the case of older image formats.  I think it's a shame that support for at least pulling these older images is going away, but we don't have any plans to change our process (all new images should be schema2 already).

That being said, it shouldn't be too difficult to dig up the old `Dockerfile` we used from this repository's history (or recreate it, as it is not terribly complex) and rebuild it for yourself.

**Comment by bilbof** [comment]
Thanks a lot, @tianon!
