### ISSUE TITLE
PPC64le support

### ISSUE THREAD

**Issue by sfantao** [docker-library/mongo#386]
Any chance support for ppc64le can be added? Linux image should work as well for this target.

I am happy to contribute support for ppc64le if I get some guidance on what are the steps to be followed.

**Comment by tianon** [comment]
Unfortunately MongoDB upstream isn't publishing "MongoDB Community" packages for `ppc64le` (because they don't officially support the Community edition on `ppc64le`), and we get our packages from them: http://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/multiverse/

See also https://docs.mongodb.com/manual/installation/#mongodb-supported-platforms, especially https://docs.mongodb.com/manual/installation/#ppc64le-mongodb-enterprise-edition.

**Comment by sfantao** [comment]
@tianon, thank you for the quick response - that makes sense.

**Comment by darkbasic** [comment]
What are the limitations of the enterprise version?
There are mongodb 6 packages available for RHEL 8:
https://www.mongodb.com/docs/manual/administration/production-notes/#std-label-prod-notes-supported-platforms-PPC64LE
https://www.mongodb.com/docs/manual/tutorial/install-mongodb-enterprise-on-red-hat/

I've tried it myself and I've managed to successfully create a working docker image.

**Comment by tianon** [comment]
That's probably a better question for a MongoDB support forum - I would _imagine_ you need to have a license in order to use it, but I don't actually know! :sweat_smile:

**Comment by darkbasic** [comment]
If that's the only restriction and we can actually redistribute it couldn't we make a mongo-enterprise image and let the user handle licenses issues?

**Comment by yosifkit** [comment]
One of the tenets of the Docker Official Images program is a "Focus on [Free](https://www.debian.org/social_contract#guidelines) and [Open-Source](https://opensource.org/) Software" ([`README.md`](https://github.com/docker-library/official-images/tree/7d7979d4629ee61dbc83d06f3e6e1ff1934b9f7b#what-are-official-images)). We do not plan to add any more commercial software into Official Images.

MongoDB Inc. publishes their commercial products as Docker images under their Verified Publisher namespace: https://hub.docker.com/u/mongodb/.

**Comment by darkbasic** [comment]
@yosifkit from what I can see it's amd64 only, do you know if I can download the dockerfile somewhere so I can build it for ppc64le?

**Comment by yosifkit** [comment]
I can't find anything obvious under `https://github.com/mongodb`. 🤷 You'd have to ask someone from MongoDB Inc.
