### ISSUE TITLE
Unable to authenticate when using environment variables

### ISSUE THREAD

**Issue by migrachev** [docker-library/mongo#393]
I am having trouble authenticating to mongo docker container.
(I have read all related issues but couldn't manage to make authentication work)

**My setup**
* ubuntu 16.04 server edition (hosting the docker that hosts the mongo container)
* windows 10 with mongo client (version 4.0.9)

**Setting up container on the server**
`docker pull mongo:4.0.9`
`docker run -d -p 27017-27019:27017-27019 --name my-mongo -e MONGO_INITDB_ROOT_USERNAME=milen -e MONGO_INITDB_ROOT_PASSWORD=secret mongo:4.0.9`

**Connecting via mongo client**
(I am completely sure about the server IP address)
`mongo --username milen --password secret 192.168.5.10 `

**My output**
`MongoDB shell version v4.0.9  `
`connecting to: mongodb://192.168.5.10:27017/test?gssapiServiceName=mongodb  `
`2020-03-17T10:59:39.471+0200 E QUERY    [js] Error: Authentication failed. :  `
`connect@src/mongo/shell/mongo.js:343:13  `
`@(connect):2:6  `
`exception: connect failed`

**Further observation**
When I attempt connecting without providing username and password connection is established. 
`mongo 192.168.5.10`
`MongoDB shell version v4.0.9  `
`connecting to: mongodb://192.168.5.10:27017/test?gssapiServiceName=mongodb  `
`Implicit session: session { "id" : UUID("ab83eb76-c5e4-4422-9139-7a9d909a2308") }  `
`MongoDB server version: 4.0.9  `  

However if I further want to authenticated using the mongo shell I get authentication failed again.
`> db.auth("milen", "secret")  `
`Error: Authentication failed.  `
`0  `

**Comment by wglambert** [comment]
Specify `--host 192.168.5.10` in your command, I'm not sure why but it causes mongo to use `test` as the auth db whereas specifying `--host` correctly uses `admin`

In your `docker logs` you'll see something like:
```console
ACCESS   [conn5] SASL SCRAM-SHA-1 authentication failed for milen on test from client 192.168.0.7:60538 ; UserNotFound: Could not find user "milen" for db "test"
```

Then changing it to `--host 192.168.5.10` or adding `--authenticationDatabase admin`
```console
ACCESS   [conn6] Successfully authenticated as principal milen on admin from client 192.168.0.7:60596
```

**Comment by migrachev** [comment]
Thanks a lot, adding the `--host` option to `192.168.10.23` did the trick.
It seem to be problem of the mongo shell itself. Anyway with the option it works.

For others let to this issue here is the connect command that worked at the end
`mongo --user milen --password secret --host 192.168.10.23`
