### ISSUE TITLE
Can't get mongo to create root user on initialization

### ISSUE THREAD

**Issue by BarnumD** [docker-library/mongo#404]
I'm attempting to start mongo in Kubernetes, but I have the same issue in regular docker.  I can't get the `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` to work if I pass custom commands.  I'm passing custom commands so that I can set replSet, oplogSize, wiredTigerCacheSizeGB, etc.

This successfully creates the root user.
`docker run -d -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=secret mongo:4.0.18`
```
...
Successfully added user: {
        "user" : "mongoadmin",
        "roles" : [
                {
                        "role" : "root",
                        "db" : "admin"
                }
        ]
}
```

This fails to produce any success method, and the user is not created.
`docker run -d -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=secret mongo:4.0.18 /usr/bin/mongod --wiredTigerCacheSizeGB 1`

Is there some command line parameter I'm missing that is causing it to skip the initialization?
Options reported on the first are;
```
options: { net: { bindIp: "127.0.0.1", port: 27017, ssl: { mode: "disabled" } }, processManagement: { fork: true, pidFilePath: "/tmp/docker-entrypoint-temp-mongod.pid" }, systemLog: { destination: "file", logAppend: true, path: "/proc/1/fd/1" } }
```
.. on the second;
```
options: { storage: { wiredTiger: { engineConfig: { cacheSizeGB: 1.0 } } } }
```

**Comment by yosifkit** [comment]
The entrypoint only does its initialization stuff if you are running `mongod` not `/usr/bin/mongod`, so the user creation part is skipped.

https://github.com/docker-library/mongo/blob/112494a28df43cd3c867f7487bcb825d9e176a7c/docker-entrypoint.sh#L192

Use either `mongod` or just leave it off entirely and just use the flags and `mongod` will be added for you:
```console
$ docker run -d \
-e MONGO_INITDB_ROOT_USERNAME=mongoadmin \
-e MONGO_INITDB_ROOT_PASSWORD=secret \
mongo:4.0.18 --wiredTigerCacheSizeGB 1
```

https://github.com/docker-library/mongo/blob/112494a28df43cd3c867f7487bcb825d9e176a7c/docker-entrypoint.sh#L4-L6

**Comment by BarnumD** [comment]
Thank you
