### ISSUE TITLE
A focal image

### ISSUE THREAD

**Issue by jomarocas** [docker-library/mongo#407]
Hi i want a focal image, exist a image with the latest ubuntu version? thanks

**Comment by tianon** [comment]
Our packages come from http://repo.mongodb.org/ which is directly supported/supplied/maintained by upstream.  As you can see in http://repo.mongodb.org/apt/ubuntu/dists/, it does not currently support Ubuntu Focal.

Also, the official download page at https://www.mongodb.com/download-center/community does not list Ubuntu Focal (yet?).

**Comment by akshaybabloo** [comment]
I think this supports now @tianon

**Comment by tianon** [comment]
@akshaybabloo indeed, it looks like 4.4 does (not any of the older releases, however), but it would unfortunately also mean we'd lose `s390x` support :disappointed:
