### ISSUE TITLE
Automatically add --keyFile when needed

### ISSUE THREAD

**Issue by profiprog** [docker-library/mongo#414]
When starting containers as replicaSet and databases are protected by `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD`, then containers cannot configure replicaSet with others when `--keyFile` is not configured.

#### Proposal:
Automatically add argument `--keyFile` and create file with content of environment variable `MONGO_INITDB_ROOT_PASSWORD`, when starting database in cluster mode.

#### Code doing this in ENTRYPOINT script (`docker-entrypoint.sh`):
```bash
DEFAULT_KEY_FILE="$HOME/.keyFile"

if _mongod_hack_have_arg --replSet "$@" && [ "$MONGO_INITDB_ROOT_USERNAME" ] && [ "$MONGO_INITDB_ROOT_PASSWORD" ] && ! _mongod_hack_have_arg --keyFile "$@"; then
  _mongod_hack_ensure_arg_val --keyFile "${DEFAULT_KEY_FILE}" "$@"
  set -- "${mongodHackedArgs[@]}"
fi

KEY_FILE="$(_mongod_hack_get_arg_val --keyFile "$@")"
if [ "$KEY_FILE" ]; then
  [ -r "$KEY_FILE" ] || cat > "$KEY_FILE" <<< "$MONGO_INITDB_ROOT_PASSWORD"
  chmod 0400 "$KEY_FILE"
fi
```
_Note:_ Code should appear before line ```unset "${!MONGO_INITDB_@}"```to having environment variable `MONGO_INITDB_ROOT_PASSWORD` still available.

**Comment by profiprog** [comment]
After few attempts I get this working code:
```bash
if _mongod_hack_have_arg --replSet "$@" && [ "$MONGO_INITDB_ROOT_USERNAME" ] && [ "$MONGO_INITDB_ROOT_PASSWORD" ] && ! _mongod_hack_have_arg --keyFile "$@"; then
	# if $HOME dir does not exists, create keyFile as temporary file
	[ -d "$HOME" -a -w "$HOME" ] && DEFAULT_KEY_FILE="$HOME/.keyFile" || DEFAULT_KEY_FILE="$(mktemp --suffix=.keyFile)"
	_mongod_hack_ensure_arg_val --keyFile "${DEFAULT_KEY_FILE}" "$@"
	set -- "${mongodHackedArgs[@]}"
fi
KEY_FILE="$(_mongod_hack_get_arg_val --keyFile "$@")"
# check content of keyFile must be readable and min. 6 characters
if [ "$KEY_FILE" ] && ! [ -r "$KEY_FILE" -a "$(stat --format=%s "$KEY_FILE")" -ge 6 ]; then
	[ -a "$KEY_FILE" ] || touch "$KEY_FILE" # create if not exists
	[ -w "$KEY_FILE" ] || chmod 0600 "$KEY_FILE"  # make writable if is not
	# Generate safe content (min. 6 characters, only base64 characters)
	KEY="$(echo -n "$MONGO_INITDB_ROOT_PASSWORD" | openssl dgst -sha256 -binary | openssl base64 -A)"
	cat > "$KEY_FILE" <<< "$KEY"
	chmod 0400 "$KEY_FILE"
fi
```
However, tests in pull request #415 still fails. Any idea why?

**Comment by tianon** [comment]
This is an interesting proposal, but I'm not sure the official image is the appropriate place for this functionality.  It shouldn't be too difficult to create an image that's `FROM mongo:xxx` which adds this.

For most production users, I think using a Docker or Kubernetes Secret file is probably a better way to share a `keyFile` between instances.  It also makes it much more obvious/declarative if it ever needs to be changed/rotated (whereas changing the value of `MONGO_INITDB_ROOT_PASSWORD` won't have any effect on the stored database contents).

**Comment by profiprog** [comment]
You are right, it wasn't difficult. This functionality can be added with `Dockerfile`:
```Dockerfile
ARG MONGO_TAG=4.2
FROM mongo:$MONGO_TAG
RUN mkhomedir_helper mongodb
COPY ./docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
```
and file `docker-entrypoint-initdb.d/auto-keyFile.sh`:
```bash
if _mongod_hack_have_arg --replSet "$@" && ! _mongod_hack_have_arg --keyFile "$@"; then
  KEY_FILE="$HOME/.keyFile"
  _mongod_hack_ensure_arg_val --keyFile "$KEY_FILE" "$@"
  set -- "${mongodHackedArgs[@]}"

  KEY="$(echo -n "$MONGO_INITDB_ROOT_PASSWORD" | openssl dgst -sha256 -binary | openssl base64 -A)"
  cat > "$KEY_FILE" <<< "$KEY"
  chmod 0400 "$KEY_FILE"
  echo "$BASH_SOURCE: added '--keyFile' '$KEY_FILE' (size $(wc -c "$KEY_FILE"))"
fi
```
And it is much easy and clean.
So I am closing this issue.
