### ISSUE TITLE
Add XFS/xfsprogs to image.

### ISSUE THREAD

**Issue by crunk1** [docker-library/mongo#416]
I already saw #135 but I'm not sure what the conclusion was. I'm a little confused by the response. It says the image is already on XFS? 

I have a container using mongo:4.4.0 and I want to mount a separate XFS volume to /data/db. When I try, I get "unknown filesystem type 'xfs'".

I'd be happy to do a PR to include xfsprogs. Thanks in advance!

**Comment by tianon** [comment]
I don't think `xfsprogs` inside the *image* entirely makes sense -- I think that should be installed on your host, and your filesystem mounted there and then bind-mounted into the container, ala:

```console
$ mount -t xfs /dev/sdx1 /mnt/mongodb-drive
$ mkdir /mnt/mongodb-drive/data-db
$ docker run ... --mount type=bind,src=/mnt/mongodb-drive/data-db,dst=/data/db mongo:xxx ...
```

**Comment by crunk1** [comment]
Any additional insights on what that might look like for kubernetes on GKE? They use Container optimized OS, which doesn't have XFS, I believe.

**Comment by tianon** [comment]
You'd have to take that up with GKE -- if the host OS doesn't support XFS, you're not going to get XFS working very reliably in a container without doing some serious hacks (which amount to breaking the container confinement and getting the XFS kernel module installed on the host).

**Comment by crunk1** [comment]
After a little research, I found GKE supports Ubuntu node hosts with XFS support, so thankfully, I have a way forward. That aside, thanks for helping me understand a bit more!
