### ISSUE TITLE
Install stable version of mongo for 3.1

### ISSUE THREAD

**Issue by sge-babrams** [docker-library/mongo#42]
Previously the image installed stable version of mongo: https://github.com/docker-library/mongo/blob/master/3.1/Dockerfile#L30

However in 3.1 it is now using unstable packages: https://github.com/docker-library/mongo/blob/master/3.1/Dockerfile#L30

I think that the majority of people expect to get stable versions by default and that if you want unstable its reasonable to use 3.1-unstable for unstable version

**Comment by yosifkit** [comment]
Odd dot series releases are always unstable in mongo

**Comment by tianon** [comment]
"odd numbered builds are development/*unstable* releases"

https://www.mongodb.org/downloads#development

**Comment by sge-babrams** [comment]
@yosifkit @tianon should there be a "latest-stable" and "latest-unstable" tags? So that you can set and forget it without having to worry too much? to match rolling release patterns. Obviously in production you want to pin a specific version but in dev envs you want the latest stable so that you can test your application with a version before sneaking its way into production

**Comment by tianon** [comment]
":latest" is latest stable
