### ISSUE TITLE
mongo:4.4.1 is missing

### ISSUE THREAD

**Issue by mritzmann** [docker-library/mongo#423]
Seems like MongoDB 4.4.1 [was released](https://docs.mongodb.com/manual/release-notes/4.4/#sep-9-2020) on Sep 9, 2020 bus is missing on docker hub.

```shell
$ docker pull mongo:4.4.1
Error response from daemon: manifest for mongo:4.4.1 not found: manifest unknown: manifest unknown
```

Maybe this is due the `Some checks were not successful` [here](https://github.com/docker-library/mongo/commit/d8f72cf4966794763be1600382656064c9d60d0d)?

I'm not sure if anybody has that on their radar, so I just created this issue here.  :-)

**Comment by adampl** [comment]
I'm wondering about that too. Is it in the build queue? If yes, where to get the information when it will be ready?

I've found this, but I don't know if it's the right place: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/mongo/

That would suggest that an amd64 image hasn't been built in 20 days.
Apparently the change to 4.4.1 was picked up by Jennkins yesterday: https://doi-janky.infosiftr.net/job/update.sh/job/mongo/5849/

Please someone share more insight.

**Comment by wglambert** [comment]
https://github.com/docker-library/mongo#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

Questions and discussions would be better answered on the update PR https://github.com/docker-library/official-images/pull/8698
Looks like it's being held up by a permissions issue on the Windows variant https://github.com/docker-library/official-images/pull/8698/checks?check_run_id=1093671106#step:6:72

**Comment by mritzmann** [comment]
> Questions and discussions would be better answered on the update PR docker-library/official-images#8698

Thank you for pointing that out, so I will close this issue.
