### ISSUE TITLE
Two mongod.exe running in 4.4.1-windowsservercore-1809 docker image

### ISSUE THREAD

**Issue by mail2hjain** [docker-library/mongo#426]
The docker image ```mongo:4.4.1-windowsservercore-1809``` starts two mongo daemon processes one as windows service and another as standalone process.

Command used to start the container : ```docker run mongo:4.4.1-windowsservercore-1809```
Once container is started, enter the container and run command ``` tasklist /svc``` gives output as -

Image Name                     PID Services
========================= ======== ============================================
System Idle Process              0 N/A
System                           4 N/A
smss.exe                       948 N/A
csrss.exe                      976 N/A
wininit.exe                    260 N/A
services.exe                   280 N/A
lsass.exe                      504 SamSs
fontdrvhost.exe                788 N/A
svchost.exe                    580 RpcEptMapper, RpcSs
svchost.exe                   1032 DcomLaunch, LSM, SystemEventsBroker
svchost.exe                   1096 gpsvc, iphlpsvc, ProfSvc, Schedule, SENS,
                                   UserManager, Winmgmt
svchost.exe                   1144 EventSystem, nsi, RemoteRegistry
CExecSvc.exe                  1168 cexecsvc
svchost.exe                   1228 Dhcp, EventLog, TimeBrokerSvc,
                                   WinHttpAutoProxySvc
**mongod.exe                    1272 N/A**
svchost.exe                   1340 CryptSvc, Dnscache, LanmanWorkstation, WinR
svchost.exe                   1428 CoreMessagingRegistrar
svchost.exe                   1464 DiagTrack
**mongod.exe                    1500 MongoDB**
svchost.exe                   1544 SysMain
WmiPrvSE.exe                  2068 N/A
conhost.exe                   2176 N/A
cmd.exe                       2188 N/A
tasklist.exe                  2236 N/A

Console Out: [mongo-container-console-out.txt](https://github.com/docker-library/mongo/files/5415943/mongo-container-console-out.txt)

**Comment by tianon** [comment]
Oh, interesting -- I guess we need to disable the installed service while we build. :disappointed:

Probably just something like `Set-Service MongoDB -StartupType Disabled` after we install?

I also have to wonder if there's some way to ask the installer not to register the service in the first place. :thinking:

**Comment by mail2hjain** [comment]
As a temporary workaround I am stopping the service manually with my startup script.  Hoping to get it fixed within the image itself. 
Also any plans to provide a windows equivalent of ```docker-entrypoint.sh```  🤓

**Comment by yosifkit** [comment]
> Also any plans to provide a windows equivalent of `docker-entrypoint.sh`

It is extremely unlikely, see also https://github.com/docker-library/mongo/issues/291#issuecomment-410813034.

**Comment by TBBle** [comment]
It would be possible to flick the container over to using the Service, rather than running the Binary, using https://github.com/Microsoft/IIS.ServiceMonitor as (per https://github.com/docker-library/mongo/issues/291#issuecomment-410813034)
> a process monitor as well to sit between Docker and mongod for the lifetime of the session (all for some simple initialization behavior, which is kind of a heavy toll).


That's what [IIS's Dockerfile](https://github.com/microsoft/iis-docker/blob/master/windowsservercore-ltsc2019/Dockerfile) does, for example.
