### ISSUE TITLE
omit --configsvr during initdb

### ISSUE THREAD

**Issue by benety** [docker-library/mongo#431]
Currently, initdb [omits both --auth and --replSet](https://github.com/docker-library/mongo/blob/cd315c60d63f034cf9556dc947b90a92eb535f09/4.4/docker-entrypoint.sh#L249) when adding the initial user for authentication.

When running a config server, initdb uses `--configsvr` for the standalone mongod server. I'm wondering if this option can be omitted just like `--auth` and `--replSet`. For the default dbpath, we would always provide a `--dbpath $dbPath` during initdb, similar to how initdb always overrides the [port](https://github.com/docker-library/mongo/blob/cd315c60d63f034cf9556dc947b90a92eb535f09/4.4/docker-entrypoint.sh#L246). 

This request is motivated by the work done in: https://jira.mongodb.org/browse/SERVER-51733

**Comment by yosifkit** [comment]
So is this not correct way to get the `/data/configdb` properly seeded? Why would this setup cause `mongod` to crash after the `rs.initiate`?
- run `mongod --configsvr`
- create an "admin" user
- stop `mongod`
- run `mongod --configsvr --auth --replSet 'myreplica'`
- run `rs.initiate()` via `mongo`

**Comment by benety** [comment]
There is a bug in 4.4 that would cause `mongod` to crash in this situation. The fix is already in the latest development version but not in 4.4 yet. The suggestion to the `initdb` steps here will avoid the crash for existing versions of 4.4 and will also work for earlier versions of `mongod`.

**Comment by benety** [comment]
This is no longer an issue now that the bug is fixed in 4.4.3. See SERVER-51733
