### ISSUE TITLE
community version?

### ISSUE THREAD

**Issue by ewoks** [docker-library/mongo#433]
Do these images (i.e. [v4.4.1](https://hub.docker.com/layers/mongo/library/mongo/4.4.1/images/sha256-31f6433f7cfcd2180483e40728cbf97142df1e85de36d80d75c93e5e7fe10405?context=explore)) comntain community or payed version of MongoDB?

Thanks

**Comment by ewoks** [comment]
executing `mongod --version` in container returns empty **"modules": []**, which should imply this is community version. In case of enterprise version value of "modules" would be 'enterprise'.

Can anyone confirm this please?

**Comment by wglambert** [comment]
It's the community edition
https://github.com/docker-library/mongo/blob/3f9f4cdaf6c6a64bf0ad32c7d10aa2029873f585/4.4/Dockerfile#L74-L77
