### ISSUE TITLE
gnupg: keyserver receive failed Cannot assign requested address

### ISSUE THREAD

**Issue by beaulabs** [docker-library/mongo#450]
Hello! Wanted to surface this for others who may be having similar issues. Tested on versions 4.4 and 4.2, when building MongoDB Enterprise containers you may run into random cannot assign requested address errors:

```
Step 9/22 : RUN set -ex;  export GNUPGHOME="$(mktemp -d)";  for key in $GPG_KEYS; do  gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; done;    gpg --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mongodb.gpg;    command -v gpgconf && gpgconf --kill all || :;  rm -r "$GNUPGHOME";     apt-key list
 ---> Running in 3f283098af09
+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.YkDbOPwROn
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys 20691EEC35216C63CAF66CE1656408E390CFB1F5
gpg: keybox '/tmp/tmp.YkDbOPwROn/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address
```
This appears to be related to gpg attempting to pull the key via IPv6. If that is not running or your network is not configured to support v6 it causes a comm failure. 

There were two methods I used in debugging to get around it and successfully build the containers. 

First was to just change the server pool that gpg was reaching out to only use IPv4:

>https://sks-keyservers.net/overview-of-pools.php

```
ENV GPG_KEYS 20691EEC35216C63CAF66CE1656408E390CFB1F5
RUN set -ex; \
	export GNUPGHOME="$(mktemp -d)"; \
	for key in $GPG_KEYS; do \
	gpg --batch --keyserver ipv4.pool.sks-keyservers.net --recv-keys "$key"; \
	done; \
	gpg --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mongodb.gpg; \
	command -v gpgconf && gpgconf --kill all || :; \
	rm -r "$GNUPGHOME"; \
	apt-key list
```
The other method, since it was an ubuntu based image, was to execute ```sysctl -w``` to disable ipv6 and to inject just during the build to be able to pull the keys. 

```
RUN set -ex; \
	sysctl -w net.ipv6.conf.all.disable_ipv6=1; \
	sysctl -w net.ipv6.conf.default.disable_ipv6=1; \
	sysctl -w net.ipv6.conf.lo.disable_ipv6=1; \
```

However if you use the image to build out other container versions ipv6 will rear up again. So I also set it into **/etc/sysctl.conf** to hold it for later builds just for my environment.  

One could also disable gpg from using ipv6 in dirmngr.conf, (original bug/description to handle via dirmngr [here](https://dev.gnupg.org/rGecfc4db3a2f8bc2652ba4ac4de5ca1cd13bfcbec)) but due to time I didn't rabbit down that trail. 

Don't know if others have seen this, but just wanted to pass along the issue, wasn't sure how the team might want to handle it.

**Comment by tianon** [comment]
Yeah, it's definitely a very flaky situation, and the "successful" workarounds will vary by the environment and over time.

See https://github.com/docker-library/faq#openpgp--gnupg-keys-and-verification for an "official" description of how we handle it (essentially a MitM on the keyserver network to try the request against many servers simultaneously instead).

Frankly, the most "successful" solution we've found is convincing the key owner to verify their email address on keys.openpgp.org (https://keys.openpgp.org/about), but that requires more upstream coordination than we're often able to drum up. :disappointed:

**Comment by beaulabs** [comment]
Thanks for the quick response and info...I can see what you mean about the coordination on email address. As this seems to be more of a gpg related process workaround and not a specific bug I'll close this and keep it more for record of information on ways to bypass when "cannot assign requested" comes up. Cheers!
