### ISSUE TITLE
exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by LeoChenHere** [docker-library/mongo#456]
there is a missing code in Dockfile at this step : 
```
ENTRYPOINT ["docker-entrypoint.sh"]
```
modify this line to fix it 
```
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
```
then there is another issue occur : 
```
exec: "/usr/local/bin/docker-entrypoint.sh": permission denied: unknown.
```
add a line before this line to fix it 
```
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
```
then this bug will be fixed.

**Comment by wglambert** [comment]
If you downloaded the repo's file with something other than `git clone` then the execute permissions weren't persisted.
https://github.com/docker-library/postgres/issues/386#issuecomment-350323371
https://github.com/docker-library/postgres/issues/296#issuecomment-308735942

**Comment by wglambert** [comment]
Since this isn't an issue with the image I'm going to close
