### ISSUE TITLE
It would be nice to have mongo images based on debian jessie.

### ISSUE THREAD

**Issue by ssreekanth** [docker-library/mongo#46]
Saves space by not pulling different versions of debian for different applications, as my other apps' images are all based from debian jessie.

**Comment by tianon** [comment]
I'd be +1to switching the base, but upstream's apt repo doesn't include
anything but wheezy: http://repo.mongodb.org/apt/debian/dists/

**Comment by ssreekanth** [comment]
Ref: https://jira.mongodb.org/browse/SERVER-18329

Not sure why jessie is not included in the upstream apt repo yet. If there are no real issues with mongodb on jessie, then we should have separate images, tagged appropriately, just like how nodejs official images (https://registry.hub.docker.com/_/node/) are provided.

**Comment by Unbr8kbal** [comment]
FYI, it's there for jessie, might have a go re-imaging it when i get home...

**Comment by yosifkit** [comment]
Aw :crying_cat_face:, only 3.3 which is not a stable release. But I guess that is some progress.

**Comment by tianon** [comment]
Looks like they've added 3.2 support for `jessie` (http://repo.mongodb.org/apt/debian/dists/jessie/mongodb-org/3.2/main/binary-amd64/)!  I'm working on making a PR now. :+1:
