### ISSUE TITLE
mongorc.js not working in docker

### ISSUE THREAD

**Issue by yangzhaofeng** [docker-library/mongo#462]
I need the following mongorc.js when starting mongodb
```
rs.initiate()
rs.secondaryOk()
```
However, it does not work when I mount it to `/etc/mongorc.js` or `/home/mongodb/.mongorc.js` or in `/docker-entrypoint-initdb.d/`

Where should I mount it? If mongorc.js is disabled, is there any substitution?

**Comment by wglambert** [comment]
What do the `docker logs` show?

Seems like https://github.com/docker-library/mongo/issues/339#issuecomment-485578503
The `docker-entrypoint-initdb.d` scripts run during an initialization period (and only if the database is empty), during which the container is only listening on localhost so trying to initiate a cluster during that period isn't possible as it won't resolve it's own container hostname.

**Comment by yangzhaofeng** [comment]
@wglambert Thanks! I put the script in `/docker-entrypoint-initdb.d` and cleared the databases. Now it works as expected.
