### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by romintomasetti** [docker-library/mongo#473]
Following the changes in https://github.com/docker-library/mongo/commit/791d400b9e84a298356b78db01956d98db973b9d, building the Docker image for MongoDB 4.4 doesn't work because `Error response from daemon: Dockerfile parse error line 83: ARG requires exactly one argument`.

This should be corrected, at least in https://github.com/docker-library/mongo/commit/791d400b9e84a298356b78db01956d98db973b9d#diff-64bdf01b91b9801069c15f8fd273c15306316bc74320059836a839d62307cfae.

**Comment by tianon** [comment]
Can you provide some more detail?  I can't reproduce: :confused:

```console
$ docker build --pull https://github.com/docker-library/mongo.git#:4.4
Sending build context to Docker daemon  29.18kB
Step 1/20 : FROM ubuntu:bionic
bionic: Pulling from library/ubuntu
Digest: sha256:538529c9d229fb55f50e6746b119e899775205d62c0fc1b7e679b30d02ecb6e8
Status: Image is up to date for ubuntu:bionic
 ---> 4eb8f7c43909
...
Step 9/20 : ARG MONGO_PACKAGE=mongodb-org MONGO_REPO=repo.mongodb.org
 ---> Running in 8331bc5611ab
Removing intermediate container 8331bc5611ab
 ---> 897879f53032
Step 10/20 : ENV MONGO_PACKAGE=${MONGO_PACKAGE} MONGO_REPO=${MONGO_REPO}
 ---> Running in 3bcec62aa4ba
Removing intermediate container 3bcec62aa4ba
 ---> 6789f9ce0727
Step 11/20 : ENV MONGO_MAJOR 4.4
 ---> Running in 841b2982cdda
Removing intermediate container 841b2982cdda
 ---> 9c3041177f12
Step 12/20 : RUN echo "deb http://$MONGO_REPO/apt/ubuntu bionic/${MONGO_PACKAGE%-unstable}/$MONGO_MAJOR multiverse" | tee "/etc/apt/sources.list.d/${MONGO_PACKAGE%-unstable}.list"
 ---> Running in e5687ba0221b
deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
Removing intermediate container e5687ba0221b
 ---> 7b31d6744be8
...
 ---> 66ede2bb496e
Step 20/20 : CMD ["mongod"]
 ---> Running in c92f0c962b78
Removing intermediate container c92f0c962b78
 ---> d6341af03a5c
Successfully built d6341af03a5c
```

**Comment by romintomasetti** [comment]
Well, it's weird that it works for you because clearly from https://github.com/docker-library/mongo/blob/6377a52b25e9b7790c7082fbdc3f587069255d27/4.4/Dockerfile#L83, there are 2 `ARG` on the same line and that doesn't work on my side. From the Docker documentation https://docs.docker.com/engine/reference/builder/#arg, it seems that `ARG` is only one value at a time.

**Comment by tianon** [comment]
What's your Docker version?

**Comment by romintomasetti** [comment]
> What's your Docker version?

19.03.8, not the newest I agree. But not that old :smiley:

**Comment by yosifkit** [comment]
This seems to only be a limitation when using older buildkit for `docker build`; regular `docker build` works fine and a newer buildkit also works fine (https://github.com/moby/buildkit/pull/1692).
