### ISSUE TITLE
Image Mongo 5.0-rc1

### ISSUE THREAD

**Issue by vinigracindo** [docker-library/mongo#477]
Hello, I would like to get an image for mongo 5.0-rc1.

To create a 5.0 version do I have to use apply-templates.sh?

Thank you.

**Comment by yosifkit** [comment]
RC's should be automatic now. :tada: Fixed by https://github.com/docker-library/mongo/pull/476

`versions.sh` finds and adds new/updated versions to `versions.json`
`apply-templates.sh` takes `versions.json` and applies those values using the Dockerfile templates files to each version.
