### ISSUE TITLE
Add the volume in the instructions!!!

### ISSUE THREAD

**Issue by dada513** [docker-library/mongo#480]
I was moving my data to a different machine. Copied the home folder and was expecting that the mongodb would save its data inside its docker compose folder. But no! The instructions didnt add volumes. I think they really should. I lost ALL of my data because of this stupid mistake. ALL of it.

**Comment by wglambert** [comment]
The default behavior for this image is that data is persisted in a Docker [named volume](https://docs.docker.com/storage/volumes/)
https://github.com/docker-library/mongo/blob/38acbaea2f25cd148c28a69bddf6f51c466babf1/4.4/Dockerfile#L113


Named volumes are kept at `/var/lib/docker/volumes/` to find the one your container is using check the `docker inspect` for volumes
```console
$ docker run -d --rm --name mongo mongo
ae888e1615db1a3538090340a00bd5af0256366cec989ed069d5a8fc4bc95fea

$ docker inspect mongo | grep -A 2 -i volume
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
--
                "Type": "volume",
                "Name": "2073deb048535010fafa4288aa6bd4d8e49e3e7a1bb023a4334a5a70a6a0686a",
                "Source": "/var/lib/docker/volumes/2073deb048535010fafa4288aa6bd4d8e49e3e7a1bb023a4334a5a70a6a0686a/_data",
                "Destination": "/data/configdb",
                "Driver": "local",
--
                "Type": "volume",
                "Name": "27fb95886133cb4037f53bf336b53db9d862b977d397d5d04e7fe7b18d6ed708",
                "Source": "/var/lib/docker/volumes/27fb95886133cb4037f53bf336b53db9d862b977d397d5d04e7fe7b18d6ed708/_data",
                "Destination": "/data/db",
                "Driver": "local",
--
            "Volumes": {
                "/data/configdb": {},
                "/data/db": {}

$ ls /var/lib/docker/volumes/27fb95886133cb4037f53bf336b53db9d862b977d397d5d04e7fe7b18d6ed708/_data
WiredTiger                           diagnostic.data
WiredTiger.lock                      index-1-5311923285655401540.wt
WiredTiger.turtle                    index-3-5311923285655401540.wt
WiredTiger.wt                        index-5-5311923285655401540.wt
WiredTigerHS.wt                      index-6-5311923285655401540.wt
_mdb_catalog.wt                      journal
collection-0-5311923285655401540.wt  mongod.lock
collection-2-5311923285655401540.wt  sizeStorer.wt
collection-4-5311923285655401540.wt  storage.bson
```

**Comment by yosifkit** [comment]
We do mention data storage; it is just not part of the example compose file: https://github.com/docker-library/docs/tree/970b24c95b5c3c2b5214ffd8ff3b846248641341/mongo#where-to-store-data

**Comment by dada513** [comment]
yes it is mentioned in the github repository but on the docker page theres no mention about it. The old machine was being replaced and the backup I had was of the home folder (where all the other images stored their data with volume).
