### ISSUE TITLE
Feature Request: Docker Image for MongoDB Enterprise

### ISSUE THREAD

**Issue by sigonzal3** [docker-library/mongo#482]
Hello,

Have the team considered hosting MongoDB Enterprise Docker images on Docker Hub, GitHub Packages or any other public registry?

On Docker Hub, the only images available are the community edition. For the enterprise edition, the [instructions available](https://docs.mongodb.com/manual/tutorial/install-mongodb-enterprise-with-docker/) require manual build.

I'm testing out [MongoDB Client Side Field Encryption](https://docs.mongodb.com/manual/core/security-client-side-encryption/), and this feature is only available on MongoDB enterprise. It would be great to have official images available for local development, so I can test locally using Helm and Minikube. For production, I'm using MongoDB Atlas.

**Comment by tianon** [comment]
I think https://docs.mongodb.com/manual/tutorial/install-mongodb-enterprise-with-docker/ is really relevant here (we're not directly affiliated with MongoDB, and have no plans to publish an image of their Enterprise product).

**Comment by tianon** [comment]
I guess I should point out what I think is the most relevant bit, sorry: :sweat_smile:

> This procedure uses Docker's official mongo image, which is supported by the Docker community and not MongoDB.

**Comment by yosifkit** [comment]
It looks like they do host enterprise images on quay.io. See the "Offline using Helm and Docker" tab from their ["Install the MongoDB Enterprise Kubernetes Operator"](https://docs.mongodb.com/kubernetes-operator/stable/tutorial/install-k8s-operator/).

```console
docker pull quay.io/mongodb/mongodb-enterprise-operator:<op-version>; \
docker pull quay.io/mongodb/mongodb-enterprise-database:<db-version>; \
docker pull quay.io/mongodb/mongodb-enterprise-ops-manager:<om-version>; \
docker pull quay.io/mongodb/mongodb-enterprise-appdb:10.2.15.5958-1_4.2.11-ent; \
docker pull quay.io/mongodb/mongodb-enterprise-init-ops-manager:1.0.3; \
docker pull quay.io/mongodb/mongodb-enterprise-init-appdb:1.0.6; \
docker pull quay.io/mongodb/mongodb-enterprise-init-database:1.0.2;
```
