### ISSUE TITLE
[Request] Include MongoSH

### ISSUE THREAD

**Issue by LeeThompson** [docker-library/mongo#497]
For the docker container it would be *really* helpful if the image came with mongosh installed.  

My MongoDB instance is in a private docker network so to prepare for mongodb updates I setup a separate container with mongosh and link it.  It's time consuming and it would be nice if I could just connect a terminal to the mongodb image and start mongosh within it to issue the commands needed to prep and perform version upgrades.

**Comment by tianon** [comment]
I'm a bit confused here -- we do? :confused:

```console
$ docker pull mongo
Using default tag: latest
latest: Pulling from library/mongo
Digest: sha256:71348de35c2edef847906cbcf175d12e15244cdc37fc4ae5661fde361f4e4893
Status: Image is up to date for mongo:latest
docker.io/library/mongo:latest

$ docker run --rm mongo mongosh --version
1.0.7
```

**Comment by LeeThompson** [comment]
Was this recent?  It's not in my image but I'm not on the latest branch.
If it's in it now though, yay!

**Comment by tianon** [comment]
It's definitely been in the 5.0 builds since some of the early 5.0 RCs.

**Comment by LeeThompson** [comment]
Ah I'm on 4.4.6 still.   I upgrade cautiously since I'm running the RocketChat house of cards.
