### ISSUE TITLE
too many open files error on start up

### ISSUE THREAD

**Issue by 3choBoomer** [docker-library/mongo#50]
I am getting the following error on startup of my docker container:
```
2015-08-04T17:43:42.693+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=6G,session_max=20000,eviction=(threads_max=4),statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),checkpoint=wait=60,log_size=2GB),statistics_log=(wait=0),
2015-08-04T17:43:54.351+0000 E STORAGE  [initandlisten] WiredTiger (24) [1438710234:351024][1:0x7fe4f3f20b60], file:collection-2071-2488305337711612400.wt, session.open_cursor: /
data/db/collection-2071-2488305337711612400.wt: Too many open files
2015-08-04T17:43:54.351+0000 I -        [initandlisten] Invariant failure: ret resulted in status UnknownError 24: Too many open files at src/mongo/db/storage/wiredtiger/wiredtig
er_session_cache.cpp 78
2015-08-04T17:43:54.375+0000 I CONTROL  [initandlisten]
```

I have verified that the /etc/iniit.d/mongod file is setting the ulimit -n to 64000, but there appears to be no obvious way to override this via a docker command.

Does anyone have any experience with something similar?

**Comment by md5** [comment]
You can't set ulimits from inside the container (and `/etc/init.d/mongod` is ignored in this Docker image since it doesn't use `init`).

You'll want to pass a `--ulimit` flag to your `docker run` command. I just tried to find some docs for it, but it doesn't appear to be documented in the `docker run` docs. It's mentioned in this blog post though: https://blog.docker.com/2015/04/docker-release-1-6/

**Comment by md5** [comment]
Apparently it's documented here: https://docs.docker.com/reference/commandline/run/

**Comment by 3choBoomer** [comment]
Awesome. Thank you @md5

**Comment by md5** [comment]
@3choBoomer Looks like this issue can be closed in that case.

Adding some advice about setting `--ulimit nofile=NNNN` to [the docs for the `mongo` image](https://github.com/docker-library/docs/blob/master/mongo/content.md) might help the next person who runs into this issue. It looks like there are already `ulimit`-related instruction in [the Mongo docs](http://docs.mongodb.org/manual/reference/ulimit/).

**Comment by md5** [comment]
These docs in particular look like a good reference: http://docs.mongodb.org/manual/reference/ulimit/#recommended-ulimit-settings

**Comment by md5** [comment]
It would be interesting if some of those recommended settings could be set in a Dockerfile with a (hypothetical) `ULIMIT` directive.

**Comment by 3choBoomer** [comment]
It appears that the defaults for open files in the docker container are already way larger than the recommended settings:

```
nathan.cooke@mongodb-01:~$ docker exec -i -t mongodb bash
root@9d7ba95c3e71:/# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 55995
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 524288
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

It's very possible that there is a larger issue at play here than the error that was reported.
A reboot solved my issue for the time being, hopefully it won't be an issue in the future.
