### ISSUE TITLE
Add ReplicaSet Environment Variable

### ISSUE THREAD

**Issue by WingsLikeEagles** [docker-library/mongo#501]
The Official image for MongoDB does not incorporate Environment Variables for setting the Replica Set and other important features.  This is an important feature that is missing.

See Bitnami's repackaging of MongoDB for an example.
https://hub.docker.com/r/bitnami/mongodb

They have this and many other important flags and options configurable by Environment Variables.  This is critical to using MongoDB in a more automated easily (i.e. Docker-Compose).

**Comment by tianon** [comment]
See #246 and #339 for several good discussions around replica sets (and the complications involved in setting them up automatically).
