### ISSUE TITLE
Insufficient free space for journal files

### ISSUE THREAD

**Issue by quimrstorres** [docker-library/mongo#51]
I am having the problem mentioned in dockerfile/mongodb#9 and again in docker-library/official-images#281. As suggested in the latter, I opened the issue here.

I am using Mac OS X 10.10.3 with:

```
> boot2docker version
Boot2Docker-cli version: v1.7.1

> docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): darwin/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

> docker info | grep Storage                                                                                                                  
Storage Driver: aufs

> docker-compose logs mongo
mongo_1 | mongod --help for help and startup options
mongo_1 | Sat Aug 15 16:19:02.094 [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db/ 64-bit host=dcdc00ea89ac
mongo_1 | Sat Aug 15 16:19:02.094 [initandlisten] db version v2.4.14
mongo_1 | Sat Aug 15 16:19:02.094 [initandlisten] git version: 05bebf9ab15511a71bfbded684bb226014c0a553
mongo_1 | Sat Aug 15 16:19:02.094 [initandlisten] build info: Linux ip-10-154-253-119 2.6.21.7-2.ec2.v1.2.fc8xen #1 SMP Fri Nov 20 17:48:28 EST 2009 x86_64 BOOST_LIB_VERSION=1_49
mongo_1 | Sat Aug 15 16:19:02.094 [initandlisten] allocator: tcmalloc
mongo_1 | Sat Aug 15 16:19:02.094 [initandlisten] options: {}
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] journal dir=/data/db/journal
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] recover : no journal files present, no recovery needed
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten]
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] ERROR: Insufficient free space for journal files
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] Please make at least 3379MB available in /data/db/journal or use --smallfiles
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten]
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] exception in initAndListen: 15926 Insufficient free space for journals, terminating
mongo_1 | Sat Aug 15 16:19:02.099 dbexit:
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] shutdown: going to close listening sockets...
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] shutdown: going to flush diaglog...
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] shutdown: going to close sockets...
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] shutdown: waiting for fs preallocator...
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] shutdown: lock for final commit...
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] shutdown: final commit...
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] shutdown: closing all files...
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] closeAllFiles() finished
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] journalCleanup...
mongo_1 | Sat Aug 15 16:19:02.099 [initandlisten] removeJournalFiles
mongo_1 | Sat Aug 15 16:19:02.101 [initandlisten] shutdown: removing fs lock...
mongo_1 | Sat Aug 15 16:19:02.101 dbexit: really exiting now
```

I am using the `mongo:2.4` image and the database has very little data. I started the container successfully many times until it started having this problem.

**Comment by yosifkit** [comment]
You are probably running out of hard drive space on the boot2docker vm. This might help clean up untagged images to clear up some space: `docker images --filter dangling=true -q | sort -u | xargs docker rmi`.

**Comment by henriquemoody** [comment]
I tried everything and I had no success until realize that `/mnt/sda1` was full by accessing my boot2docker machine with docker-machine.

Looks like ~~my~~ docker doesn't clean completely the container after I remove them, so there ware still some volumes there.

I end up using this container to clean it up: https://github.com/chadoe/docker-cleanup-volumes and it worked like a charm, I really think this is not a problem to be reported on this projects, despite I still don't get why only the Mongo containers could get this error.

**Comment by yosifkit** [comment]
MongoDB gets this because they pre-allocate very large files for the database.  Use `docker rm -v` to make sure volumes are cleaned up when deleting a container.

**Comment by wattletimber** [comment]
Hi Guys. Help me here i have installed a dockerized mongodb and meteor, and my container is increasing with a gig almost everyday. How can I handle this, see images below for reference. i want to preserve the images.
<img width="1085" alt="screen shot 2016-06-02 at 6 22 40 am" src="https://cloud.githubusercontent.com/assets/19662899/15813032/cf91415c-2bbb-11e6-861c-2c8b9365549e.png">
<img width="748" alt="screen shot 2016-06-06 at 6 43 50 am" src="https://cloud.githubusercontent.com/assets/19662899/15813050/fde88632-2bbb-11e6-9908-08b117732a44.png">

**Comment by wattletimber** [comment]
<img width="652" alt="screen shot 2016-06-01 at 11 06 51 am" src="https://cloud.githubusercontent.com/assets/19662899/15813088/4cb0b32a-2bbc-11e6-8fd5-09e585980286.png">

**Comment by agamrafaeli** [comment]
For me the problem was that I shut down my computer without shutting down the container properly. 

When starting the container an internal problem happened with the mongo. I SSH'ed into the machine and deleted a lock file and then the container started all right for me.

**Comment by puneetakhouri** [comment]
@agamrafaeli Can you kindly elaborate where is the lock file that you mentioned in your post. I SSH'ed into the machine but am not able to track the location of the lock file you mentioned.

**Comment by patrickaroo** [comment]
I'm having the same issue on OSX, Docker Version 1.12.3-beta29.3 (13640), and tutum/mongodb, for what it's worth. The error on docker-compose up was:

db_1 ... ERROR: Insufficient free space for journal files
db_1 ... Please make at least 3379MB available in /data/db/journal or use --smallfiles

Since I'm using the new(ish) Docker app, instead of the old approach, it's a little unclear at first glance how I'll do the rebuild workaround, and restarting the Docker app isn't helping.

**Comment by yosifkit** [comment]
Closing old issue. Feel free to comment on further troubleshooting if you feel this was closed in error or on the solution to help users running into the same problem.

(related lock file issue #62)
