### ISSUE TITLE
Adding port to docker run command

### ISSUE THREAD

**Issue by james-beston** [docker-library/mongo#530]
I was having trouble accessing the Docker image on my Mac as the port (27017) was not bound when I ran the command in the instructions:

`docker run --name some-mongo -d mongo:tag`

Suggest updating instructions to:

`docker run -dp 27017:27017  --name some-mongo -d mongo:tag`

With the updated code I could run `mongosh` without the connection being refused

**Comment by tianon** [comment]
Also, by default, MongoDB doesn't use authentication, so exposing port 27017 outside a Docker network or something similarly private is a pretty dangerous configuration. :see_no_evil:
