### ISSUE TITLE
[Security] Auth disabled if some environment variables are not set

### ISSUE THREAD

**Issue by Dr-Shadow** [docker-library/mongo#533]
Hello,

I have a security concern about this line :

> https://github.com/docker-library/mongo/blob/master/5.0/docker-entrypoint.sh#L249

It seems auth is disabled if I don't keep these environment variables MONGO_INITDB_ROOT_USERNAME / MONGO_INITDB_ROOT_PASSWORD in my docker-compose.yml.
In my case, these variables were provided from an overriding docker-compose.yml file like this :
`docker-compose -f <file.yml> -f <second_file.yml> <command>`

These variables should be present during initialization and that makes sense but not on later runs (once database is initialized, we should be able to remove these environment variables)

That's why a few people document to set this flag on the web but this is not documented in the Dockerhub README :
`command: [--auth]`

This means that if we provide MONGO_INITDB_ROOT_USERNAME / MONGO_INITDB_ROOT_PASSWORD only during the first start of the Docker service, on later runs the Mongo runs without auth even if an user has been created previously.

--auth flag should not rely only on MONGO_INITDB_ROOT_USERNAME / MONGO_INITDB_ROOT_PASSWORD existence

**Comment by tianon** [comment]
Unfortunately, we can't automatically detect whether or not a user wants authentication enabled unless they tell us in some way (either via the authentication environment variables or via `--auth` on the command line).  I agree that it would probably make sense to add a small note to the image description, likely around those variables that if they are removed, `--auth` is no longer implied and needs to be explicitly specified.

(That documentation is in https://github.com/docker-library/docs/blob/master/mongo/content.md)

**Comment by Dr-Shadow** [comment]
Why not using a specific environment variable to enable/disable authentication as an option in addition to --auth on command line ?

This would make things more explicit and without the need to include the environment variables used for database initialization to keep auth enabled.

**Comment by yosifkit** [comment]
We do not add environment variables for arguments to `mongod`, since users can just pass the flag.

**Comment by tianon** [comment]
Closing as this is (unfortunately) working as designed :heart:
