### ISSUE TITLE
Cannot pull mongo

### ISSUE THREAD

**Issue by vorobey** [docker-library/mongo#54]
Hello, i'm need some help. Trying pull mongo, but always get problems with HTTP 400 Error
```
Pulling mongodb (mongo:3.0)...
Pulling repository docker.io/library/mongo
278372cb22b2: Pulling image (3.0) from docker.io/library/mongo, endpoint: https:278372cb22b2: Error pulling image (3.0) from docker.io/library/mongo, endpoint: 278372cb22b2: Error pulling image (3.0) from docker.io/library/mongo, HTTP code 400e96c112fc: Download complete
430e6598f55b: Error pulling dependent layers

Error pulling image (3.0) from docker.io/library/mongo, HTTP code 400
```

Tried get other tag (2.6 for example), but got same error. Tried change DNS to 8.8.8.8 or reinstall docker, but it didn' help. Even tried install only docker on clear computer and pull only mongo

**Comment by vorobey** [comment]
Hm, this morning pulling was succefull

**Comment by yosifkit** [comment]
This usually means a [problem with Docker Hub](https://twitter.com/dockerstatus/status/645548753978396672). If you don't see anything on https://status.docker.com/ or https://twitter.com/dockerstatus, I would suggest opening a ticket with support@docker.com or tweeting at dockerstatus.  We only maintain the images and do not have control or access to the distribution system (Docker Hub).
