### ISSUE TITLE
MongoDB 5.x Docker image is missing

### ISSUE THREAD

**Issue by infa-ysokolov** [docker-library/mongo#546]
Can we get MongoDB 5.x dockerized as well?

**Comment by wglambert** [comment]
The latest 5.x image is 5.0.9 https://github.com/docker-library/official-images/pull/12558
https://github.com/docker-library/docs/tree/master/mongo#simple-tags

Do you mean the rapid releases? https://github.com/docker-library/mongo/pull/516

**Comment by infa-ysokolov** [comment]
@wglambert yes. We understand that there is no official support for on-prem, and we're using Atlas, but our CI is Docker-based, so we can't automate testing of the features released in a rapid release without a Docker image.

**Comment by yosifkit** [comment]
Unfortunately, since the rapid releases are not upstream supported we chose not to publish them.  The Dockerfile could work by updating the three relevant environment variables for a local image build: `MONGO_PACKAGE=mongodb-org-unstable`, `MONGO_MAJOR=development`, and `MONGO_VERSION=5.3.1`.
