### ISSUE TITLE
Mongo 4.4.15 docker image not available on docker hub

### ISSUE THREAD

**Issue by cdavid15** [docker-library/mongo#548]
I just tried pulling mongo:4.4.15 expecting that 4.4.15 released 21st June would have been available but it appears the latest patch version of 4.4.x has not been applied yet.

I initially reached out to MongoDB via Twitter and they told me they don't maintain the image and pointed me here.

Is there any indication of when this will be published?

**Comment by tianon** [comment]
Hopefully this is something the MongoDB maintainers want to fix, but I guess in the interim we probably need a workaround in our tests? :grimacing:

**Comment by tianon** [comment]
Workaround applied in https://github.com/docker-library/official-images/pull/12745, version updated in 1d2a1b08bd24135e9ce8ecec55b27cfc5fb6f0a1, proper update PR up at https://github.com/docker-library/official-images/pull/12747 :+1:
