### ISSUE TITLE
convert mongo standalone to replicaset in docker

### ISSUE THREAD

**Issue by scne** [docker-library/mongo#55]
I've a Docker instance with mongo. This run as standalone configuration. Now I would to change `entrypoint.sh` to run itself as replica set following [official guide standalone to replica set] (http://docs.mongodb.org/manual/tutorial/convert-standalone-to-replica-set/)

Any suggestion? I've tried to manually setting up entrypoint.sh but it have crashed my container.

**Comment by yosifkit** [comment]
As far as I can tell, you shouldn't need to change the entrypoint.  As long as you have the data accessible to a new container, just run it with the `--replSet` flag:
```console
$ docker run -d --name some-mongo -v /path/to/my/data/dir:/data/db mongo --replSet rs0
$ # then connect to it with a mongo shell:
$ docker run -it --link some-mongo:mongo --rm mongo mongo mongo/myDatabase
> rs.initiate()
```

**Comment by scne** [comment]
Great!
