### ISSUE TITLE
Create MongoDB 6.0 Docker image

### ISSUE THREAD

**Issue by nikolashermann** [docker-library/mongo#552]
MongoDB 6.0 is GA: https://www.mongodb.com/blog/post/mongodb-6-0-now-available https://github.com/mongodb/mongo/releases/tag/r6.0.0

There should be a docker image for it.

**Comment by yosifkit** [comment]
Opened PR #553.

**Comment by minhhungit** [comment]
any news please

**Comment by sameerbhadouria** [comment]
Bump on this as well!

**Comment by DheerendraTomar** [comment]
Any update on docker image??

**Comment by moisesbites** [comment]
Any Update for Linux?

**Comment by tianon** [comment]
See discussion in https://github.com/docker-library/mongo/pull/553 :wink:
