### ISSUE TITLE
mongo:3.0.6 will not work on circleci

### ISSUE THREAD

**Issue by bitglue** [docker-library/mongo#56]
mongo:3.0.6 will not run within the Docker environment on CircleCI. For a minimal example, see:

  - https://circleci.com/gh/bitglue/mongo-gosu-bug/2
  - https://github.com/bitglue/mongo-gosu-bug

It appears the issue is that [gosu attempts to fchown all the open FDs](https://github.com/tianon/gosu/commit/75150acc2b2baf01a8ce5b106f226464f3c737e0), and for whatever reason on CircleCI this is not possible.

I'm still looking into exactly what FDs these are, but it would seem reasonable to me there might be any number of FDs a process may have open which are not fchownable.

**Comment by kimh** [comment]
I haven't looked this issue closely, but CircleCI is running docker inside LXC container and the chown of FD in LXC container seems restricted.

**Comment by bitglue** [comment]
I wonder what the motivation for the change to gosu was, anyway. I'd think CircleCI aside, not all filesystems support chown (or any concept of ownership at all), and there's not even a guarantee that a file descriptor is a regular file anyway: it may be a socket, or a pipe, etc. It looks like `gosu` might handle the pipe and socket cases by ignoring `EBADF`, but the comment suggests the reasoning is something else.

Besides, changing my file permissions is not a behavior I'd expect in a tool for changing users, nor does it appear to be documented anywhere. I wouldn't be surprised if there are a few security problems introduced by this change.

**Comment by dominikmueller** [comment]
Hi, i think i'm having a similar problem:

i try to run a rocketchat server with docker with these two commands:
```
docker run --name db -d mongo mongod --smallfiles
docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://localhost --link db:mongo -d rocket.chat
```

the creation of the mongodb server fails with following log:
```
error: failed switching to "mongodb": fchown fds permission denied
```

I'm running CentOS 7 with Docker version 1.7.1, build 446ad9b/1.7.1

Can someone help me getting it up and running?

**Comment by bitglue** [comment]
@dominikmueller for now you can work around the issue by using the previous version of the mongo image:

    docker run --name db -d mongo:3.0.5 mongod --smallfiles

**Comment by dominikmueller** [comment]
Awesome! :) Many Thanks @bitglue - worked with 3.0.5 :+1:

**Comment by bitglue** [comment]
Looks like Docker Hub has been updated and our builds are working now. Thanks for the prompt fix!
