### ISSUE TITLE
bash mongo command not found

### ISSUE THREAD

**Issue by waywayyang** [docker-library/mongo#560]
while I enter the mongo container,I got this error. how to solve it?

**Comment by wglambert** [comment]
https://www.mongodb.com/docs/manual/release-notes/6.0-compatibility/#legacy-mongo-shell-removed

Try `mongosh` instead

**Comment by REALSTEVEIG** [comment]
Thanks, this solved my problem.

**Comment by clarensromeus** [comment]
there's nowhere else out to find help better on the dilemma, i owe you one Dev
