### ISSUE TITLE
Not able to access container shell

### ISSUE THREAD

**Issue by ShubhamDalal** [docker-library/mongo#561]
Tried
`$ docker exec -it some-mongo bash`
`root@40534b22942a:/# mongo`

Response
`bash: mongo: command not found`
`root@40534b22942a:/#`

**Comment by gkwan-ibm** [comment]
encountered same problem

**Comment by wglambert** [comment]
https://www.mongodb.com/docs/manual/release-notes/6.0-compatibility/#legacy-mongo-shell-removed

Try `mongosh`
