### ISSUE TITLE
mongosh : execute js script on a bind mounted volume

### ISSUE THREAD

**Issue by stockersky** [docker-library/mongo#564]
My aim is to execute a script located in a local git repository.

image :  mongo:6.0.1-focal   (d34d21a9eb5b)
Using MongoDB:          4.0.0                                                                                                                
Using Mongosh:          1.5.4 

I execute the container this way :

```
docker run -it \
--mount src=/c/Users/myuser/PROJECTS/my-git-project,target=/project,type=bind \
--rm mongo mongosh \
"mongodb://***************************************"  \
"/project/test/test.js"
```

Error is :
```
Loading file: C:/Users/my-user/AppData/Local/Programs/Git/project/test/test.js
Error: ENOENT: no such file or directory, open '/C:/Users/my-user/AppData/Local/Programs/Git/project/test/test.js'
```

When opening a shell on the container, I can verify that the mountpoint `/project` is populated and contain the simple script and want to execute

However, it works if I execute it interactively :

```
docker run -it \
--mount src=/c/Users/myuser/PROJECTS/my-git-project,target=/project,type=bind \
--rm mongo mongosh \
"mongodb://***************************************"  \
```

```
globaldb [primary] test> load("/project/script/test.js")
The mongodb version is: 4.0.0
true
```

Why does it prefix this windows path `/C:/Users/my-user/AppData/Local/Programs/Git` to the mountpoint` ?

**Comment by wglambert** [comment]
Are you using Docker Desktop? No idea why it'd be modifying the path like that but it's not something the image is doing.

There are Windows variants for this image that might suit your environment better https://github.com/docker-library/docs/tree/master/mongo#shared-tags

**Comment by yosifkit** [comment]
>```
> Loading file: C:/Users/my-user/AppData/Local/Programs/Git/project/test/test.js
>```

That looks kind of like git-for-windows Bash auto adjusting paths; try `"//project/test/test.js"`
