### ISSUE TITLE
I as a Mongo user can set uid and gid as arguments while building a Mongo Docker image

### ISSUE THREAD

**Issue by aivinog1** [docker-library/mongo#579]
Hello! 

It would be cool to have the ability to set up my uid and gid (numbers) as arguments. Because in my system `999` already belongs to another system.

**Comment by tianon** [comment]
You should be able to run with any `--user` (or `USER` in a `Dockerfile`) value you choose, as long as you make sure the permissions on `/data/db` are pre-set appropriately for the user you choose to access it.
