### ISSUE TITLE
Documentation query/request

### ISSUE THREAD

**Issue by simonmcnair** [docker-library/mongo#592]
I wondered if it would be a good idea in the docker page to advise of special characters that should not make up the password of a user as I recently got caught out by needing to use escape characters in bash in order to login on the command line.

**Comment by tianon** [comment]
While this is unfortunate, it's not exactly specific to MongoDB (or even more particularly, running MongoDB inside Docker using this specific Docker image), so I don't think it's very appropriate for us to use our limited image description space describing it. :sweat_smile:
