### ISSUE TITLE
Initialization scripts in docker-entrypoint-initdb.d/ not working for Windows containers

### ISSUE THREAD

**Issue by twity1337** [docker-library/mongo#604]
In the documentation for the container image in section "Initializing a fresh instance" it is described how to initialize the image with custom JavaScript files. Those can be located in a `docker-entrypoint-initdb.d` directory.

However, this feature is not yet supported nor working on windows.
Instead just a [todo-comment](https://github.com/docker-library/mongo/blob/master/6.0/windows/windowsservercore-ltsc2022/Dockerfile#L62) was added to the corresponding Dockerfile.

If the feature is not added yet, I think, it would be good to have a note mentioning this in the documentation.

**Comment by twity1337** [comment]
So far as I know, the environment variables "MONGO_INITDB_ROOT_USERNAME" and "MONGO_INITDB_ROOT_PASSWORD" also don't show any effect in the Windows image.

**Comment by tianon** [comment]
https://github.com/docker-library/mongo/issues/291#issuecomment-410813034

**Comment by twity1337** [comment]
Thanks for your reply.

> If the feature is not added yet, I think, it would be good to have a note mentioning this in the documentation.

I created an issue for changing the docs: https://github.com/docker-library/docs/issues/2271

Issue closed.
