### ISSUE TITLE
Warning shows up in mismatch version in aarch64

### ISSUE THREAD

**Issue by mathric** [docker-library/mongo#609]
When trying to run docker in version 4.4 or 4.2. The following error shows up
pull the image using `sha256:1f597c605bdc2a244e7b58ab9f14abcadf4905c2efe6dbf7b21e7b7267e3bbd1` also have same result.
![image](https://user-images.githubusercontent.com/20289754/222254243-1be45da4-386c-4c2a-9229-5504b351362a.png)

but it doesn't shows up when run in version 3.6

---
The following is the cpu and distro info
![image](https://user-images.githubusercontent.com/20289754/222253640-482d6a03-b0b6-4145-be2f-27094073659a.png)

![image](https://user-images.githubusercontent.com/20289754/222253995-7d6509b5-7992-498b-868a-ab6407e08ad6.png)

**Comment by yosifkit** [comment]
> This applies the warning across all versions, with the justification that affected users might want to know sooner than post-5.0-upgrade that their containers will not be starting successfully.
>
> \- #491 (and the follow up for `arm64v8` #511)

`3.6` is no longer a supported release, so it did not get the warning message. The warning message is there to let you know that newer versions will likely not work on your host CPU architecture (see the provided links); it is not an error.  Your listed processor is a `Cortex-A72` and according to the ["List of ARM Processors"](https://en.wikipedia.org/wiki/List_of_ARM_processors), it is an `ARMv8-A` which means it is not `ARMv8.2-A or higher` and so it is being correctly detected as unable to run MongoDB 5.0+.

Here is the detection code:

https://github.com/docker-library/mongo/blob/4bde9c88f7479d4f0281bc3793d0eabb22ec7e6b/docker-entrypoint.sh#L40-L52

**Comment by mathric** [comment]
Thanks for the reply. Since the container also stop immediately after start up I thought it wasn't just warning and it's about why the container stop. 
So I think the issue will become the container can't start in version 4.4 or 4.2 in that environment without other error message.

**Comment by yosifkit** [comment]
It seems that the minimum has increases for older versions now too: https://jira.mongodb.org/browse/SERVER-71772 :disappointed:. Seems not great for them to do this on older releases.

**Comment by mathric** [comment]
okey, thanks for the help. Will try to get another enviroment for this.
