### ISSUE TITLE
Failed to start mongo service using systemd

### ISSUE THREAD

**Issue by PHXA** [docker-library/mongo#633]
I want to set up an ssh server in mongo.
I used sytemd to set it up. In that configuration, I used ExecStart=docker-entrypoint.sh mongod.
However, it fails to start the mongo service.
I thought it was an environment variable problem, but it seems not.
I don't understand everything that is done in docker-entrypoint.sh. Do you have any ideas?
BTW, if I run docker-entrypoint.sh mongod on the container and restart Systemd, it seems to start up fine. So, thinking that the environment variable might be the cause, I tried writing the printenv output from the build to a file and configuring Systemd to use that as the environment variable, but that didn't work. Perhaps the folder or file is not being created due to permission issues.

I have a further question: I wrote out to a /my.sh of bash file as ```docker-entrypoint.sh mongod & service start ssh;``` and configured it to run with PID1(CMD /my.sh), but the init.db migration does not work. Why does the init.db migration not work? Does docker-entrypoint.sh mongod have to be PID1?

**Comment by tianon** [comment]
I'm sorry, but running with `systemd` is not really a configuration we're prepared to support. :sweat_smile:

If you want to continue, I'd suggest running with `docker-entrypoint.sh` as part of your `ExecStart` just like running the container directly would (ie, `ExecStart=/path/to/docker-entrypoint.sh mongod`) which should _mostly_ do what you're looking for (but again, stressing that you're not running in a configuration that we feel like we can reasonably support :see_no_evil:).
