### ISSUE TITLE
How to create a Mongo Docker Image with default collections and data?

### ISSUE THREAD

**Issue by felipeplets** [docker-library/mongo#64]
Anyone here available to help on this quest: [How to create a Mongo Docker Image with default collections and data?](http://stackoverflow.com/questions/33558506/how-to-create-a-mongo-docker-image-with-default-collections-and-data)

**Comment by yosifkit** [comment]
There is a volume defined in [`/db/data`](https://github.com/docker-library/mongo/blob/8b9f19b2dfa7a2d90e2c4152ca33c8879a88c872/3.0/Dockerfile#L41) so that directory will not get saved in the resulting image (https://docs.docker.com/engine/userguide/dockervolumes/#data-volumes).

**Comment by felipeplets** [comment]
@yosifkit thanks for pointing this out. Was not aware of how volume works in Docker.
I will try to mount a different volume for my own db files.
