### ISSUE TITLE
Any dis-benefit to wrapping Mongo within Supervisor?

### ISSUE THREAD

**Issue by viztastic** [docker-library/mongo#65]
I am willing to put together a pull request, but I wanted to explore if there is a reason why this might not be a good idea,

I have been wrapping Mongo in supervisor and running my Docker in this way:

```
FROM ubuntu:14.04
RUN apt-get update -y && apt-get install -y wget
RUN apt-get install -y supervisor
RUN mkdir -p /var/log/supervisor
RUN mkdir -p /data
RUN mkdir -p /logs
RUN cd /opt && wget -nv http://fastdl.mongodb.org/linux/mongodblinux-x86_64-2.6.5.tgz
RUN cd /opt && tar -xvzf mongodb-linux-x86_64-2.6.5.tgz
ADD mongo.conf /opt/mongodb-linux-x86_64-2.6.5/mongo.conf
ADD supervisor.conf /etc/supervisor/conf.d/supervisor.conf
EXPOSE 27017
CMD "/usr/bin/supervisord"

```

The benefit being that supervisor will restart Mongo if it ever crashed and leave a trail of logs about the process as well.

Any reason why this is a bad idea? I'd be happy to create a pull request and share it with the community.

Also for reference, this is something I have been doing based on https://github.com/InconceivableDuck/Nodevember's presentation, it's been working great for me.

**Comment by tianon** [comment]
I'm not sure I understand what value this adds over Docker's own process supervision -- can you elaborate?  I run with `--restart=always`, and Docker keeps track of all the logs for me even across restarts (`docker logs my-mongo`), so I'm not quite tracking what supervisord adds besides another process doing the same thing? :confused:

**Comment by Avagenzo** [comment]
I've done this recently in order to have multiple processes in one container: [Running mongodb container managed by supervisor](https://stackoverflow.com/questions/65340333/running-mongodb-docker-container-managed-by-supervisor/65341124#65341124).
