### ISSUE TITLE
Incorrect initial password because of invalid behaviour of _js_escape

### ISSUE THREAD

**Issue by Ckram** [docker-library/mongo#654]
While initializing a new container with INITDB_ROOT_PASSWORD, if it contains special bash character like `!3` 
It calls ` _js_escape` to escape invalid URL character, but it does not escape `invalid` bash characters

When calling _js_escape with this password `foo!3bar` it returns me a wrong password something like
`foomongosh --helpbar`

**Comment by tianon** [comment]
I can't seem to reproduce: :see_no_evil: (can you provide more details?)

```console
$ docker run -it --rm --env MONGO_INITDB_ROOT_USERNAME=foo --env MONGO_INITDB_ROOT_PASSWORD='foo!bar' --name mongo mongo
...
admin> db.createUser({
... user: "foo",
... pwd: "foo!bar",
... roles: [ { role: 'root', db: "admin" } ]
... })
...
```

**Comment by Ckram** [comment]
Oh actually my bad, it was mongosh that got me wrong when not escaping some characters, I'll close the issue
`mongosh mongodb://foo:foo!3bar@localhost:27017/?authMechanism=DEFAULT`
