### ISSUE TITLE
PGP KEYS expired for Mongodb v3.6

### ISSUE THREAD

**Issue by KavithaVarughese** [docker-library/mongo#658]
PGP KEYS expired in the dockerfile and it is impossible to build for Mongodb v3.6
Please update the PGP KEYS

`gpg: Signature made Tue 16 Mar 2021 09:57:14 AM PDT
gpg:                using RSA key 58712A2291FA4AD5
gpg: Good signature from "MongoDB 3.6 Release Signing Key <packaging@mongodb.com>" [expired]
gpg: Note: This key has expired!`

**Comment by KavithaVarughese** [comment]
Is this version no longer supported ?

**Comment by yosifkit** [comment]
3.6 has been end of life since April 2021. It was removed in https://github.com/docker-library/mongo/commit/77e66571efd350467bc552ad80f127837e1af726.
