### ISSUE TITLE
Error reading config file: Permission denied

### ISSUE THREAD

**Issue by vincebowdren** [docker-library/mongo#66]
When I try to start a mongo container with a config file specified, it throws an error: 

> Error reading config file: Permission denied

Setup: I am running as the user 'docker', who has the following file in their home directory:

    -rw-rw-r-- 1 docker docker 364 Nov 25 01:12 mongod.conf

I want to make the mongod process start up with the config settings from this file; so my run command is, defined in a shell file, this:

    docker run --name insight_mongo1 \
    -v /data:/data/db -v /log:/log \
    -v /var/run/mongodb:/var/run/mongodb \
    -v /home/docker:/made/up/location \
    -p 27017:27017 \
    -d mongo:3.1 --smallfiles --replSet "repset" \
    --config /made/up/location/mongod.conf

I have mapped the location of the config file so the process running in the docker container will be able to access it. But when I run the container, it fails with this error:
> 2015-11-24T17:13:44.874953724Z Error reading config file: Permission denied
> 2015-11-24T17:13:44.874998435Z try 'mongod --help' for more information

I have confirmed that the config file *should* be available in the container, by removing the `--config` line from the run command – in this setup, it starts the container successfully, and I can run a bash shell within it and access the file without problems, for example like this:
`cat /made/up/location/mongod.conf` 

Has anybody else managed to get this working at all? If so, is there some crucial difference in the setup?

Appendix: the server is running linux on AWS v2015.03.

**Comment by yosifkit** [comment]
When the mongo image starts `mongod`, it sets it to run as the user `mongodb` (https://github.com/docker-library/mongo/blob/956574dea803f6f395856215e448ef52f8af2430/3.0/docker-entrypoint.sh#L16).  The config file and the path to it will need to be accessible by the `mongodb` user (which is `999` in the container).  It could be the permissions of your home directory; you could try just bind mounting the config file directly: `-v /home/docker/mongod.conf:/made/up/location/mongod.conf`.

**Comment by vincebowdren** [comment]
Bind mounting the config file itself has got it working, thanks yosifkit.
