### ISSUE TITLE
7.0.7 tag is missing linux/arm64 image

### ISSUE THREAD

**Issue by motoki317** [docker-library/mongo#679]
Hello,

I noticed that, Docker image tag `7.0.7` and `7.0.7-jammy` (and some others I may have overlooked) are missing images for `linux/arm64` architecture, which is usually present in tags like `7.0.6`.

This makes the image unable to be pulled on the linux/arm64 machines using those tags.

Relevant URLs:
- https://hub.docker.com/_/mongo/tags
- https://hub.docker.com/layers/library/mongo/7.0.7/images/sha256-5af155ed5b41f856dc214e16fd30f666fc1a07ad8fed454b3e0f009b4bd49ff6?context=explore
- https://hub.docker.com/layers/library/mongo/7.0.7-jammy/images/sha256-5af155ed5b41f856dc214e16fd30f666fc1a07ad8fed454b3e0f009b4bd49ff6?context=explore
- https://hub.docker.com/layers/library/mongo/7.0.6/images/sha256-3a023748ee30e915dd51642f1ef430c73c4e54937060054ca84c70417f510cc5?context=explore

**Comment by yosifkit** [comment]
Thats for the issue. It looks like the amr64v8 builder was failing to output the image for mongo 7.0.7; I have cleared the problem and it should be up soon.
