### ISSUE TITLE
security issues with stdlib

### ISSUE THREAD

**Issue by logidru** [docker-library/mongo#697]
I just installed the latest harbor registry today with (2.11.0 rc2) in order to test the SBOM feature. I noticed that trivy is reporting much more vulnerabilites (v0.51.2) than on our regular registry (v0.50.1). Acutally i dont understand why there is a diff.

But all these cves are related to the package 'stdlib' that seems to be really there according sbom (related to GOSU). It this really an issue?

the cves are shown on all the latest jammy based images, 5.0.26, 6.0.15, 7.0.11, 8.0.0-rc6
![image_cves](https://github.com/docker-library/mongo/assets/71891248/16da597e-9074-43ee-8e50-8813c587a2b2)
![images_overview](https://github.com/docker-library/mongo/assets/71891248/f3228ad5-2152-48d5-b082-3e35b812aae7)
![sbom_stdlib](https://github.com/docker-library/mongo/assets/71891248/dfee7bb4-7fea-4aef-87c1-88c089636176)

**Comment by whalelines** [comment]
The CVEs associated with `gosu` are false positives. See https://github.com/tianon/gosu/blob/master/SECURITY.md . https://github.com/docker-library/faq?tab=readme-ov-file#why-does-my-security-scanner-show-that-an-image-has-cves may also be helpful.

**Comment by logidru** [comment]
thx for clarification....
