### ISSUE TITLE
How to get the password if it's not in the logs?

### ISSUE THREAD

**Issue by JulianKingman** [docker-library/mongo#70]
I'm looking at the mongo logs, but I don't see where it set up the password for the database. Anyway I can get it via SSH or anything like that? Will I need to redeploy it and specify a password?

**Comment by tianon** [comment]
This container is just MongoDB with the default configuration, so there's
no SSH or authentication -- if you need to access the container after it's
started up, the easiest ways to do so are either to use "docker run --link"
or "docker exec".

**Comment by JulianKingman** [comment]
Thanks! Then how do I get the password?

**Comment by JulianKingman** [comment]
Background: I want to connect via Robomongo, so I need to get the authentication details, which as far as I know, are generated at random and are usually output by the container logs.

**Comment by yosifkit** [comment]
There is no password or user created automatically.  If you want to turn on authentication then you add `--auth` to the docker run (`docker run -d mongo --auth`), and then you'll need to connect to it via localhost (`docker exec ...`) to create an admin user (https://docs.mongodb.org/manual/tutorial/enable-authentication/).

**Comment by JulianKingman** [comment]
If I have an application linked to the mongo instance, and I add authentication to it, will I need to do something special with the application, or would it continue to work?

**Comment by tianon** [comment]
You'd probably have to configure the application to use authentication when
it connects, but I'll be the first to admit I haven't played much with
authentication (since it's not on by default).

**Comment by vincebowdren** [comment]
Yes, you will have to configure the application to use authentication when it connects. Exactly how, depends on your application; in ours we just give it the entire mongodb url like this:
```-e MONGO_URI=mongodb://11.249.120.179:27017/testdb```
when I enabled authentication on the database, I had to change the URL to include a username and password:
```-e MONGO_URI=mongodb://testAdmin:badgers@11.249.120.179:27017/testdb```
