### ISSUE TITLE
Persistent Data in Azure Volume

### ISSUE THREAD

**Issue by SeanKearns96** [docker-library/mongo#713]
Hi I have created an Azure Container app simply using the mongo:5.0 image on docker hub. I am trying to make the data that gets into mongo persistent by adding an azure file share as a volume mount. However when I try set the mount path to be /data/db my container wont start. Any suggestions on how to get around this ?

**Comment by tianon** [comment]
I'd suggest checking the container logs -- it's probably complaining about the filesystem type because the way MongoDB works requires it to be a little picky about the underlying filesystem, and I imagine however Azure is providing this storage doesn't meet what MongoDB needs.
