### ISSUE TITLE
No tag available for 6.0.19 and 5.0.30

### ISSUE THREAD

**Issue by gaelcrova** [docker-library/mongo#716]
Hi,
There is not tag available on the repository for images currently in Docker hub with tags 6.0.19 and 5.0.30.
Could it be possible to put tag on related commits ?
Thanks
Regards
Gael

**Comment by yosifkit** [comment]
Sorry, we don't put git tags on commits in this repo.

The image can rebuild outside of commits to this repo like when its parent image is updated. The image index of a specific image can tell you exactly which commit, directory, and base image that the image was built from by looking at the `annotations` (`crane manifest mongo:5.0.30`)
```json
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.index.v1+json",
"manifests": [
{
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"digest": "sha256:02425a4d2150ff04e01a515388f4190d4dcc73b1912a5be5c993eda18bb07412",
"size": 2477,
"platform": {
"architecture": "amd64",
"os": "linux"
},
"annotations": {
"com.docker.official-images.bashbrew.arch": "amd64",
"org.opencontainers.image.base.digest": "sha256:e5a6aeef391a8a9bdaee3de6b28f393837c479d8217324a2340b64e45a81e0ef",
"org.opencontainers.image.base.name": "ubuntu:focal",
"org.opencontainers.image.created": "2024-10-25T23:56:47Z",
"org.opencontainers.image.revision": "65909c24a2d4c3380b7a6512fd83dbc9ce00244f",
"org.opencontainers.image.source": "https://github.com/docker-library/mongo.git#65909c24a2d4c3380b7a6512fd83dbc9ce00244f:5.0",
"org.opencontainers.image.url": "https://hub.docker.com/_/mongo",
"org.opencontainers.image.version": "5.0.30-focal"
}
},
...
```

**Comment by gaelcrova** [comment]
Hi @yosifkit , I was talking about this repo https://github.com/mongodb/mongo

**Comment by yosifkit** [comment]
Oh, we are not involved in that repo. You'd need to file something in their [issue tracker](https://jira.mongodb.org/) or perhaps email someone at MongoDB.  🤔Maybe a "contentless" pull request would work? 🙊 🤷
