### ISSUE TITLE
User and group ID mappings

### ISSUE THREAD

**Issue by LaurensRietveld** [docker-library/mongo#73]
Are you open to a PR that enables user and group ID mappings? Considering that docker has no built-in solution for this (https://github.com/docker/docker/issues/7198), the files in the shared volume end up as owned by the container mongodb user.
A simple script in the entrypoint that modifies the mongodb user and group ID (based on two environment variables) would solve this issue.

**Comment by tianon** [comment]
I think the approach we've taken in https://github.com/docker-library/elasticsearch/pull/77 is probably the one we want to follow here too (see especially the additional notes in https://github.com/docker-library/elasticsearch/pull/14#issuecomment-169177347 about why that particular solution is nice).

**Comment by yosifkit** [comment]
#81 fixed this.
