### ISSUE TITLE
Publish image for MongoDB 3.2.1

### ISSUE THREAD

**Issue by Flavien** [docker-library/mongo#75]
Given that 3.2.0 has a [critical bug](https://jira.mongodb.org/browse/SERVER-21868), it would be great to publish the image for 3.2.1.

**Comment by tianon** [comment]
Thanks for the heads up; fixed in 358d9eb. :+1:

**Comment by Flavien** [comment]
Are you also pushing to [Docker Hub](https://hub.docker.com/r/library/mongo/tags/)?

**Comment by yosifkit** [comment]
Just merged the fix to the builder: https://github.com/docker-library/official-images/pull/1339.  It is building right now.
