### ISSUE TITLE
Failure on startup if "journal" is symbolic link: error creating directory /data/db/journal: File exists: "/data/db/journal"

### ISSUE THREAD

**Issue by vincebowdren** [docker-library/mongo#77]
**Issue**: On startup, docker tries to create a journal folder in the data directory. This fails if a symbolic link called _journal_ is already present, and causes the container to error and stop.

##### Background:
It's recommended to host the [journal on a different volume](http://dba.stackexchange.com/questions/33669/mongodb-should-i-separate-the-journal-and-the-data-to-different-drives) from the data files, for performance reasons. MongoDB doesn't have an option to set the location of the journal, so this is achieved in practice by creating a symbolic link called _journal_ in the data directory, pointing to the different volume, thus:
```lrwxrwxrwx 1 mongodb mongodb   18 Jan 14 16:47 journal -> /data/otherjournal```

##### Effect

When I start the mongo docker container, it fails on startup as follows:

> 2016-01-14T16:48:17.749672599Z 2016-01-14T16:48:17.749+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
> 2016-01-14T16:48:17.749964076Z 2016-01-14T16:48:17.749+0000 I JOURNAL  [initandlisten] error creating directory /data/db/journal boost::filesystem::create_directory: File exists: "/data/db/journal"
> 2016-01-14T16:48:17.750154274Z 2016-01-14T16:48:17.749+0000 I STORAGE  [initandlisten] exception in initAndListen std::exception: boost::filesystem::create_directory: File exists: "/data/db/journal", terminating
> 2016-01-14T16:48:17.750255150Z 2016-01-14T16:48:17.750+0000 I CONTROL  [initandlisten] now exiting

(full log attached: [MongodbDockerLog.txt](https://github.com/docker-library/mongo/files/90740/MongodbDockerLog.txt) )

##### Comments

This does not seem to be a permissions problem; the symbolic link _journal_ is owned by (and therefore completely visible to) the user mongodb with uid 999.

As a workaround for now, we are advising customers to allow the docker container to create the journal in the default location i.e. in a subfolder of the data directory.

**Comment by yosifkit** [comment]
Seems to work fine here, and you don't even need a symlink! :smiley_cat:
```console
$ mkdir mongo-data mongo-journal
$ docker run -d -v ~/mongo-data/:/data/db/ -v ~/mongo-journal/:/data/db/journal/ mongo
$ ls -ln mongo-*/
mongo-data/:
total 104
-rw-r--r-- 1 999 1000 16384 Jan 27 15:10 collection-0--5103028317213166617.wt
drwxr-sr-x 2 999 1000  4096 Jan 27 15:10 diagnostic.data
-rw-r--r-- 1 999 1000 16384 Jan 27 15:10 index-1--5103028317213166617.wt
drwxr-sr-x 2   0 1000  4096 Jan 27 15:09 journal
-rw-r--r-- 1 999 1000 16384 Jan 27 15:10 _mdb_catalog.wt
-rw-r--r-- 1 999 1000     2 Jan 27 15:09 mongod.lock
-rw-r--r-- 1 999 1000  4096 Jan 27 15:09 sizeStorer.wt
-rw-r--r-- 1 999 1000    95 Jan 27 15:09 storage.bson
-rw-r--r-- 1 999 1000    49 Jan 27 15:09 WiredTiger
-rw-r--r-- 1 999 1000  4096 Jan 27 15:09 WiredTigerLAS.wt
-rw-r--r-- 1 999 1000    21 Jan 27 15:09 WiredTiger.lock
-rw-r--r-- 1 999 1000   910 Jan 27 15:10 WiredTiger.turtle
-rw-r--r-- 1 999 1000 20480 Jan 27 15:10 WiredTiger.wt

mongo-journal/:
total 307212
-rw-r--r-- 1 999 1000 104857728 Jan 27 15:10 WiredTigerLog.0000000001
-rw-r--r-- 1 999 1000 104857728 Jan 27 15:09 WiredTigerPreplog.0000000001
-rw-r--r-- 1 999 1000 104857728 Jan 27 15:09 WiredTigerPreplog.0000000002
```

**Comment by vincebowdren** [comment]
Ah, of course; mapping the data and the journal volumes separately. I've tried it out and it is working for me here too, so I can now recommend this technique to our customers who wish to separate journal and data volumes.

One caveat: the mongo container does still create the journal subfolder in the data directory, even if it's not actually using it because of the separate journal mapping.
