### ISSUE TITLE
3.2: Stacktrace, 3.0 works fine

### ISSUE THREAD

**Issue by jmkgreen** [docker-library/mongo#82]
We're deploying to a Docker host via Puppet. Deployed our app with mongo:3.2 and it was hanging - looks like mongo was stacktracing (see below).

Replaced with a 3.0 instance under exact same conditions and we're apparently happy again.

[Stacktrace](https://gist.github.com/jmkgreen/69d6599f688b7d53aee0)

The data folder in both cases is bind-mounted. On the host it is managed by puppet thus:

  file { '/mnt/reporting-server/mongo' :
    ensure  => directory,
    owner   => 'root',
    group   => 'root',
    mode    => '0755',
    require => File['/mnt/reporting-server'],
    before  => Class['docker::run_instance'],
  }

**Comment by tianon** [comment]
The lines that look suspicious to me in the provided gist are these:
`2016-02-01T15:31:30.246+0000 E STORAGE  [thread1] WiredTiger (13) [1454340690:246826][1:0x7f6f33efa700], file:WiredTiger.wt, WT_SESSION.checkpoint: /data/db/WiredTiger.turtle.set: Permission denied`
`2016-02-01T15:31:30.246+0000 E STORAGE  [thread1] WiredTiger (13) [1454340690:246963][1:0x7f6f33efa700], checkpoint-server: checkpoint server error: Permission denied`
`2016-02-01T15:31:30.247+0000 E STORAGE  [thread1] WiredTiger (-31804) [1454340690:246994][1:0x7f6f33efa700], checkpoint-server: the process must exit and restart: WT_PANIC: WiredTiger library panic`

**Comment by yosifkit** [comment]
MongoDB 3.2 changed the storage engine default to WiredTiger; perhaps there is something about your bind mount that is not WiredTiger compatible.  Try running 3.0 with `--storageEngine wiredTiger` and see if it fails also (`docker run -d -v bind/mount/:/data/db mongo:3.0 --storageEngine wiredTiger`).
