### ISSUE TITLE
segmentation fault on start on kernel 4.4.1-1-ec2

### ISSUE THREAD

**Issue by tsankuanglee** [docker-library/mongo#83]
I'm running Arch 64. Tested on several versions of mongo from this repo and all led to segmentation faults (exit code 139).

On my local machine, I also experienced the same problem on 4.4.1-1, but not 4.4.1-2.

I'll update on whether the problem vanishes on 4.4.1-2-ec2 when it's available.

It's probably a kernel bug but I thought I'll point it out for reference.

**Comment by tsankuanglee** [comment]
As an update, I still have the same problem with 4.4.3-1-ec2

**Comment by tianon** [comment]
Did you have a low amount of RAM or something that might cause a segfault? (or any luck in further narrowing down what the underlying issue actually was?)

**Comment by tianon** [comment]
(Closing for bookkeeping, but if you have more details on what we can do to improve/fix/workaround, please open a new issue!)
