### ISSUE TITLE
`docker exec -it containerId bash` exit immediately

### ISSUE THREAD

**Issue by fanguigui** [docker-library/mongo#86]
when i run `docker exec -it containerId bash`, it doesn't enter the container and exit immediately like this:
[root@localhost local]# docker exec -it -d high_fermat /bin/bash
[root@localhost local]#

**Comment by ozlerhakan** [comment]
you are using the detached mode (i.e. `-d`), can you try the command without this mode?

**Comment by fanguigui** [comment]
I want to config a mongo cluster. I run `docker run --net=host -d -v /mnt/mongo:/data/db --name primary mongo --replSet rs0` , then run `docker exec -it primary bash`, but it exit immediately. I removed -d, still the same result

**Comment by ozlerhakan** [comment]
I have done this before with not failure. Which version of mongod are you using? do you have any log details?

**Comment by fanguigui** [comment]
I re-installed docker and the problem got solved~
