### ISSUE TITLE
Retrieving key from public key server times out

### ISSUE THREAD

**Issue by uromahn** [docker-library/mongo#87]
In your Dockerfiles, you have the following two lines:
1. `gpg --keyserver ha.pool.sks-keyservers.net ...`, and
2. `apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys "$key";`

This will time out in typical corporate environment since the default port is being blocked. Instead, the commands should use the fully qualified URL on port 80. So the keyserver should be specified as follows:
`ha.pool.sks-keyservers.net` --> `hkp://ha.pool.sks-keyservers.net:80`

**Comment by tianon** [comment]
What's the use case for building from source versus consuming the prebuilt
images?

**Comment by dmazzer** [comment]
@uromahn, same problem here.

But to stablish a connection to the key server I replaced the address from:
<code>hkp://ha.pool.sks-keyservers.net:80</code>
to:
<code>hkp://p80.pool.sks-keyservers.net:80
</code>

@tianon, in my case, I need to customize the Dockerfile to suit my needs. If the use of port 80 is not a security concern, maybe should be fine to update Dockerfile with those changes.

Thanks for help

**Comment by yosifkit** [comment]
Closing old issue.  Related comment in https://github.com/docker-library/postgres/issues/262#issuecomment-279570514. Feel free to comment if you feel this was closed in error.
