### ISSUE TITLE
OpsManager agents

### ISSUE THREAD

**Issue by rafaelsisweb** [docker-library/mongo#91]
How could I setup monitor and backup agents of OpsManager to my mongodb containers?

**Comment by tianon** [comment]
Given that what I can find about Ops Manager (https://www.mongodb.com/products/ops-manager) says that it's part of "MongoDB Enterprise" (https://www.mongodb.com/products/mongodb-enterprise-advanced), it's probably best to ask the MongoDB folks how they'd imagine handling a Docker deployment as it relates to that solution.  Given that Ops Manager appears to orchestrate deployment, it would probably need explicit Docker support for it to really work effectively and appropriately.

**Comment by rafaelsisweb** [comment]
@tianon OpsManager really orchestrate deployments. But it's possible to monitor and manager backups of ready deployed mongo instances.
But to do that is needed to install an agent and set the credencials gived by OpsManager.

Maybe should be interesting has the agent embeded in the image. So the mongodb in container could be monitored by OpsManager.

In this case the credencials and opsmanager endpoint could be set by params of entrypoint.

**Comment by yosifkit** [comment]
Since it would be a separate agent process running that monitors Mongodb, I think this would be better suited for its own container with access to the mongo container, maybe even `volumes-from` if it needs direct access to the database files.

**Comment by yosifkit** [comment]
Closing old issue. Feel free to comment on further if you feel this was closed in error.
