### ISSUE TITLE
REST + JSONP

### ISSUE THREAD

**Issue by tcsweetser** [docker-library/mongo#93]
How do I enable these features at start-up?

**Comment by yosifkit** [comment]
You can either provide a config file with the options and start mongo pointing to the config `docker run -d -v /local/mongo.conf:/somewhere/mongo.conf mongo --config /somewhere/mongo.conf` (https://docs.mongodb.org/manual/reference/configuration-options/#net-http-options).

Or just pass the options as flags that mongod understands: `docker run -d mongo --rest --jsonp`

**Comment by tcsweetser** [comment]
Command line options, FTW -- many thanks!
