### ISSUE TITLE
MongoDB Image that includes Connector for BI?

### ISSUE THREAD

**Issue by jeremypumphrey** [docker-library/mongo#95]
Is there an official docker for MongoDB image that includes the Connector for BI? The installation doesn't look easy to automate so I'm not sure about adding on top of this image.

**Comment by DoronCohen** [comment]
+1

**Comment by yosifkit** [comment]
I think that would have to be offered through the Docker Store and through MongoDB Inc. since it is one of their product offerings and not open source nor free for general use.
