### ISSUE TITLE
Should gid and uid be customizable?

### ISSUE THREAD

**Issue by tozz** [docker-library/mongo#96]
Any reason why these aren't configurable from the host? Right now on 3.3 you get a uid of 999 for example, this is a bit annoying when you mount host folders as volumes.

**Comment by tianon** [comment]
You should be able to use `docker run --user` to use any arbitrary UID/GID you please; see https://github.com/docker-library/mongo/pull/81 for more details.

**Comment by tozz** [comment]
That doesn't affect the Dockerfile, everything in there is still done with the wrong uid/guid.

**Comment by yosifkit** [comment]
Correct, but if you are mounting a directory from the host you can control the permissions of that directory to be accessible by the `--user` that you specify

**Comment by yosifkit** [comment]
It should be something like this:

```console
me@host$ mkdir mongo-data
# also make a configdb directory if you need one
me@host$ id -u
1000
me@host$ docker run -d -v "$PWD/mongo-data:/data/db" --user 1000 mongo
# or 
$ docker run -d -v "$PWD/mongo-data:/data/db" --user "$(id -u)" mongo
```

**Comment by tozz** [comment]
Yes, sorry for wasting your guys time, I was under the impression that `0644` was enough of a permission but it actually needs to be `0744`.
