### ISSUE TITLE
System error: no such file or directory

### ISSUE THREAD

**Issue by ptman** [docker-library/mongo#97]
I realize this is probably low priority for you, but I thought I'd document it anyway.

On Debian testing (stretch), using docker 1.8.3, the latest mongo images fail with:

    Error response from daemon: Cannot start container 3a6e7e6044930ce36c3fe7425168aaa8531e878e5477b77ccfc2d987f00da2d9: [8] System error: no such file or directory

The image tagged mongo:3.2.5 works.

**Comment by yosifkit** [comment]
I don't see anything in the image that would break the image between `3.2.5` and `3.2.6` (ie it was only a version bump).  This looks like an issue with the host, maybe `docker rmi` and pull it again?

**Comment by ptman** [comment]
You are right. I dismissed the possibility because I thought docker had checksum checking.
